- doc/apis/modules.rst
- doc/apis/nets.rst
- doc/conf.py
- doc/index.rst
- doc/tutorial.md
Updated sphinx documnets.
- added markdown tools
- added tutorial document
- remove unnecessary document
To make html, please install following python library (for markdown).
```bash
pip install commonmark==0.5.4 recommonmark
```
refs
- https://qiita.com/pashango2/items/d1b379b699af85b529ce
- https://qiita.com/leo-mon/items/46c43f0f97f730e64754
> Updated sphinx documents

- egs/chime4/asr1_1ch/path.sh
- egs/csj/asr1/path.sh
- egs/hkust/asr1/path.sh
- egs/tedlium/asr1/path.sh
- egs/voxforge/asr1/path.sh
- egs/wsj/asr1/path.sh
Added setting about the cpu usage of blas library.
> Added setting about the cpu usage of blas library

- src/nets/e2e_asr_attctc.py
Fixed a casting issues pointed by @ShigekiKarita (Thanks a lot)
> fix cast bug

- .gitignore
- README.md
- src/bin/asr_recog.py
- src/bin/asr_train.py
- src/nets/e2e_asr_attctc.py
- src/utils/kaldi_io_py.py
- src/utils/lazy_io.py
- tools/Makefile
@sw005320  proposal for no kaldi_io. if it is hard to merge, just check
- bin/asr_train.py
- bin/asr_recog.py
- utils/lazy_io.py
> No kaldi io patch

- .gitignore
- egs/wsj/asr1/run.sh
- src/bin/asr_recog.py
- src/bin/asr_recog_th.py
- src/bin/asr_train.py
- src/bin/asr_train_th.py
- src/nets/e2e_asr_attctc.py
- src/nets/e2e_asr_attctc_th.py
- src/utils/kaldi_io_py.py
- src/utils/lazy_io.py
- tools/Makefile
This PR corresponds to #9 ,  i hope this is ready to merge. @sw005320 please run some experiments of this in python2 and chainer backend.
for no-kaldi-io discussion, see #16 (closed)
> Pytorch backend in conjunction with no-kaldi-io branch

- test/test_e2e_model.py
- test/test_initialization.py
- test/test_io_voxforge.py
- test/test_loss.py
- test/test_optimizer.py
- test/test_torch.py
> fix copyrights in test

- .travis.yml
- README.md
- tools/Makefile
- tools/conda.mk
- tools/test_requirements.txt
see #29 
try `make -f conda.mk -j`
> add makefile for conda

- .travis.yml
- pytest.ini
- setup.cfg
- src/bin/asr_recog.py
- src/bin/asr_recog_th.py
- src/bin/asr_train.py
- src/bin/asr_train_th.py
- src/nets/e2e_asr_attctc.py
- src/nets/e2e_asr_attctc_th.py
- test/test_e2e_model.py
- test/test_initialization.py
- test/test_io_voxforge.py
- test/test_loss.py
- test/test_optimizer.py
- test/test_torch.py
see #34 
I'm using `max-line-length = 120`  (actual max-line-length in this repo) to avoid E501 that limits lines to 79 chars
> add linters and fix bad lines

- egs/voxforge/asr1/RESULTS
- egs/voxforge/asr1/run.sh
> changed default decoding parameter

- egs/chime4/asr1_1ch/run.sh
- egs/librispeech/asr1/run.sh
- egs/swbd/asr1/run.sh
- egs/tedlium/asr1/run.sh
- egs/voxforge/asr1/run.sh
- egs/wsj/asr1/run.sh
- src/utils/score_sclite.sh
> added WER scoring

- doc/README.md
> added how-to-publish

- .travis.yml
- doc/README.md
- doc/apis/nets.rst
- doc/conf.py
- doc/requirements.txt
> Update README.md about travis-sphinx

- .travis.yml
- src/nets/e2e_asr_attctc_th.py
now pytorch CPU version is available https://github.com/pytorch/pytorch/issues/4178#issuecomment-356709106
> Update .travis.yml to use pytorch0.3.0

- src/nets/e2e_asr_attctc.py
- src/nets/e2e_asr_attctc_th.py
> fix logging format error

- src/nets/e2e_asr_attctc.py
This function can be replaced with `np.cumsum`.
> Use cumsum

- src/nets/e2e_asr_attctc.py
- src/nets/e2e_asr_attctc_th.py
> use cumsum and simplify reshape

- src/nets/e2e_asr_attctc.py
I recommend you to use `broadcast` or `broadcast_to` instead of `tile`. `tile` allocates another array and copy data, but `broadcast` does not.
I also replaced `reshape` with `expand_dims`. It is simpler.
> Use broadcast_to instead of tile

- egs/wsj/asr1/run.sh
- src/bin/asr_recog_th.py
- src/bin/asr_train.py
- src/bin/asr_train_th.py
- src/nets/e2e_asr_attctc.py
- src/nets/e2e_asr_attctc_th.py
- modify asr_train_th.py close to the chainer version
- modify wsj/asr1/run.sh to deal with pytorch as it does not have language model integration
- add no attention mode
> add no attention mode

- src/bin/lm_train.py
> fixed a bug in making symlink

- doc/requirements.txt
> Fixed sphinx version

- src/nets/e2e_asr_attctc_th.py
warp_ctc implementation is slightly changed.
https://github.com/SeanNaren/warp-ctc/commit/0e0d2dda779a4b47da90266c953c8b13b776aedd#diff-b0f6c89958cb2d72f64ef7336f691f49
I fixed to be compatible with current warp_ctc version.
> fixed warpctc related error

- egs/fisher_swbd/asr1/run.sh
I fixed two bugs in fisher_swbd training script. Currently I am training the network with pytorch backend and may report some result later this month.
> Fix bugs in fisher_swbd script

- .travis.yml
- tools/Makefile
> fix warp-ctc version

- src/lm/lm_pytorch.py
Fixed lm parameter initialization to make validation score stable.
> Fixed lm parameter initialization

- egs/chime5/asr1/run.sh
- src/nets/e2e_asr_attctc_th.py
- src/utils/remove_longshortdata.sh
> Fix pt lm without ctc

- src/bin/asr_recog.py
- src/nets/deterministic_embed_id.py
> Travis fix

- src/asr/asr_chainer.py
- src/asr/asr_pytorch.py
- src/nets/e2e_asr_attctc.py
- src/nets/e2e_asr_attctc_th.py
- remove greedy search code.
- fix cupy import
> Fix beamsearch

- README.md
- egs/ami/asr1/run.sh
- egs/an4/asr1/RESULTS
- egs/an4/asr1/run.sh
- egs/babel/asr1/run.sh
- egs/chime4/asr1/run.sh
- egs/chime5/asr1/run.sh
- egs/csj/asr1/run.sh
- egs/fisher_swbd/asr1/run.sh
- egs/hkust/asr1/run.sh
- egs/hub4_spanish/asr1/run.sh
- egs/li10/asr1/run.sh
- egs/librispeech/asr1/run.sh
- egs/swbd/asr1/run.sh
- egs/tedlium/asr1/run.sh
- egs/voxforge/asr1/run.sh
- egs/wsj/asr1/local/run_bpe.sh
- egs/wsj/asr1/run.sh
- src/asr/asr_chainer.py
- src/asr/asr_pytorch.py
- src/bin/asr_train.py
- src/nets/e2e_asr_attctc.py
- src/nets/e2e_asr_attctc_th.py
- src/utils/score_sclite.sh
Switch to use pure CTC or attention mode upon requests at #133. Now it is switched by specifying `--mtlalpha 0.0` (pure attention) or `--mtlalpha 1.0` (pure CTC).
> Adding pure CTC or attention mode

- src/asr/asr_pytorch.py
Tested on WSJ.
Using two 1080TI, it finished in  4.3125 hours
> multi-gpu fix

- src/asr/asr_pytorch.py
> fix problem of dataparallel and resume function

- src/asr/asr_pytorch.py
> Fixed loading the model in decoding

- src/asr/asr_pytorch.py
- src/nets/e2e_asr_attctc_th.py
> Fixed Variable flag in evaluation

- egs/librispeech/asr1/RESULTS
- egs/librispeech/asr1/run.sh
PR for added rnnlm to run.sh of librispeech.
Please let me know if this is what you meant (PR from a branch)
> librispeech: rnnlm added to run.sh

- egs/librispeech/asr1/run.sh
@JaejinCho, please do not have such mistakes in the next time!
> added lm_weight variable in the decoding directory path

- .travis.yml
- src/asr/asr_chainer.py
- src/asr/asr_pytorch.py
- src/asr/asr_utils.py
- src/bin/asr_train.py
- src/nets/e2e_asr_attctc.py
- src/nets/e2e_asr_attctc_th.py
- test/test_e2e_model.py
Added attention visualization function (#172).
> Added attention visualization function

- src/nets/e2e_asr_attctc_th.py
> fix ignore_id issue

- src/asr/asr_pytorch.py
> fixed rmmlm to be eval mode in recognition

- src/asr/asr_utils.py
> fixed pyplot not found error in resuming

- docker/espnet.devel
- docker/run.sh
- Adding user inside docker.
- Updating installation for openfst and  sentencepiece
- Installing custom NCCL. Installing from apt is still failing.
- Automatic creation of symlink for kaldi_io
> Docker updates

- egs/ljspeech/tts1/run.sh
- src/nets/e2e_tts_th.py
- src/tts/tts_pytorch.py
I found that additional use of l1loss for tacotron2 objective function leads much faster attention learning.
> TTS recipe update

- src/tts/tts_pytorch.py
> Remove default value of padding

- src/asr/asr_pytorch.py
- src/nets/e2e_asr_attctc_th.py
> Fixed a bug in the case of multi-gpu

- egs/fisher_swbd/asr1/run.sh
- chmod called before lexicon0.txt was created.
- LM training and ASR training were running simultaneous
> Fisherswbd recipe bug fixes

- src/asr/asr_pytorch.py
- src/bin/asr_train.py
- src/nets/e2e_asr_attctc_th.py
- test/test_e2e_model.py
- test/test_initialization.py
- test/test_recog.py
- scheduled sampling in working condition
> [WIP] Multilingual

- egs/librispeech/asr1/path.sh
- tools/Makefile
Fix installation script to new version of sentencepiece and path to sentencepiece.
> fix installation of sentencepiece

- src/nets/e2e_asr_attctc_th.py
> Revert AttLoc forward

- README.md
add description of protocolbuf that is required by sentencepiece.
> Add description of installing protocolbuf.

- src/asr/asr_pytorch.py
Added code to save model after each epoch, using Nelson's suggestion
> Save model after each epoch

- docker/Dockerfile
- docker/run.sh
Changing from espnet.devel to Dockerfile (This is a default configuration)
Fixing error on held package due to updates in the ubuntu (nvidia-cuda) container
> fixes and default file names

- src/nets/e2e_tts_th.py
- src/tts/tts_pytorch.py
- test/test_e2e_tts.py
unify model variable arguments between TTS and ASR (#334)
> Improve model definition consistency

- egs/ami/asr1/run.sh
- egs/an4/asr1/run.sh
- egs/babel/asr1/run.sh
- egs/chime4/asr1/run.sh
- egs/chime5/asr1/run.sh
- egs/csj/asr1/run.sh
- egs/fisher_swbd/asr1/run.sh
- egs/hkust/asr1/run.sh
- egs/hub4_spanish/asr1/run.sh
- egs/jsalt18e2e/asr1/run.sh
- egs/li10/asr1/run.sh
- egs/librispeech/asr1/local/run_spm.sh
- egs/librispeech/asr1/run.sh
- egs/librispeech/tts1/run.sh
- egs/ljspeech/tts1/run.sh
- egs/swbd/asr1/run.sh
- egs/tedlium/asr1/run.sh
- egs/voxforge/asr1/run.sh
- egs/wsj/asr1/run.sh
- src/asr/asr_chainer.py
- src/asr/asr_pytorch.py
- src/asr/asr_utils.py
- src/bin/asr_recog.py
- src/bin/lm_train.py
- src/lm/lm_chainer.py
- src/lm/lm_pytorch.py
- src/tts/tts_pytorch.py
- make report interval as a variable
- add model.json for RNNLM
- automatically find model.json from args.model
- remove model.conf reading options
#334
> refine model.json treatment

- src/asr/asr_pytorch.py
- src/asr/asr_utils.py
- src/nets/e2e_asr_th.py
- src/tts/tts_pytorch.py
- test/test_e2e_model.py
- test/test_e2e_tts.py
Remove duplicated `pad_ndarray_list` function.
> Unify padding function

- egs/jsalt18e2e/asr1/local/run_spm.sh
- egs/jsalt18e2e/asr1/path.sh
This is an JSALTe2e recipe using subword. You can run this script by 
`$ ./local/run_spm.sh`.
However, I have not tuned parameters yet.
> [WIP] JSALT subword recipe

- tools/requirements.txt
Now librosa correctly works without joblib version fixing
> fixed librosa version problem

- src/asr/asr_pytorch.py
- src/asr/asr_utils.py
- src/bin/tts_decode.py
- src/tts/tts_pytorch.py
- test/test_e2e_model.py
- test/test_e2e_tts.py
Save trainer / model / optimizer states into one file in pytorch.
- Added `torch_snapshot` to save trainer / model / optimizer states into one file
- Added `torch_resume` to resume training from new snapshot
- Unified `torch_save` and `torch_load` functions in ASR and TTS
- Added multi-gpu tests for pytorch
- Added save / load test for pytorch
- Added more docstrings
> New snapshot save function and multi-gpu tests

- egs/librispeech/asr1/local/run_spm.sh
As mentioned in https://github.com/espnet/espnet/pull/326#discussion_r211101575, fixed data set path of LM to development set.
> Fix valid dataset path of LM in Librispeech recipe.

- .gitignore
- test/test_e2e_model.py
> Add test code to check the gradient in mtl mode

- src/lm/extlm_pytorch.py
Removed unnecessary items in pytorch 0.4.1.
> Remove Variable and .data from extlm

- egs/iwslt18st/st1/local/download_and_untar.sh
Fix a bug in `egs/iwslt18/st1/local/download_and_untar.sh` (`$url` is undefined)
> Fixed undefined url problem

- src/lm/lm_chainer.py
> Fix undefined gpu_id

- src/asr/asr_chainer.py
- src/asr/asr_pytorch.py
- src/asr/asr_utils.py
#334 
- unified n-best processing 
- added score to json
Now recog part is the same among chainer and pytorch.
> Refactor recognition part

- src/nets/e2e_asr.py
- src/nets/e2e_asr_th.py
This PR fix no hypothesis bug.
If we use `minlenratio > 0.0`, there is possibility to get no hypothesis.
In this PR, if there is no hypothesis, perform recognition again with smaller `minlenratio`.
> Fix no hypothesis bug

- README.md
- egs/ami/asr1/run.sh
- egs/an4/asr1/run.sh
- egs/babel/asr1/run.sh
- egs/chime4/asr1/run.sh
- egs/chime5/asr1/run.sh
- egs/csj/asr1/local/run_spm.sh
- egs/csj/asr1/run.sh
- egs/fisher_swbd/asr1/run.sh
- egs/hkust/asr1/run.sh
- egs/hub4_spanish/asr1/run.sh
- egs/iwslt18st/st1/run.sh
- egs/jsalt18e2e/asr1/local/run_spm.sh
- egs/jsalt18e2e/asr1/run.sh
- egs/li10/asr1/run.sh
- egs/librispeech/asr1/run.sh
- egs/ljspeech/tts1/run.sh
- egs/swbd/asr1/run.sh
- egs/tedlium/asr1/run.sh
- egs/voxforge/asr1/run.sh
- egs/wsj/asr1/run.sh
- src/asr/asr_chainer.py
- src/asr/asr_utils.py
This PR makes it possible to use snapshot file (`snapshot.ep.*`) in recognition.
This feature is available in both backends.
example:
```sh
./run.sh --stage 5 --recog_model model.acc.best
./run.sh --stage 5 --recog_model snapshot.ep.15
```
> Use snapshot in recognition

- README.md
- tools/Makefile
- tools/check_install.py
- tools/conda.mk
- tools/requirements.txt
Added installation check scripts and how-to-run in README.
> Add installation check scripts

- .github/stale.yml
Add setting file for probot stale which automatically closes issue.
https://github.com/probot/stale
> Add setting file for probot stale

- .travis.yml
Fixed warpctc branch in travis (#382)
> Fix warpctc branch in travis

- tools/check_install.py
@jnishi added version information of warpctc into his fork.
So I Updated `check_install.py` to check warpctc version.
> Update check_install.py to check warpctc version

- src/asr/asr_utils.py
This PR makes it possible to check the recognition result during recognition.
> Update to show predction result during recognition

- src/asr/asr_utils.py
- src/nets/e2e_asr_th.py
- src/nets/e2e_tts_th.py
Same PR (#397)  for iwslt18 branch.
> Perform explicit value filling for attention for IWSLT branch

- src/asr/asr_pytorch.py
> Fix zero division error (#400)

- egs/chime4/asr1/RESULTS
- egs/chime4/asr1/local/ndx2flist.pl
- egs/chime4/asr1/local/wsj_data_prep.sh
- egs/chime4/asr1/local/wsj_format_data.sh
- egs/chime4/asr1/run.sh
> CHiME4 egs

- docker/run.sh
Minor fixes in run.sh for root user
> Docker fix run

- src/asr/asr_chainer.py
- src/asr/asr_pytorch.py
- src/bin/asr_train.py
- src/bin/tts_train.py
- src/tts/tts_pytorch.py
This PR changes default iterator.
> Change default iterator

- src/lm/extlm_chainer.py
- src/lm/extlm_pytorch.py
> fix word-LM division-by-zero bug

- egs/wsj/asr1/run.sh
In wsj stage 3, lm script calls undefined variable {lmdatadir}
It defined below
> lm script problem in wsj's run.sh

- CONTRIBUTING.md
- doc/README.md
- setup.py
- tools/Makefile
- tools/check_install.py
> Fix manuals and makefile

- README.md
- setup.py
- tools/Makefile
- tools/check_install.py
- tools/prefetch.patch
Support Chainer's new stable version.
> Update Chainer version to 5.0.0

- espnet/nets/e2e_asr_th.py
- espnet/nets/e2e_tts_th.py
Theoretically it should improve both training time and GPU memory usage.
> optimize masking and remove unnecessary pad_list

- README.md
- egs/librispeech/asr1/RESULTS
- egs/librispeech/asr1/run.sh
- espnet/asr/asr_pytorch.py
- espnet/bin/asr_recog.py
- update the librispeech recipe with latest LM trained with external text data
- avoid to use batch beam due to #470
> update librispeech recipe with latest LM

- espnet/lm/extlm_pytorch.py
> GPU-based beam search with word-rnnlm

- egs/csj/asr1/local/run_spm.sh
- egs/csj/asr1/run.sh
- egs/librispeech/asr1/run.sh
> Fix to use batchsize=0 in decoding for CSJ recipe

- egs/csj/asr1/local/csj_rm_tag.py
- egs/hkust/asr1/local/hkust_segment.py
Fixed shebang of python2 scripts.
This causes error when setup with python2.
> Fix shebang

- espnet/asr/chainer_backend/asr.py
- espnet/asr/pytorch_backend/asr.py
- espnet/bin/bin_utils.py
- espnet/lm/chainer_backend/lm.py
- espnet/lm/pytorch_backend/lm.py
- espnet/nets/chainer_backend/e2e_asr.py
- espnet/nets/pytorch_backend/decoders.py
- espnet/nets/pytorch_backend/nets_utils.py
- espnet/tts/pytorch_backend/tts.py
[Setting deterministic = True isn't sufficient](https://github.com/pytorch/pytorch/issues/6351)
> Fix deterministic pytorch

- egs/hkust/asr1/local/hkust_segment.py
> hkust: fix word segment script

- espnet/asr/pytorch_backend/asr.py
- espnet/nets/pytorch_backend/e2e_asr.py
- test/test_e2e_asr.py
Fix a bug when using Multi GPU for pytorch due to #484
> Fix multigpu problem on v0.3.0

- espnet/utils/cli_utils.py
- espnet/utils/io_utils.py
- tools/Makefile
- tools/check_install.py
Fixed python2/3 compatibility.
This PR covers #540.
> Fixed compatibility for python2 

- egs/fisher_callhome_spanish/asr1/RESULTS
- egs/fisher_callhome_spanish/asr1/run.sh
Better to close this https://github.com/espnet/espnet/pull/491 and merge this instead
> fisher_callhome_spanish recipe: speed perturbation and small changes (updates after starting over from v.0.3.0)

- espnet/asr/chainer_backend/asr.py
- espnet/asr/pytorch_backend/asr.py
- espnet/tts/pytorch_backend/tts.py
- utils/compute-cmvn-stats.py
- utils/copy-feats.py
- utils/feat-to-shape.py
> Follow up 493

- espnet/asr/asr_pytorch.py
Fix for
https://github.com/espnet/espnet/commit/658269ad7a117ec999f5ae470b125652aff91b10#r32018971
> Read of rnnlm during training stage

- docker/build_and_push.sh
- docker/prebuilt/devel/gpu/10.0/cudnn7/Dockerfile
- docker/prebuilt/devel/gpu/8.0/cudnn7/Dockerfile
- docker/prebuilt/devel/gpu/9.0/cudnn7/Dockerfile
- docker/prebuilt/devel/gpu/9.1/cudnn7/Dockerfile
- docker/prebuilt/devel/gpu/9.2/cudnn7/Dockerfile
- docker/prebuilt/runtime/Dockerfile
- setup.py
In response to #565,
The containers will be rebuilt once this fix is accepted.
> adding h5py to Docker containers and setup

- egs/aishell/asr1/RESULTS
- egs/aishell/asr1/cmd.sh
- egs/aishell/asr1/conf/fbank.conf
- egs/aishell/asr1/conf/gpu.conf
- egs/aishell/asr1/conf/pitch.conf
- egs/aishell/asr1/conf/queue.conf
- egs/aishell/asr1/conf/slurm.conf
- egs/aishell/asr1/local/aishell_data_prep.sh
- egs/aishell/asr1/local/download_and_untar.sh
- egs/aishell/asr1/path.sh
- egs/aishell/asr1/run.sh
- egs/aishell/asr1/steps
- egs/aishell/asr1/utils
- egs/hkust/asr1/run.sh
> add aishell recipe

- egs/librispeech/tts1/conf/fbank.conf
- egs/librispeech/tts1/run.sh
- egs/ljspeech/tts1/conf/fbank.conf
- egs/ljspeech/tts1/run.sh
- egs/ljspeech/tts2/conf/fbank.conf
- egs/ljspeech/tts2/run.sh
- egs/m_ailabs/tts1/RESULTS
- egs/m_ailabs/tts1/cmd.sh
- egs/m_ailabs/tts1/conf/fbank.conf
- egs/m_ailabs/tts1/conf/gpu.conf
- egs/m_ailabs/tts1/conf/queue.conf
- egs/m_ailabs/tts1/conf/slurm.conf
- egs/m_ailabs/tts1/local/data_prep.sh
- egs/m_ailabs/tts1/local/download.sh
- egs/m_ailabs/tts1/local/parse_text.py
- egs/m_ailabs/tts1/local/trim_silence.py
- egs/m_ailabs/tts1/local/trim_silence.sh
- egs/m_ailabs/tts1/local/update_json.sh
- egs/m_ailabs/tts1/path.sh
- egs/m_ailabs/tts1/run.sh
- egs/m_ailabs/tts1/steps
- egs/m_ailabs/tts1/utils
- espnet/nets/pytorch_backend/e2e_tts.py
- espnet/utils/io_utils.py
- test/test_e2e_tts.py
- Add M-AILABS speech dataset recipe. #561 
- Change default attention `location` to `forward_ta`
- Remove unused `conf/fbank.conf`
- Fixed attention visualization bug when `r > 1` in TTS
- Fixed `filter()` issue in python3
> TTS recipe of M-AILABS Speech dataset 

- egs/voxforge/asr1/local/make_trans.py
- tools/Makefile
> fix bugs for #567

- setup.py
- tools/Makefile
kaldiio was registered to pypi server recently.
> Changed to use pip to install kaldiio

- .gitignore
- docker/build_and_push.sh
- docker/prebuilt/devel/Dockerfile
- docker/prebuilt/devel/gpu/10.0/cudnn7/Dockerfile
- docker/prebuilt/devel/gpu/8.0/cudnn7/Dockerfile
- docker/prebuilt/devel/gpu/9.0/cudnn7/Dockerfile
- docker/prebuilt/devel/gpu/9.1/cudnn7/Dockerfile
- docker/prebuilt/devel/gpu/9.2/cudnn7/Dockerfile
- docker/prebuilt/runtime/Dockerfile
Updates to support v0.3.0 in docker containers.
Test running.
> Docker updates v0.3.0

- espnet/utils/training/iterators.py
Following @kamo-naoyuki comment
> Adds maxtaskperchild for multiprocessiterator

- README.md
- tools/Makefile
- tools/check_install.py
- Refactored `check_install.py`
- Fixed `check_install.py` to be compatible with several verions.
- Added `check_install` in Makefile to run `check_install.py` after installation
> Fixed check_install.py

- espnet/nets/chainer_backend/ctc.py
> Fix ctc_type in chainer 

- tools/Makefile
> Fix mecab installation in Ubuntu 16.04

- README.md
- egs/csj/asr1/path.sh
- egs/fisher_callhome_spanish_st/st1/path.sh
- egs/iwslt18st/st1/path.sh
- egs/jsalt18e2e/asr1/path.sh
- egs/li10/asr1/path.sh
- egs/librispeech/asr1/path.sh
- tools/Makefile
Sometimes, we want to skip the installation of `extra` modules (#606).
So I added minimum installation in Makefile.
Also, I added extra module installation check in `path.sh`.
> Add minimum installation in Makefile

- egs/wsj_mix/asr1/run.sh
> Wsj mix v.0.3.0

- espnet/nets/pytorch_backend/e2e_asr_mix.py
The iteration range of wer and cer computation was too small.
> fix bug of report_cer and report_wer in multi-speaker case

- utils/score_sclite.sh
I think this line was inserted just for debugging and he may forget to delete it.
> Disable set -x in score_sclite.sh

- egs/aishell/asr1/run.sh
- egs/chime4/asr1/run.sh
I made a mistake in several recipes in #627 .
> Fix bug #627

- egs/csj/asr1/path.sh
- egs/fisher_callhome_spanish_st/st1/path.sh
- egs/iwslt18st/st1/path.sh
- egs/jsalt18e2e/asr1/path.sh
- egs/li10/asr1/path.sh
- egs/librispeech/asr1/path.sh
@kan-bayashi `return` should be used for sourced script instead of `exit` because it drops the shell on interactive mode.
```
% source path.sh
[Exit]
```
> follow #628

- test/test_e2e_compatibility.py
Sometlmes, download from google drive is failed due to its vrius check confirmation.
To avoid it, I add extra processing.
https://stackoverflow.com/questions/20665881/direct-download-from-google-drive-using-google-drive-api
> Fix google drive download error

- egs/aishell/asr1/run.sh
- egs/ami/asr1/run.sh
- egs/an4/asr1/run.sh
- egs/babel/asr1/run.sh
- egs/chime4/asr1/run.sh
- egs/csj/asr1/run.sh
- egs/fisher_callhome_spanish_st/st1/run.sh
- egs/fisher_swbd/asr1/run.sh
- egs/hkust/asr1/run.sh
- egs/hub4_spanish/asr1/run.sh
- egs/iwslt18st/st1/run.sh
- egs/librispeech/asr1/run.sh
- egs/reverb/asr1/run.sh
- egs/swbd/asr1/run.sh
- egs/tedlium/asr1/run.sh
- egs/voxforge/asr1/run.sh
- egs/wsj/asr1/run.sh
- egs/wsj_mix/asr1/run.sh
- egs/yesno/asr1/run.sh
New `data2json.sh` can be performed after the data fixing process (see #659).
I added `utils/fix_data_dir.sh` to be called after the feature extraction as default.
> use utils/fix_data_dir.sh as default

- espnet/nets/pytorch_backend/e2e_asr.py
- espnet/nets/pytorch_backend/e2e_asr_mix.py
First, pool all the edit distances and lengths together. Then compute CER or WER.
> kaldi way of computing cer/wer

- tools/Makefile
> Add version check for matplotlib installation

- espnet/nets/pytorch_backend/e2e_asr.py
> Make sure hlens is tensor in recognize_batch

- espnet/nets/pytorch_backend/decoders.py
- espnet/nets/pytorch_backend/e2e_asr.py
- test/test_e2e_asr.py
Fix the issue (#665) and add test to perform `recognize_batch` for all of attentions.
> Fix recognize_batch for 2d, location_reccurent, multi-head attentions

- egs/tedlium/asr1/local/join_suffix.py
- egs/tedlium/asr1/run.sh
I modified the TEDLIUM recipe for supporting word LMs while referring to the WSJ recipe.
Since there is a lot of duplicated sentences in the data used for training LMs, join_suffix.py was also slightly modified.
The first word and the second word in a sentence would not join together by join_suffix.py. I wonder that this implementation is correct.
> Support word LM in TEDLIUM recipe

- README.md
- tools/Makefile
- tools/check_install.py
Adding cupy label to makefile and no-cupy flag
Referred to #674.
Did some modifications in the makefile to reuse the CUPY_VERSION flag.
in case empty, the cupy installation is avoided.
I tested with both `make` and `make CUPY_VERSION=''` without any problem.
Let me know if the modifications are acceptable to modify the Readme file also.
> No Cupy install

- egs/voxforge/asr1/local/voxforge_data_prep.sh
- egs/voxforge/asr1/run.sh
* when running the stage 0, UnicodeDeodeError was occured.
→add encoding option in local/voxforge_data_prep.sh#L127
* when running the stage 4, a problem occered:number of utterances < #splits
→change nj=32 to nj=16 in run.sh
> bugfix in voxforge

- egs/tedlium/asr1/run.sh
- espnet/bin/asr_recog.py
> Fix duplicated line in tedlium recipe

- setup.py
fix to use scikit-learn 0.20 for travis CI check. (same change is done for #691)
> use scikit-learn 0.20

- egs/voxforge/asr2/RESULTS
- egs/voxforge/asr2/cmd.sh
- egs/voxforge/asr2/conf/decode.yaml
- egs/voxforge/asr2/conf/fbank.conf
- egs/voxforge/asr2/conf/gpu.conf
- egs/voxforge/asr2/conf/pitch.conf
- egs/voxforge/asr2/conf/queue.conf
- egs/voxforge/asr2/conf/slurm.conf
- egs/voxforge/asr2/conf/train.yaml
- egs/voxforge/asr2/local/filter_text.py
- egs/voxforge/asr2/local/getdata.sh
- egs/voxforge/asr2/local/make_trans.py
- egs/voxforge/asr2/local/split_tr_dt_et.sh
- egs/voxforge/asr2/local/voxforge_data_prep.sh
- egs/voxforge/asr2/local/voxforge_format_data.sh
- egs/voxforge/asr2/path.sh
- egs/voxforge/asr2/run.sh
- egs/voxforge/asr2/steps
- egs/voxforge/asr2/utils
- Added a transformer recipe for the well-know Adi set (@arendu).
- Training is still ongoing, but already (at 100 epochs) got the better result from RNN
|           | RNN (CER%) | Transformer (CER%) |
|-----------|:----:|:----:|
| dev | 12.9| 12.2|
| test |12.6 |12.5 |
- Will add the result after the training is finished.
> Update voxforge recipe

- egs/tedlium/asr1/run.sh
Prevent a file existence error caused by spm_encode at stage 2.
> Fix a bug in the TEDLIUM recipe

- egs/ru_open_stt/asr1/RESULTS
- egs/ru_open_stt/asr1/cmd.sh
- egs/ru_open_stt/asr1/conf/decode.yaml
- egs/ru_open_stt/asr1/conf/fbank.conf
- egs/ru_open_stt/asr1/conf/gpu.conf
- egs/ru_open_stt/asr1/conf/lm.yaml
- egs/ru_open_stt/asr1/conf/pitch.conf
- egs/ru_open_stt/asr1/conf/queue.conf
- egs/ru_open_stt/asr1/conf/slurm.conf
- egs/ru_open_stt/asr1/conf/train.yaml
- egs/ru_open_stt/asr1/local/ru_open_stt_download_data.sh
- egs/ru_open_stt/asr1/local/ru_open_stt_prepare_data.py
- egs/ru_open_stt/asr1/path.sh
- egs/ru_open_stt/asr1/run.sh
- egs/ru_open_stt/asr1/steps
- egs/ru_open_stt/asr1/utils
Dataset description: https://github.com/snakers4/open_stt
Current amount of training data is 3253 hours due to dev/test subsetting and data cleanup.
> Add Russian open STT recipe

- egs/ami/asr1/run.sh
- egs/an4/asr1/run.sh
- egs/aurora4/asr1/run.sh
- egs/babel/asr1/run.sh
- egs/chime4/asr1/run.sh
- egs/chime5/asr1/run.sh
- egs/csj/asr1/local/run_spm.sh
- egs/csj/asr1/run.sh
- egs/fisher_callhome_spanish/asr1/run.sh
- egs/fisher_callhome_spanish_st/st1/local/run_asr.sh
- egs/fisher_callhome_spanish_st/st1/local/run_asr_spm.sh
- egs/fisher_callhome_spanish_st/st1/local/run_spm.sh
- egs/fisher_callhome_spanish_st/st1/run.sh
- egs/fisher_swbd/asr1/run.sh
- egs/hub4_spanish/asr1/run.sh
- egs/iwslt18/asr1/run.sh
- egs/iwslt18/st1/run.sh
- egs/jsalt18e2e/asr1/local/run_spm.sh
- egs/jsalt18e2e/asr1/run.sh
- egs/li10/asr1/run.sh
- egs/librispeech/asr1/run.sh
- egs/reverb/asr1/run.sh
- egs/ru_open_stt/asr1/run.sh
- egs/swbd/asr1/run.sh
- egs/tedlium/asr1/run.sh
- egs/timit/asr1/run.sh
- egs/voxforge/asr1/run.sh
- egs/wsj/asr1/run.sh
- egs/wsj_mix/asr1/run.sh
> Make ngpu=1 as default

- espnet/nets/pytorch_backend/e2e_tts_tacotron2.py
- espnet/nets/pytorch_backend/tacotron2/decoder.py
- espnet/nets/pytorch_backend/tacotron2/encoder.py
- Not to store unnecessary hyperparameters
- use padding_idx in Embedding
These changes do not effect previous models.
Just internal changes.
> Refactor tacotron2 modules

- egs/chime4/asr1_multich/conf/train.yaml
I forgot to write `use-frontend`
> Bug fix: egs/chime4/asr1_multich/conf/train.yaml

- espnet/utils/training/batchfy.py
Current code doesn't wok if there are two or more "categories", which is used in multi channel recipe.
> Bug fix: espnet/utils/training/batchfy.py

- tools/Makefile
fixes https://github.com/espnet/espnet/issues/832 
Use sentencepiece v0.1.82 instead of master.
> use sentencepiece v.0.1.82

- .circleci/config.yml
- .gitignore
- .travis.yml
- README.md
- ci/test_python.sh
- setup.py
This PR aims to reinforce CI to display unittest coverage. We decided to add the coverage when we found new bug in v0.4.0 release that was not covered in our unittest.
see also https://github.com/codecov/example-python
> codecov support

- .circleci/config.yml
- .gitignore
- .travis.yml
- README.md
- ci/test_python.sh
- setup.py
> codecov for master

- test/test_e2e_compatibility.py
This makes the code more readable and platform independent. With this change, I can run all unit tests successfully on osx.
> test: avoid using grep and sed in subprocess and use python stdlib instead

- espnet/nets/pytorch_backend/e2e_tts_transformer.py
I forgot to fix this bug in `calculate_all_attentions`.
> Fix a bug in calculate_all_attentions

- egs/ljspeech/README.md
- egs/ljspeech/tts1/conf/train_pytorch_tactoron2.yaml
- egs/ljspeech/tts1/run.sh
- espnet/nets/pytorch_backend/e2e_tts_tacotron2.py
- espnet/nets/pytorch_backend/e2e_tts_transformer.py
- espnet/nets/pytorch_backend/tacotron2/cbhg.py
Cleaned up comments and docstrings.
> Refactor TTS Transformer

- espnet/transform/transformation.py
This line doesn't work with function having variable keyword arguments.
> Fix: espnet/transform/transformation.py

- CONTRIBUTING.md
- README.md
- doc/tutorial.md
- egs/libritts/tts1/RESULTS.md
- espnet/utils/io_utils.py
- utils/data2json.sh
- utils/pack_model.sh
- utils/recog_wav.sh
- utils/synth_wav.sh
This is a TTS version of #581.
> Demo script for TTS

- espnet/asr/asr_utils.py
- espnet/asr/pytorch_backend/asr.py
- espnet/bin/asr_train.py
- test/test_e2e_asr.py
Read this post on gradient noise http://deliprao.com/archives/153 and found it to be effective to handle overfitting especially for librispeech.
> gradient noise injection from std normal dis

- espnet/asr/asr_utils.py
- espnet/asr/pytorch_backend/asr.py
- espnet/bin/asr_train.py
- fix a bug in the grad noise
- change the grad noise option to accept true/false argument
> fix bugs in grad noise

- egs/ljspeech/tts1/RESULTS.md
- utils/synth_wav.sh
updated model links, which including dict.
> Update LJSpeech RESULTS.md

- test_utils/test_eval_perm_free_error_py.bats
fixed the bug in test_eval_perm_free_error.py, related to #902
> Modified if conditions

- espnet/nets/pytorch_backend/transformer/plot.py
> Fix plot fail

- egs/tedlium3/asr1/local/download_data.sh
> update tedlium3 download script

- egs/libri_trans/asr1/conf/lm.yaml
- egs/libri_trans/asr1/run.sh
- egs/libri_trans/mt1/run.sh
- egs/libri_trans/st1/RESULTS
- egs/libri_trans/st1/run.sh
> Update libri trans

- espnet/nets/pytorch_backend/e2e_tts_transformer.py
- test/test_e2e_tts_transformer.py
Fixed a bug causing index out of bounds error when elayers != dlayers.
Added a test case.
> Fix a typo bug in computing guided attention loss

- espnet/nets/e2e_asr_common.py
- espnet/nets/pytorch_backend/e2e_asr_transformer.py
- test/test_utils.py
fix #952, No space in char_list
> FiX ER calculator

- espnet/asr/chainer_backend/asr.py
- espnet/asr/pytorch_backend/asr.py
- espnet/asr/pytorch_backend/asr_mix.py
- espnet/lm/chainer_backend/lm.py
- espnet/lm/pytorch_backend/lm.py
- espnet/tts/pytorch_backend/tts.py
> make tensorboard logging done every 100 iters

- README.md
- utils/synth_wav.sh
> Fix a bug in synthesis_wav.sh

- README.md
we will use [![Gitter](https://badges.gitter.im/espnet-en/community.svg)](https://gitter.im/espnet-en/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) for tiny issues and QA
> Update README.md to add badge to gitter

- egs/jsut/tts1/conf/train_pytorch_transformer.yaml
This PR adds transformer config for JSUT.
> Add Transformer config in JSUT

- .gitmodules
- .travis.yml
- ci/doc.sh
- doc/.gitignore
- doc/conf.py
- doc/index.rst
- setup.py
see this page for preview https://karita.xyz/espnet/notebook/asr_cli.html
> nbsphinx support

- tools/Makefile
Solve the issue described in Issues: Cupy Import Error. #969
> fix Cupy Import Error #969

- espnet/nets/pytorch_backend/e2e_tts_transformer.py
- test/test_e2e_tts_fastspeech.py
- test/test_e2e_tts_transformer.py
This PR makes it possible to use speaker embedding in Transformer.
To solve the dimension mismatch problem, additional linear projection layer is added after concat.
> Support multi-speaker Transformer

- test_utils/test_json2trn.py.bats
- utils/json2trn.py
This PR is to fix #993.
The reference must not be converted to unk.
@siddalmia, what do you think of this solution (this is not perfect though).
> fix unk scoring

- egs/ljspeech/tts1/RESULTS.md
Sort the results from new to old.
> Clean LJSPeech RESULTS.md

- espnet/nets/pytorch_backend/e2e_tts_transformer.py
- test/test_e2e_tts_fastspeech.py
- test/test_e2e_tts_tacotron2.py
- test/test_e2e_tts_transformer.py
This PR adds test to check TTS modules are decodable with GPU.
> Add GPU decodable test for TTS modules

- espnet/tts/pytorch_backend/tts.py
This PR adds log about the inference speed of TTS models.
> Add log of the inference speed of TTS models

- espnet/nets/chainer_backend/e2e_asr_transformer.py
Given that #1028 may take time i am pushing this fix.
For `report_cer & report_wer == false`, there is not declaration of `self.error`. I am adding a `None` declaration for these cases.
> [Bug] Fix error calculator for report false

- espnet/bin/tts_train.py
- espnet/tts/pytorch_backend/tts.py
- espnet/utils/io_utils.py
An native implementation (this is what I had locally)
Not deeply investigated yet, but it had seemed to be not working as expected (memory usage wasn't increased when I treid this a while ago). Probably I am not fully understanding how data is processed in espnet. Any ideas?
> RFC: Add keep_all_data_on_mem option

- utils/recog_wav.sh
This modification supports the other ASR recipe not only tedlium2.
> Support of other recipe in recog_wav.sh

- egs/csj/asr1/conf/tuning/train_pytorch_transformer.yaml
This PR improves reproducibility in CSJ (related to #1048).
> Update accum_grad for a single gpu in CSJ

- README.md
- egs/ljspeech/tts1/RESULTS.md
- espnet/nets/pytorch_backend/e2e_tts_fastspeech.py
- test/test_e2e_tts_fastspeech.py
- utils/convert_fbank_to_wav.py
- utils/download_from_google_drive.sh
- utils/synth_wav.sh
I found that pretrained fastspeech model does not work with `synth_wav.sh`.
This PR fix this issue.
> Minor fix to use fastspeech in synth_wav.sh

- espnet/asr/chainer_backend/asr.py
- espnet/nets/chainer_backend/rnn/attentions.py
> Fix deleted argument atype

- egs/how2/asr1/run.sh
- egs/how2/st1/local/data_prep_test.sh
- egs/how2/st1/run.sh
> Fix bug in how2 asr1

- egs/iwslt19/asr1/conf/fbank.conf
- egs/iwslt19/asr1/conf/pitch.conf
- egs/iwslt19/asr1/path.sh
- egs/iwslt19/asr1/run.sh
- egs/iwslt19/asr1/steps
- egs/iwslt19/asr1/utils
- egs/must_c/st1/local/download_and_untar.sh
This is a follow-up PR of #1120
- fixed several missing links
- add the feature extraction part with 40dims to unify the front-end condition with how2
- create `text.${case}` for tedlium2 data (simply copied from `text`)
- change to use `download_from_google_drive.sh` for the must-c download. This is more robust.
> fix iwslt19 recipe

- egs/librispeech/asr1/conf/decode.yaml
- egs/librispeech/asr1/conf/train.yaml
I forgot to update symlink of librispeech recipe in #970.
> Updated symlink in Librispeech

- espnet/asr/pytorch_backend/recog.py
- espnet/nets/pytorch_backend/lm/default.py
- utils/recog_wav.sh
This PR fixed model compatibility related to the changes in #1092, as reported in #1121.
> Fix model compatibility

- espnet/asr/pytorch_backend/asr.py
> Fix apex error when opt == “noam"

- test/test_sentencepiece.py
- test_utils/test_spm.bats
- utils/spm_train
> Update spm_train and test it

- egs/mini_an4/asr1/cmd.sh
- egs/mini_an4/tts1/cmd.sh
- test_utils/test_stdout_pl.bats
- utils/stdout.pl
The diff between stdout.pl and run.pl is one line
```diff
210c210
<     print B "( " . $cmd . ") 2>>$logfile >> $logfile";
---
>     print B "( " . $cmd . ") |& tee -a $logfile";
```
> Add stdout.pl for debugging version run.pl

- ci/test_flake8.sh
- espnet/bin/tts_decode.py
- espnet/bin/tts_train.py
- espnet/nets/pytorch_backend/e2e_tts_fastspeech.py
- espnet/nets/pytorch_backend/e2e_tts_tacotron2.py
- espnet/nets/pytorch_backend/e2e_tts_transformer.py
- espnet/nets/pytorch_backend/fastspeech/duration_calculator.py
- espnet/nets/pytorch_backend/fastspeech/duration_predictor.py
- espnet/nets/pytorch_backend/fastspeech/length_regulator.py
- espnet/nets/pytorch_backend/tacotron2/cbhg.py
- espnet/nets/pytorch_backend/tacotron2/decoder.py
- espnet/nets/pytorch_backend/tacotron2/encoder.py
- espnet/nets/tts_interface.py
- espnet/tts/pytorch_backend/tts.py
Updated docstrings to pass `flake8-docstrings`.
> Clean up TTS module docstrings

- espnet/nets/beam_search.py
- test/test_beam_search.py
- test/test_lm.py
> Sort nbest_hyps without limiting them to beam size

- setup.py
fixed h5py version as 2.9.0
#1182
> fixed h5py version as 2.9.0

- ci/install_kaldi.sh
- ci/test_shell.sh
- espnet/utils/io_utils.py
- test/test_utils.py
- test_utils/test_data2json_sh.bats
- utils/data2json.sh
modified data2json.sh and io_utils.py to support multiple parallel input cases.
> Support multiple inputs

- docker/prebuilt/local/Dockerfile
> Fix a bug in building docker container

- test/test_e2e_tts_fastspeech.py
- test/test_e2e_tts_tacotron2.py
- test/test_e2e_tts_transformer.py
Recent numpy changes cause errors when the arguments are tensor.
> Fix e2e_tts test error in CI

- egs/jsut/tts1/RESULTS.md
- egs/jsut/tts1/run.sh
The previous verison didn't contain dict files, so I updated them.
followup of #1216
> TTS: Update JSUT models

- espnet/nets/pytorch_backend/frontends/dnn_wpe.py
Fix the bug mentioned in https://github.com/espnet/espnet/issues/1272
> [bug fixing] Using inplace masked_fill_()

- espnet/nets/pytorch_backend/transformer/multi_layer_conv.py
This PR fixed docstring for #1286
> Fix docstrings

- README.md
@lingjzhu kindly provided CSMSC wavenet (Thank you so much, @lingjzhu!).
https://github.com/espnet/espnet/issues/977#issuecomment-543328268
This PR adds the pretrained wavenet model in README.
> Add Mandarin Pretrained Wavenet

- .circleci/config.yml
- espnet/nets/pytorch_backend/e2e_tts_fastspeech.py
- Fixed inference: The Array should be 2d to be written in ark file.
- Fixed loss: Loss should not be doubled when w/o PostNet
> Minor fix of FastSpeech

- README.md
- egs/csmsc/tts1/RESULTS.md
- Added csmsc transformer + wavenet samples
- Added csmsc fastspeech + wavenet samples
CSMSC FastSpeech sounds really good.
https://drive.google.com/open?id=1LLrT-Dbk7Sov75NURZTAOlNoxyTqwLQb
> Update CSMSC results

- egs/csmsc/tts1/RESULTS.md
- egs/csmsc/tts1/conf/tuning/train_fastspeech.v3.single.yaml
Fixed https://github.com/espnet/espnet/pull/1299#discussion_r339293252
> Fixed pretrained model URL in CSMSC reicpe

- egs/jsut/tts1/RESULTS.md
- egs/jsut/tts1/conf/tuning/train_fastspeech.v1.yaml
WaveNet samples: https://drive.google.com/open?id=1EFEeTjJjEJjU-NGeheWNpsraZFXlOIla
I think the results are of reasonable quality. Further improvements can be future work (#1287).
> TTS: add FastSpeech config and result for jsut

- README.md
- espnet/asr/pytorch_backend/asr.py
- espnet/nets/pytorch_backend/streaming/segment.py
- test/test_e2e_asr.py
- utils/recog_wav.sh
I slightly modified SegmentStreamingE2E class to support batch decoding. This significantly speed up streaming-based decoding.
> Support batch decoding for streaming E2E

- espnet/asr/chainer_backend/asr.py
- espnet/asr/pytorch_backend/asr.py
- espnet/asr/pytorch_backend/asr_mix.py
- espnet/mt/pytorch_backend/mt.py
- espnet/tts/pytorch_backend/tts.py
This PR changes the log level from info -> warning about the batchsize change in the case of multi-gpu (#1335).
> Change log level info -> warning about batchsize

- espnet/nets/pytorch_backend/e2e_tts_transformer.py
This PR fixes a bug of transformer attention weight calculation in inference (#1291)
> Fix TTS transformer attention weight calculation in inference

- README.md
> Fix pretrained model URL for master

- README.md
- egs/csmsc/tts1/RESULTS.md
- egs/ljspeech/tts1/RESULTS.md
- utils/synth_wav.sh
I found the bug in uploaded models so I re-uploaded and renew the URL.
> Fix pretrained model URL

- doc/conf.py
- espnet/nets/pytorch_backend/tacotron2/cbhg.py
- espnet/nets/pytorch_backend/tacotron2/decoder.py
- espnet/nets/pytorch_backend/transformer/multi_layer_conv.py
This PR fixed Sphnix warning of TTS modules.
> Fix sphinx warning of TTS modules

- utils/pack_model.sh
> Make --preprocess_conf optional in pack_model.sh

- doc/index.rst
This PR updated notebook submodule and added a notebook in the Sphinx document.
> Update notebook and add to Sphinx document

- egs/an4/tts1/conf/decode.yaml
- egs/arctic/tts1/conf/decode.yaml
- egs/blizzard17/tts1/conf/decode.yaml
- egs/csmsc/tts1/conf/decode.yaml
- egs/jnas/tts1/conf/decode.yaml
- egs/jsut/tts1/conf/decode.yaml
- egs/jvs/tts1/conf/decode.yaml
- egs/libritts/tts1/conf/decode.yaml
- egs/ljspeech/tts1/conf/decode.yaml
- egs/ljspeech/tts2/conf/decode.yaml
- egs/m_ailabs/tts1/conf/decode.yaml
- egs/tweb/tts1/conf/decode.yaml
- egs/vais1000/tts1/conf/decode.yaml
- egs/yesno/tts1/conf/decode.yaml
- espnet/bin/tts_decode.py
- espnet/nets/pytorch_backend/e2e_tts_tacotron2.py
- espnet/nets/pytorch_backend/e2e_tts_transformer.py
- espnet/nets/pytorch_backend/rnn/attentions.py
- espnet/nets/pytorch_backend/tacotron2/decoder.py
- test/test_e2e_tts_tacotron2.py
This PR adds the attention constraint introduced in Deep Voice 3.
https://arxiv.org/abs/1710.07654
Related issue: #1385
> Support attention constraint for Tacotron 2

- espnet/bin/tts_decode.py
> Fix wrong type float -> int

- ci/test_integration.sh
- espnet/asr/pytorch_backend/asr.py
> Fix multi-encoder ASR integration test

- egs2/TEMPLATE/asr1/asr.sh
- egs2/TEMPLATE/tts1/tts.sh
- espnet2/asr/decoder/transformer_decoder.py
- espnet2/asr/encoder/transformer_encoder.py
- espnet2/layers/stft.py
- espnet2/lm/e2e.py
- espnet2/tasks/asr.py
- espnet2/utils/fileio.py
- espnet2/utils/text_converter.py
- Fix typo
- Add docstring
- Fix comments in run.sh
- Fix small bug around --print_config of asr_train
> [Espnet2] small changes

- ci/test_integration.sh
- egs2/TEMPLATE/tts1/tts.sh
espnet2 part was +125second in my pc.
> [ESPnet2] Add integration test

- ci/test_integration.sh
- egs2/TEMPLATE/asr1/asr.sh
- egs2/TEMPLATE/tts1/tts.sh
This PR updated ASR recipe to unify with TTS recipe update (#1430).
- fixed shellcheck errors
- added comments for options
- updated help messages
- fixed typos
- added dumpdir
- updated tag management
> [ESPnet2] Update ASR recipe

- egs/mini_an4/tts1/run.sh
- setup.py
- utils/convert_fbank.sh
This PR fixed segmentation fault caused by the scipy update.
https://github.com/scipy/scipy/issues/11237
> Fix segmentation fault in CI

- .github/workflows/ci.yaml
- ci/test_integration.sh
- utils/free-gpu.sh
This PR adds github action support.
It can use 20 parallel jobs so it is useful to test many versions.
> Support github actions

- .github/workflows/ci.yaml
- README.md
Updated github actions setting and added badge.
> Update github actions

- README.md
This PR adds knowledge dist based FastSpeech link in README.
> Add knowledge dist based FastSpeech link in README

- egs/ljspeech/README.md
This PR adds a brief explanation about the FastSpeech training.
It helps to understand the difference between configs.
> Updated README in ljspeech about FastSpeech training

- egs/swbd/asr1/RESULTS.md
- egs/swbd/asr1/conf/lm.yaml
- egs/swbd/asr1/conf/tuning/decode_pytorch_transformer.yaml
- egs/swbd/asr1/local/fisher_data_prep.sh
- egs/swbd/asr1/run.sh
- utils/pack_model.sh
LM can be trained with Fisher English training speech transcripts.
I'll also update fisher_swbd recipe based on this pull request.
> Add LM training/decoding in swbd recipe

- ci/test_flake8.sh
- egs/must_c/mt1/conf/decode.yaml
- egs/must_c/mt1/conf/train.yaml
- egs/must_c/mt1/conf/tuning/decode_pytorch_transformer.yaml
- egs/must_c/mt1/conf/tuning/train_pytorch_transformer.yaml
- egs/must_c/mt1/run.sh
- espnet/nets/e2e_asr_common.py
- espnet/nets/e2e_mt_common.py
- espnet/nets/pytorch_backend/e2e_mt_transformer.py
- espnet/nets/pytorch_backend/transformer/plot.py
- test/test_e2e_mt_transformer.py
- Add Transformer-baed NMT model
- Visualize token strings (not index) for attention plotting
> Transformer NMT

- espnet2/tasks/abs_task.py
- espnet2/train/dataset.py
- espnet2/utils/sized_dict.py
- espnet2/utils/types.py
- test/espnet2/utils/test_sized_dict.py
- test/espnet2/utils/test_types.py
Refer: 
https://github.com/ptrblck/pytorch_misc/blob/master/shared_dict.py
I'm not sure that shared memory by Manager is really efficient, but I couldn't find another idea.
> [ESPnet2] Implement --max_cache_size option

- ci/test_shell.sh
- egs2/an4/asr1/local/data.sh
- egs2/mini_an4/asr1/local/data.sh
- egs2/vivos/asr1/local/data.sh
- egs2/voxforge/asr1/local/data.sh
- egs2/wsj/asr1/local/data.sh
- egs2/yesno/asr1/local/data.sh
> [ESPnet2] shellcheck for local/data.sh

- espnet2/tasks/abs_task.py
- espnet2/train/epoch_iter_factory.py
DataLoaders sent tesnor to GPU memory  because pin_memory=True.
> [ESPnet2] Fix bug of using GPU even if CPU mode

- egs2/TEMPLATE/asr1/pyscripts/audio/format_wav_scp.py
(Cherry-pick from #1504)
@ftshijt Please split PR as possible. The other people also works in parallel.
> [ESPnet2] Fix format_wav_scp.py

- README.md
- egs/wsj/asr1/RESULTS.md
update the new WSJ results reported in https://github.com/espnet/espnet/pull/1527 in the main README.md
> Update WSJ results in the main README.md

- egs2/TEMPLATE/asr1/asr.sh
- egs2/TEMPLATE/tts1/tts.sh
- egs2/mini_an4/asr1/local/data.sh
- egs2/mini_an4/asr1/run.sh
- egs2/mini_an4/tts1/run.sh
I also added "test_seg" in mini_an4 for ci test of the use case of segments.
> [ESPnet2] Fix bug when "segments" existing

- README.md
This is related to the discussion in #1562
> update readme to include Linux installation guides from CI

- egs2/TEMPLATE/asr1/asr.sh
- egs2/TEMPLATE/tts1/tts.sh
same problem as #1564 
referred by #1504
> bug-fix for reco2file

- espnet2/asr/frontend/default.py
If win_length is None, assign same value as n_fft.
https://github.com/espnet/espnet/pull/1529#issuecomment-585397145
> [ESPnet2] Change defalt of win_length to None

- ci/test_shell.sh
Fix this problem:
https://github.com/espnet/espnet/pull/1504#issuecomment-585000987
~I also changed to use .shellcheckrc.~
> [ESPnet2] Fix ci for local/data.sh

- README.md
This PR add MT result on IWSLT'16 corpus. (cont. from [this PR](https://github.com/espnet/espnet/pull/1544))
> Add MT result

- espnet/nets/ctc_prefix_score.py
- espnet/nets/pytorch_backend/rnn/decoders.py
- test/test_recog.py
Update for #1508. Changed CTC score computation so that it is always P(y_i=blank|y_1,...,y_i-1)=0
> Fix pure CTC decoding

- egs2/vivos/asr1/run.sh
> [ESPnet2] vivos recipe: --audio_format wav

- egs/ami/asr1/run.sh
Not sure if this is a typo? Or the script only supports IHM? Thanks.
> Fix a typo in AMI script?

- egs2/TEMPLATE/asr1/asr.sh
> [ESPnet2] Change "" to none

- egs2/TEMPLATE/asr1/asr.sh
- egs2/wsj/asr1/local/data.sh
- egs2/wsj/asr1/run.sh
- espnet2/text/build_tokenizer.py
- espnet2/text/char_tokenizer.py
- espnet2/text/word_tokenizer.py
(Discussed in #1504)
- Remove nlsyms when word scoring
- Added nlsyms.txt for WSJ (I forgot it)
I don't know what is correct way to handle nlsyms for BPE.
> [ESPnet2]Remove nlsyms when word scoring

- egs/csmsc/tts1/local/data_download.sh
- egs/csmsc/tts1/run.sh
- Fixed wrong data split
- Fixed wrong path
- Added `-w` option for `nkf` (Maybe not needed but for safety)
> Fix a bug in csmsc recipe

- espnet/asr/pytorch_backend/asr_init.py
- espnet/bin/tts_train.py
- espnet/tts/pytorch_backend/tts.py
This PR adds options to load pretrained model in TTS.
Related to #1591
> Add option to load pretrained model in TTS

- espnet/asr/pytorch_backend/asr.py
- espnet/asr/pytorch_backend/asr_mix.py
- espnet/mt/pytorch_backend/mt.py
- espnet/st/pytorch_backend/st.py
This PR fix LM backward compatibility issue.
Related: #1646 #1638 #1623
> Fix lm backward compatibility

- egs/fisher_callhome_spanish/st1/run.sh
Cleaned up some lines in `run.sh`.
> Remove unnecessary lines on Fisher-CallHome Spanish

- espnet/nets/pytorch_backend/lm/default.py
This PR fix LM backward compatibility issue for api v2.
Related: #1646 #1638 #1623
> Fix lm compatibility for v2

- egs/tedlium2/asr1/RESULTS.md
#1590 
We recovered the file provided by @ahmedalbahnasawy (many thanks!)
> Fix model link in the tedlium2 recipe

- espnet2/tasks/abs_task.py
- espnet2/train/trainer.py
- Use amp.state_dict() and amp.load_state_dict()
- Register the optimizers of apex
> Save apex state in checkpoint and support apex optimizer

- egs2/TEMPLATE/asr1/path.sh
- egs2/TEMPLATE/tts1/path.sh
- egs2/csj/asr1/path.sh
- egs2/how2/asr1/path.sh
- egs2/jsut/asr1/path.sh
- espnet2/train/trainer.py
- Double quoter for NCCL_SOCKET_IFNAME
- Small fix for comment
> Double quoter for NCCL_SOCKET_IFNAME

- egs/must_c/mt1/RESULTS.md
- egs/must_c/mt1/conf/tuning/decode_pytorch_transformer.2en.lc.rm.yaml
- egs/must_c/mt1/conf/tuning/decode_pytorch_transformer.2en.tc.yaml
- egs/must_c/mt1/run.sh
- utils/score_bleu.sh
Add `--reverse_direction` in `must_c/mt1` for the back translation option (not in this PR).
> Add reverse_direction option to MT

- espnet2/tasks/abs_task.py
(I think this is a bug of pytorch)
```python
state = torch.load("a.pth", map_location="cuda")
state = torch.load("a.pth", map_location=torch.device("cuda"))
state = torch.load("a.pth", map_location=f"cuda:{torch.cuda.current_device())}")
```
Therefore I just changed it.
> Fix the gpu device when resuming

- egs/jsut/asr1/conf/tuning/train_pytorch_transformer.v1.yaml
- egs/jsut/asr1/conf/tuning/train_pytorch_transformer.v2.yaml
- egs/tedlium2/asr1/conf/tuning/train_pytorch_transformer.v1.yaml
- egs/tedlium2/asr1/conf/tuning/train_pytorch_transformer.v2.yaml
- egs/tedlium3/asr1/conf/tuning/train_transformer.yaml
- egs/voxforge/asr1/conf/tuning/train_pytorch_transformer.yaml
- egs/voxforge/asr1/conf/tuning/train_pytorch_transformer_d6-2048.yaml
> remove non-available options

- espnet2/tasks/abs_task.py
- espnet2/utils/types.py
- test/espnet2/utils/test_types.py
--chunk_length can be int or str like "100,200,400" (=[100, 200, 400]) or "100-300" (=range(100, 300)).
(type=str is no problem)
> Change the type of --chunk_length to str_or_int

- espnet2/tasks/abs_task.py
- setup.py
https://github.com/jettify/pytorch-optimizer
This repository looks useful.
> Support torch_optimizer

- setup.py
Workaround for bug of configargparse==1.2 https://github.com/bw2/ConfigArgParse/issues/179
> Workaround for bug of configargparse==1.2

- espnet2/tasks/abs_task.py
The char "%" can be used for help argument.
> % -> percent:   espnet2/tasks/abs_task.py

- espnet2/train/trainer.py
Before:
- Keep n-Best models only for each epoch. Remove the latest model if it's not in n-best
After:
-  Keep n-Best models and the latest model for each epoch 
- Create a symlink: `latest.pth`
> keep the latest model

- espnet/nets/pytorch_backend/e2e_asr_transducer.py
- test/test_e2e_compatibility.py
- utils/spm_encode
This PR makes the compatibility test to be skipped since the download from google drive is often failed.
Related to #1636.
> Skip compatibility test

- espnet/nets/pytorch_backend/ctc.py
- test/test_train_dtype.py
- test/test_transformer_decode.py
> Fix torch.ctc not implemented in float16 by casting float32

- espnet/nets/pytorch_backend/nets_utils.py
- espnet/nets/pytorch_backend/transformer/decoder.py
- espnet/nets/pytorch_backend/transformer/encoder.py
- test/test_e2e_asr_transformer.py
> Fix v.0.3.0 pretrained Transformer model compatibility

- utils/synth_wav.sh
I added note for `synth_wav.sh` to make it clear the usage.
> Add note in synth_wav.sh

- README.md
- utils/synth_wav.sh
This PR enables to synthesize multiple sentence in `synth_wav.sh`.
> Support multiple sentences in synth_wav.sh

- egs/ljspeech/tts2/run.sh
in stage 4, train_config should be used, not decode_config.
> bugfix in ljspeech/tts2

- egs/ljspeech/tts2/run.sh
> Optionize trans_type in egs/ljspeech/tts2

- espnet/nets/pytorch_backend/rnn/encoders.py
Summary:
- Remove dropout argument in RNN init
- Add dropout attribute to RNNP
- Call `F.dropout` in all but last layer
-  Some minor other changes that make the code more readable in my opinion
> fix https://github.com/espnet/espnet/issues/1780

- setup.py
The bug of https://github.com/bw2/ConfigArgParse/issues/179 was fixed.
#1764
> Change to configargparse>=1.2.1

- setup.py
The issue of scipy==1.4.0 was fixed by https://github.com/scipy/scipy/issues/11237
#1450
> Change to scipy>=1.4.1

- egs/tedlium3/asr1/RESULTS.md
This is related to #1839 
@ahmedalbahnasawy, could you check that it's working?
> fix the missing link of tedlium3

- espnet/tts/pytorch_backend/tts.py
> Fix param freeze (#1863)

- espnet2/train/abs_espnet_model.py
I forgot to remove unused part.
> followup #1867

- egs/ru_open_stt/asr1/RESULTS.md
> docs: added fbank link to the experiment readme

- doc/docker.md
- docker/build.sh
- docker/prebuilt/devel/Dockerfile
- docker/run.sh
Support for espnet2
rebuild containers
> Docker update

- espnet/tts/pytorch_backend/tts.py
`state_dict()` is not suitable for freezing weights.
> fix freezing modules

- doc/tutorial.md
- espnet/asr/pytorch_backend/asr.py
- espnet/asr/pytorch_backend/asr_init.py
- espnet/asr/pytorch_backend/asr_mix.py
- espnet/bin/asr_train.py
- espnet/mt/pytorch_backend/mt.py
- espnet/nets/pytorch_backend/transformer/optimizer.py
- espnet/st/pytorch_backend/st.py
- espnet/tts/pytorch_backend/tts.py
Hi,
This PR add freezing parameters option + documentation for finetuning options (transfer learning + freezing). Feel free to tell me or modify docs if it lacks clarity!
> Finetuning doc + freezing parameters option

- espnet/nets/pytorch_backend/e2e_tts_transformer.py
- utils/download_from_google_drive.sh
- Fixed import place not to load unnecessary modules
- Fixed comments
> Minor fix of import place and comments

- espnet2/train/trainer.py
From pytorch1.5, clip_grad_norm_ returns torch.Tensor
> Minor fix for pytorch=1.5

- espnet/transform/cmvn.py
> fixed typo in cmvn.py

- espnet/mt/pytorch_backend/mt.py
- espnet/nets/e2e_asr_common.py
- espnet/nets/e2e_mt_common.py
- espnet/nets/pytorch_backend/e2e_mt.py
- espnet/nets/pytorch_backend/e2e_mt_transformer.py
- espnet/nets/pytorch_backend/e2e_st.py
- espnet/nets/pytorch_backend/e2e_st_transformer.py
- espnet/st/pytorch_backend/st.py
- Fixed PPL calculation
- Fix BLEU calculation
- Refine ST/MT scripts to keep consistency
> Fix BLEU/PPL calculation during training

- espnet2/main_funcs/calculate_all_attentions.py
- test/espnet2/main_funcs/test_calculate_all_attentions.py
> fix calculate_all_attentions for multihead attention

- espnet/nets/pytorch_backend/e2e_asr.py
- espnet/nets/pytorch_backend/e2e_mt.py
- espnet/nets/pytorch_backend/e2e_st.py
pointed by Daniel Garcia-Romero (many thanks!)
> fix a typo for the decoder add_argument_group

- README.md
- utils/recog_wav.sh
> fix tedlium2/3 model link

- utils/compute-fbank-feats.py
- utils/compute-stft-feats.py
- utils/make_fbank.sh
- utils/make_stft.sh
@kan-bayashi I changed to support resampling in utils/compute-fbank-feats.py and  utils/compute-stft-feats.py. What do you think?
> resampling in utils/compute-fbank-feats.py and  utils/compute-stft-feats.py

- espnet2/tasks/abs_task.py
The intermediate states from checkpoint survives during training, so it increases the memory usage by that size.
I moved this resuming  process to a function, so all intermediate values are deleted.
> Fix memory issue when resuming

- utils/recog_wav.sh
- utils/synth_wav.sh
> Fix download file extension

- espnet/nets/pytorch_backend/e2e_asr.py
- espnet/nets/pytorch_backend/e2e_asr_transducer.py
- espnet/nets/pytorch_backend/e2e_asr_transformer.py
This PR fixed the compatibility issue (#2048 #2060).
> Fix old model compatibility #2048 #2060

- README.md
- egs/tedlium2/asr1/RESULTS.md
- egs/tedlium3/asr1/RESULTS.md
- utils/recog_wav.sh
This PR the issue in #2053.
I cleaned pretrained model's content and re-uploaded.
And to avoid the questions, we use api=v1 as default for the streaming RNN models.
> Fix pretrained model #2053

- espnet/nets/scorer_interface.py
> scorerinterface warning English correction

- egs2/TEMPLATE/asr1/asr.sh
Fix minor bug in asr template recipe
> Fix bug for feats_type=extracted

- tools/Makefile
I fixed some dependencies bugs due to my latest updating.
> Fix Makefile

- egs/commonvoice/asr1/RESULTS.md
Fix issue of https://github.com/espnet/espnet/issues/2099
> updatemodel link (add pre-trained bpe model and lm model)

- egs2/TEMPLATE/asr1/asr.sh
- egs2/TEMPLATE/tts1/tts.sh
https://github.com/espnet/espnet/commit/c989c1d0de3c91bed1279cd71fc39e2322b3eedc
> Change stats_dir naming not to overwrite

- egs2/TEMPLATE/asr1/db.sh
- egs2/csmsc/tts1/cmd.sh
- egs2/csmsc/tts1/conf/decode.yaml
- egs2/csmsc/tts1/conf/fbank.conf
- egs2/csmsc/tts1/conf/pbs.conf
- egs2/csmsc/tts1/conf/queue.conf
- egs2/csmsc/tts1/conf/slurm.conf
- egs2/csmsc/tts1/conf/train.yaml
- egs2/csmsc/tts1/conf/tuning/decode_tacotron2.yaml
- egs2/csmsc/tts1/conf/tuning/train_tacotron2.yaml
- egs2/csmsc/tts1/db.sh
- egs2/csmsc/tts1/local/data.sh
- egs2/csmsc/tts1/local/data_download.sh
- egs2/csmsc/tts1/path.sh
- egs2/csmsc/tts1/pyscripts
- egs2/csmsc/tts1/run.sh
- egs2/csmsc/tts1/scripts
- egs2/csmsc/tts1/steps
- egs2/csmsc/tts1/tts.sh
- egs2/csmsc/tts1/utils
- espnet2/bin/tokenize_text.py
- espnet2/tasks/tts.py
- espnet2/text/phoneme_tokenizer.py
- setup.py
- test/espnet2/text/test_phoneme_tokenizer.py
This PR adds CSMSC TTS recipe and pypinyin-based phoneme tokenizer.
- Add new phoneme tokenizer `pypinyin_g2p` and `pypinyin_g2p_phone`
- Remove some dependencies from setup.py, which are included in `espnet_tts_frontend`
- Add new dependency `pypinyin` in `espnet_tts_frontend` https://github.com/espnet/espnet_tts_frontend/pull/3
> Add ESPnet2 CSMSC TTS recipe

- egs2/wsj/asr1/conf/tuning/train_lm.yaml
> fix best_model_criterion:   wsj/asr1/conf/tuning/train_lm.yaml

- egs2/vctk/tts1/path.sh
> Add missing path.sh in egs2/vctk/tts1

- espnet/mt/pytorch_backend/mt.py
- espnet/nets/pytorch_backend/e2e_asr_transformer.py
- espnet/nets/pytorch_backend/e2e_mt.py
- espnet/nets/pytorch_backend/e2e_mt_transformer.py
- espnet/nets/pytorch_backend/e2e_st.py
- espnet/nets/pytorch_backend/e2e_st_transformer.py
- espnet/st/pytorch_backend/st.py
- test/test_e2e_mt_transformer.py
- test/test_e2e_st_transformer.py
I added lightweight and dynamic convolutions to Transformer-based ST/MT models.
> Fix ST/MT models for compatibility with ASR

- espnet2/text/phoneme_tokenizer.py
> fix #2198:   PhonemeTokenizer can't perform with multiprocessing

- setup.py
Librosa 0.8.0 was out and numba compatibility issue was fixed.
> Change the requirement of librosa

- egs/fisher_callhome_spanish/st1/run.sh
- egs/how2/st1/run.sh
- egs/libri_trans/st1/run.sh
- egs/mboshi_french/st1/run.sh
- egs/must_c/mt1/run.sh
- egs/must_c/st1/run.sh
This is for semi-supervised training data generation in future research.
> Add source case information to json files in ST task

- egs2/TEMPLATE/enh1/enh.sh
> fix the stage number: enh.sh

- egs2/TEMPLATE/tts1/tts.sh
- egs2/csmsc/tts1/run.sh
- egs2/jsut/tts1/run.sh
- egs2/ljspeech/tts1/run.sh
- egs2/vctk/tts1/run.sh
- espnet2/bin/tts_inference.py
- espnet2/tts/espnet_model.py
- espnet2/tts/feats_extract/log_mel_fbank.py
- espnet2/tts/feats_extract/log_spectrogram.py
This PR fixes some bugs in tts_inference.
- When using teacher forcing, probs is None. So I added check of the existence.
- normalize.inverse is in-place. I added .clone() to avoid this issue.
- Added missing default arguments.
- `decode_config` -> `inference_config`
> Fix TTS inference

- espnet2/bin/asr_inference.py
> avoid UnboundLocalError when lm is not loaded

- espnet2/train/reporter.py
- espnet2/train/trainer.py
- test/espnet2/train/test_reporter.py
#2183 
Now the statistics registered by tensorboard are only epoch averaged values. I updates the reporter to register the averaged values between logging_interval iterations.
> Tensorboard stats between iterations

- ci/test_integration.sh
- egs2/TEMPLATE/asr1/asr.sh
- egs2/TEMPLATE/enh1/enh.sh
- egs2/TEMPLATE/tts1/tts.sh
> Add coverage measure for espnet2 integration test

- espnet2/train/reporter.py
- espnet2/train/trainer.py
- test/espnet2/train/test_reporter.py
FIX #2261 
(this bug comes from #2252 )
> fix bug of reporter

- egs/aidatatang_200zh/asr1/RESULTS.md
- egs/aidatatang_200zh/asr1/conf/train.yaml
- egs/aidatatang_200zh/asr1/conf/tuning/train_pytorch_conformer.yaml
- egs/aidatatang_200zh/asr1/run.sh
added conformer recipe and results
> aidatatang conformer ESPnet1 recipe

- espnet/nets/pytorch_backend/conformer/subsampling.py
- espnet/nets/pytorch_backend/transformer/attention.py
- espnet/nets/pytorch_backend/transformer/decoder_layer.py
- espnet/nets/pytorch_backend/transformer/encoder_layer.py
- espnet/nets/pytorch_backend/transformer/mask.py
Update the shape description to avoid confusing user. Fix typos in conformer subsampling class by the way.
> Update comments in MultiHeadAttention

- egs2/TEMPLATE/asr1/asr.sh
- egs2/TEMPLATE/enh1/enh.sh
- egs2/TEMPLATE/tts1/tts.sh
> Fix for queue-freegpu.pl

- egs2/TEMPLATE/asr1/scripts/utils/show_asr_result.sh
> decode -> inference

- espnet2/train/reporter.py
> Avoid illegal summary name for tensorboard

- espnet/nets/scorers/ngram.py
it is a basic bug fix, I will make a unit test later.
or you guys want to I merge them together?
> ngram single decoding bug fix

- README.md
- egs2/TEMPLATE/tts1/README.md
- egs2/csmsc/tts1/conf/tuning/decode_fastspeech.yaml
- egs2/csmsc/tts1/conf/tuning/train_fastspeech.yaml
- egs2/csmsc/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/csmsc/tts1/conf/tuning/train_transformer.yaml
- egs2/jsut/tts1/conf/tuning/train_transformer.yaml
- egs2/ljspeech/tts1/conf/tuning/decode_fastspeech.yaml
- egs2/ljspeech/tts1/conf/tuning/train_fastspeech.yaml
- egs2/ljspeech/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/ljspeech/tts1/conf/tuning/train_transformer.yaml
- egs2/vctk/tts1/conf/tuning/decode_fastspeech.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_fastspeech.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_transformer.yaml
This PR adds README about ESPnet2 TTS recipe.
> Add ESPnet2 TTS recipe document

- espnet/nets/pytorch_backend/e2e_tts_tacotron2.py
> Fix device allocation error in guided attention loss #2282

- doc/tutorial.md
The comment is about steps directory therefore changed utils to steps.
> updated comment on the documentation

- README.md
- test_utils/integration_test_asr_align_wav.bats
- utils/asr_align_wav.sh
This pull request adds a small demo to `README.md`, as requested in #2301.
> CTC segmentation - Demo

- egs/wsj/asr1/local/filtering_samples.py
- egs/wsj/asr1/run.sh
This PR fixes the bug in espnet/egs/wsj/asr1/local/filtering_samples.py reported by https://github.com/espnet/espnet/issues/2211.
> Fix issue https://github.com/espnet/espnet/issues/2211

- doc/installation.md
This is related to the question in https://github.com/espnet/espnet/issues/525#issuecomment-679253442
> add a description about check install.

- egs2/TEMPLATE/asr1/asr.sh
- egs2/TEMPLATE/enh1/enh.sh
- egs2/TEMPLATE/tts1/tts.sh
- espnet2/main_funcs/pack_funcs.py
- test/espnet2/main_funcs/test_pack_funcs.py
I changed the packing stage to include the images of the experiment. I also added ppl result in packed model.
> Support recursive add in pack_funcs and add images to packed model

- espnet2/main_funcs/pack_funcs.py
> fix recursive add:   espnet2/main_funcs/pack_funcs.py

- ci/install.sh
- egs/tedlium2/align1/path.sh
- setup.py
> Remove ctc_segmentation temporary

- espnet/asr/asr_utils.py
ESPnet2 TTS depends on asr_utils.py, and it depends on chainer, so I changed it to lazy import. I also changed matplotlib to lazy import.
> Lazy import chainer in asr_utils.py

- egs2/TEMPLATE/asr1/asr.sh
> fix the directory for init_file_prefix

- README.md
- egs2/TEMPLATE/tts1/README.md
- egs2/csmsc/tts1/conf/tuning/train_conformer_fastspeech.yaml
- egs2/csmsc/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/jsut/tts1/conf/tuning/train_conformer_fastspeech.yaml
- egs2/jsut/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/ljspeech/tts1/conf/tuning/train_conformer_fastspeech.yaml
- egs2/ljspeech/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- espnet2/tts/fastspeech.py
- espnet2/tts/fastspeech2.py
- test/espnet2/tts/test_fastspeech.py
- test/espnet2/tts/test_fastspeech2.py
This PR supports Conformer for FastSpeech & FastSpeech2.
I've not yet checked the performance.
> Support Conformer-based FastSpeech / FastSpeech2

- egs2/csmsc/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/csmsc/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/jsut/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/jsut/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/ljspeech/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/ljspeech/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_conformer_fastspeech2.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_fastspeech2.yaml
- Update gradient stopping setting in Fastspeech2 config
- Add GST-based Fastpseech2 config
> Update and add fastspeech2 configs

- egs2/csmsc/tts1/conf/tuning/train_conformer_fastspeech.yaml
- egs2/csmsc/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/csmsc/tts1/conf/tuning/train_fastspeech.yaml
- egs2/csmsc/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/csmsc/tts1/conf/tuning/train_tacotron2.yaml
- egs2/csmsc/tts1/conf/tuning/train_transformer.yaml
- egs2/jsut/tts1/conf/tuning/train_conformer_fastspeech.yaml
- egs2/jsut/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/jsut/tts1/conf/tuning/train_fastspeech.yaml
- egs2/jsut/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/jsut/tts1/conf/tuning/train_tacotron2.yaml
- egs2/jsut/tts1/conf/tuning/train_transformer.yaml
- egs2/ljspeech/tts1/conf/tuning/train_conformer_fastspeech.yaml
- egs2/ljspeech/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/ljspeech/tts1/conf/tuning/train_fastspeech.yaml
- egs2/ljspeech/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/ljspeech/tts1/conf/tuning/train_tacotron2.yaml
- egs2/ljspeech/tts1/conf/tuning/train_transformer.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_conformer_fastspeech2.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_fastspeech.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_fastspeech2.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_tacotron2.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_transformer.yaml
- Change to use `num_iters_per_epoch` option in config
- Fix wrong structure of variance predictor in FastSpeech2
> Update ESPnet2 TTS config

- espnet2/tts/feats_extract/energy.py
- test/espnet2/tts/feats_extract/test_energy.py
Sum axis is wrong in energy extraction.
This PR fixed the above issue.
> Fix wrong sum axis in energy extraction

- ci/install.sh
- egs/hkust/asr1/local/hkust_data_prep.sh
- egs/hkust/asr1/run.sh
- tools/Makefile
- tools/installers/install_py3mmseg.sh
Fix #2321#2433
- I forked py3mmseg for python3.7: https://github.com/kamo-naoyuki/py3mmseg
- Add -L option to find. This recipe is failed if the specified corpus directory is a symlink. We should use find command more carefully.
- Now speed perturbation is applied after feature extraction. It causes the problem of #2433. We should use utils/fix_data_dir.sh more carefully. 
- Such a ridiculous problem never happens in espnet2. We should move all to espnet2 quickly.
> Fix HKUST recipe

- espnet2/train/preprocessor.py
This is the PR for fixing the #2450.  I've add the missing Class.
I think it's because @shincling forgot to commit it in the `espnet2/train/preprocessor.py` in the last PR.
> Fix the CommonPreprocessor_multi missing issue

- test/test_e2e_asr_mulenc.py
(local run time 152.75s -> 8.86s)
1. decreased the feature size and model size
2. created a separate test module for ctc plot and att plot
3. deleted/merged redundant test cases
> make test_e2e_asr_mulenc.py faster 

- espnet/nets/batch_beam_search.py
> Fixed IndexError in BatchBeamSearch.post_process() (#2483)

- test/espnet2/enh/nets/test_tasnet.py
this is the PR for testing faster #2459 
Now, testing for TasNet takes 7.01s in my local.
> shorten test time for tasnet

- egs/an4/asr1/local/data_prep.py
- egs/csj/asr1/local/csj_rm_tag.py
- egs/iwslt18/st1/local/ctm2segments.py
- egs/jnas/asr1/local/filter_text.py
- egs/libri_trans/st1/local/concat_json_multiref.py
- egs/mini_an4/asr1/local/data_prep.py
- egs/mini_an4/asr_mix1/local/data_prep.py
- egs/voxforge/asr1/local/filter_text.py
- espnet/asr/chainer_backend/asr.py
- espnet/lm/chainer_backend/extlm.py
- espnet/lm/chainer_backend/lm.py
- espnet/lm/pytorch_backend/extlm.py
- espnet/nets/chainer_backend/rnn/training.py
- utils/addjson.py
- utils/concatjson.py
- utils/filt.py
- utils/json2text.py
- utils/merge_scp2json.py
- utils/mergejson.py
- utils/result2json.py
- utils/scp2json.py
- utils/splitjson.py
- utils/spm_decode
- utils/spm_encode
- utils/text2token.py
- utils/trim_silence.py
python3 does not need these lines
> Remove all __future__ lines

- egs2/csmsc/tts1/conf/tuning/train_transformer.yaml
- egs2/jsut/tts1/conf/tuning/train_transformer.yaml
- egs2/ljspeech/tts1/conf/tuning/train_transformer.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_transformer.yaml
- Lamb is stable in the training, but in synthesis it causes many attention errors.
- Use before_normalize=True to make both the training and synthesis stable.
> Update Transformer-TTS configs

- espnet/bin/mt_trans.py
- espnet/bin/st_trans.py
- espnet/mt/pytorch_backend/mt.py
- espnet/nets/pytorch_backend/e2e_mt_transformer.py
- espnet/nets/pytorch_backend/e2e_st_transformer.py
- espnet/st/pytorch_backend/st.py
This PR changes decoding scripts in ST/MT tasks as follows:
- Change decoding to hypothesis-level batch decoding
- Remove RNNLM integration to simplify the codes.
> Refactor decoding for translation tasks

- espnet/nets/pytorch_backend/conformer/convolution.py
- espnet/nets/pytorch_backend/conformer/encoder.py
- espnet/nets/pytorch_backend/conformer/encoder_layer.py
- espnet/nets/pytorch_backend/transformer/attention.py
- espnet/nets/pytorch_backend/transformer/decoder.py
- espnet/nets/pytorch_backend/transformer/decoder_layer.py
- espnet/nets/pytorch_backend/transformer/embedding.py
- espnet/nets/pytorch_backend/transformer/encoder.py
- espnet/nets/pytorch_backend/transformer/encoder_layer.py
- espnet/nets/pytorch_backend/transformer/layer_norm.py
- espnet/nets/pytorch_backend/transformer/multi_layer_conv.py
- espnet/nets/pytorch_backend/transformer/positionwise_feed_forward.py
- espnet/nets/pytorch_backend/transformer/repeat.py
- espnet/nets/pytorch_backend/transformer/subsampling.py
- espnet2/asr/encoder/conformer_encoder.py
- espnet2/tasks/asr.py
- test/espnet2/asr/encoder/test_conformer_encoder.py
- Support `conformer_encoder` in ESPnet2 ASR
- Update docstrings related to transformer
> Support conformer encoder in ESPnet2 ASR

- espnet/nets/pytorch_backend/e2e_asr.py
- espnet/nets/pytorch_backend/e2e_asr_transformer.py
- espnet/nets/pytorch_backend/e2e_mt.py
- espnet/nets/pytorch_backend/e2e_mt_transformer.py
- espnet/nets/pytorch_backend/e2e_st.py
- espnet/nets/pytorch_backend/e2e_st_transformer.py
- espnet/nets/pytorch_backend/rnn/argument.py
- espnet/nets/pytorch_backend/transformer/argument.py
This PR removes duplicate lines for the argument parser in ASR/ST/MT tasks.
> Unify arguments

- egs2/TEMPLATE/asr1/asr.sh
> remove cleaner

- egs/jsut/asr1/RESULTS.md
- egs/jsut/asr1/conf/specaug.yaml
- egs/jsut/asr1/conf/train.yaml
- egs/jsut/asr1/conf/tuning/train_pytorch_conformer.yaml
- egs/jsut/asr1/run.sh
- update a result with conformer
- obtained 14.5% from 18.7% with conformer and specaug (speed perturbation was not effective, but I just included it)
> update the JSUT recipe with conformer

- egs2/TEMPLATE/tts1/README.md
- espnet2/text/build_tokenizer.py
- espnet2/text/phoneme_tokenizer.py
- test/espnet2/text/test_phoneme_tokenizer.py
> Support `g2p=none` for text with phonemes

- ci/doc.sh
- doc/apis/espnet2_bin.rst
- doc/index.rst
- doc/usage2rst.sh
See http://karita.xyz/espnet/apis/espnet2_bin.html
> Support espnet2/bin in sphinx doc.

- egs/jsut/tts1/local/download.sh
- egs2/TEMPLATE/asr1/db.sh
- egs2/TEMPLATE/asr1/scripts/utils/download_from_google_drive.sh
- egs2/jsss/tts1/README.md
- egs2/jsss/tts1/cmd.sh
- egs2/jsss/tts1/conf/decode.yaml
- egs2/jsss/tts1/conf/pbs.conf
- egs2/jsss/tts1/conf/queue.conf
- egs2/jsss/tts1/conf/slurm.conf
- egs2/jsss/tts1/conf/train.yaml
- egs2/jsss/tts1/conf/tuning/decode_fastspeech.yaml
- egs2/jsss/tts1/conf/tuning/decode_tacotron2.yaml
- egs2/jsss/tts1/conf/tuning/train_conformer_fastspeech.yaml
- egs2/jsss/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/jsss/tts1/conf/tuning/train_fastspeech.yaml
- egs2/jsss/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/jsss/tts1/conf/tuning/train_tacotron2.yaml
- egs2/jsss/tts1/conf/tuning/train_transformer.yaml
- egs2/jsss/tts1/db.sh
- egs2/jsss/tts1/local/data.sh
- egs2/jsss/tts1/local/data_download.sh
- egs2/jsss/tts1/local/data_prep.sh
- egs2/jsss/tts1/path.sh
- egs2/jsss/tts1/pyscripts
- egs2/jsss/tts1/run.sh
- egs2/jsss/tts1/scripts
- egs2/jsss/tts1/steps
- egs2/jsss/tts1/tts.sh
- egs2/jsss/tts1/utils
- egs2/jsut/asr1/local/data_prep.sh
This PR add a new TTS recipe using JSSS corpus.
https://sites.google.com/site/shinnosuketakamichi/research-topics/jsss_corpus
> Add JSSS recipe for ESPnet2-TTS

- egs2/aishell/asr1/README.md
- egs2/aishell/asr1/conf/train_asr_conformer.yaml
- egs2/aishell/asr1/conf/train_lm_transformer.yaml
- egs2/aishell/asr1/conf/tuning/train_asr_conformer.yaml
- egs2/aishell/asr1/conf/tuning/train_asr_transformer2.yaml
- egs2/aishell/asr1/conf/tuning/train_asr_transformer3.yaml
- egs2/aishell/asr1/conf/tuning/train_lm_rnn.yaml
- egs2/aishell/asr1/conf/tuning/train_lm_rnn2.yaml
- egs2/aishell/asr1/conf/tuning/train_lm_transformer.yaml
- egs2/aishell/asr1/run.sh
- Got better result than espnet1 using conformer model.
- Pitch feats seems to have no effects for this task.
> Update espnet2 AISHELL results

- egs2/aishell/asr1/README.md
- egs2/aishell/asr1/conf/tuning/train_asr_conformer.yaml
- egs2/aishell/asr1/conf/tuning/train_asr_transformer3.yaml
Remove num_workers from configuration file.
> Small changes for aishell config

- egs/tedlium2/asr1/RESULTS.md
- egs/tedlium2/asr1/conf/train.yaml
- egs/tedlium2/asr1/conf/tuning/decode_pytorch_transformer.yaml
- egs/tedlium2/asr1/conf/tuning/train_pytorch_conformer_large_kernel15_lr2.0.yaml
- date: `Tue Oct 27 10:53:56 CST 2020`
- python version: `3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42)  [GCC 7.2.0]`
- espnet version: `espnet 0.9.3`
- chainer version: `chainer 6.0.0`
- pytorch version: `pytorch 1.6.0`
|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_decode_pytorch_transformer|507|34191|94.3|3.0|2.7|1.0|6.7|71.8|
|decode_test_decode_pytorch_transformer|1155|51224|95.0|2.3|2.7|0.7|5.7|62.7|
|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_decode_pytorch_transformer|507|17783|92.8|4.5|2.8|1.4|8.6|71.8|
|decode_test_decode_pytorch_transformer|1155|27500|93.6|3.5|2.9|0.8|7.2|62.6|
> Update tedlium2 with conformer results

- egs/voxforge/asr1/RESULTS.md
- egs/voxforge/asr1/conf/train.yaml
- egs/voxforge/asr1/conf/tuning/train_pytorch_conformer.yaml
Added config files and uploaded a pre-trained model for Conformer.
> Update Voxforge with Conformer results

- egs2/TEMPLATE/tts1/README.md
> Update TTS README.md 

- espnet/nets/pytorch_backend/rnn/encoders.py
- espnet/nets/pytorch_backend/tacotron2/cbhg.py
- espnet/nets/pytorch_backend/tacotron2/encoder.py
> bug fix for  pytorch1.7

- egs/commonvoice/asr1/run.sh
The run.sh script was broken because data_url, nbpe and datadir was being set before running utils/parse_options.sh
> lang was being used before being parsed for user input

- egs2/TEMPLATE/tts1/README.md
- egs2/jvs/tts1/README.md
> Update README about fine-tuning

- espnet2/asr/ctc.py
- How to use
`--ctc_conf ignore_nan_grad=True`
Ignore samples causing nan gradients.  If all samples have nan grads, nothing to do. i.e. stop updating for the step.
This feature is false by default.
If you see "WARNING: The grad norm is nan. Skipping updating the model.", it might be worth to try this option.
> Add ignore_nan_grad option for CTC

- espnet2/tasks/tts.py
- espnet2/tts/feats_extract/dio.py
- espnet2/tts/feats_extract/energy.py
- test/espnet2/tts/feats_extract/test_dio.py
- test/espnet2/tts/feats_extract/test_energy.py
> Fix token averaged feature the case when r > 1

- ci/install.sh
- espnet2/asr/espnet_model.py
- espnet2/asr/frontend/default.py
- espnet2/bin/aggregate_stats_dirs.py
- espnet2/bin/asr_inference.py
- espnet2/bin/enh_inference.py
- espnet2/layers/stft.py
- espnet2/main_funcs/average_nbest_models.py
- espnet2/samplers/build_batch_sampler.py
- espnet2/samplers/folded_batch_sampler.py
- espnet2/samplers/unsorted_batch_sampler.py
- espnet2/tasks/abs_task.py
- espnet2/train/iterable_dataset.py
- espnet2/train/trainer.py
This is the prior PR for the PR #2649.
> Touching common modules before the main Enh PR

- espnet2/tasks/abs_task.py
- espnet2/train/reporter.py
> Update wandb part

- egs2/aishell/asr1/README.md
> Add AISHELL w/o LM result

- egs2/TEMPLATE/asr1/asr.sh
Add the following new options in `asr.sh`:
- `--asr_stats_dir`
- `--lm_stats_dir`
> Add *_stats_dir options in asr.sh

- egs/ru_open_stt/asr1/RESULTS.md
- egs/ru_open_stt/asr1/conf/decode.yaml
- egs/ru_open_stt/asr1/conf/lm_transformer_large.yaml
- egs/ru_open_stt/asr1/conf/train.yaml
- egs/ru_open_stt/asr1/conf/tuning/decode_pytorch_transformer_large.yaml
- egs/ru_open_stt/asr1/conf/tuning/train_pytorch_conformer_large.yaml
- egs/ru_open_stt/asr1/local/ru_open_stt_download_data.sh
- egs/ru_open_stt/asr1/local/ru_open_stt_prepare_data.py
- egs/ru_open_stt/asr1/run.sh
Current amount of training data is about 4700 hours.
> Update Russian open STT recipe for v1.01 of the dataset

- egs2/csmsc/tts1/README.md
The link address of open-source CSMSC corpus has been changed.
> update latest CSMSC link address

- egs2/voxforge/asr1/README.md
- egs2/voxforge/asr1/README_LightweightSincConvs.md
> README_LightweightSincConvs.md

- egs2/TEMPLATE/tts1/README.md
- egs2/TEMPLATE/tts1/conf/mfcc.conf
- egs2/TEMPLATE/tts1/conf/vad.conf
- egs2/TEMPLATE/tts1/setup.sh
- egs2/TEMPLATE/tts1/sid
- egs2/TEMPLATE/tts1/tts.sh
- egs2/vctk/tts1/conf/mfcc.conf
- egs2/vctk/tts1/conf/vad.conf
- egs2/vctk/tts1/sid
- espnet2/bin/tts_inference.py
This PR is the subset of #2796 
- Support X-vector extraction in the template
- Add files for the X-vector extraction
- Update README about X-vector extraction
> Support X-vector based multi-speaker TTS model in ESPnet2

- egs2/jsut/tts1/README.md
- Add FS2 results with the transformer teacher
> Update JSUT results 

- egs2/csmsc/tts1/conf/tuning/train_conformer_fastspeech.yaml
- egs2/csmsc/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/csmsc/tts1/conf/tuning/train_fastspeech.yaml
- egs2/csmsc/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/jsss/tts1/conf/tuning/train_conformer_fastspeech.yaml
- egs2/jsss/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/jsss/tts1/conf/tuning/train_fastspeech.yaml
- egs2/jsss/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/jsut/tts1/conf/tuning/train_conformer_fastspeech.yaml
- egs2/jsut/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/jsut/tts1/conf/tuning/train_fastspeech.yaml
- egs2/jsut/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/ljspeech/tts1/conf/tuning/train_conformer_fastspeech.yaml
- egs2/ljspeech/tts1/conf/tuning/train_conformer_fastspeech2.yaml
- egs2/ljspeech/tts1/conf/tuning/train_fastspeech.yaml
- egs2/ljspeech/tts1/conf/tuning/train_fastspeech2.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_conformer_fastspeech2.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_fastspeech.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_fastspeech2.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_tacotron2.yaml
- egs2/vctk/tts1/conf/tuning/train_gst_transformer.yaml
- single speaker model -> 100k iters as a default
- multi speaker model -> 150k iters as a default
> Fix total number of iterations

- espnet/nets/beam_search_transducer.py
- espnet/nets/e2e_asr_common.py
- test/test_e2e_asr_sa_transducer.py
Fix bug when using greedy search during inference. Close #2805
> fix greedy decoding

- egs2/TEMPLATE/tts1/tts.sh
- egs2/vctk/tts1/README.md
- egs2/vctk/tts1/conf/tuning/train_gst+xvector_conformer_fastspeech2.yaml
- egs2/vctk/tts1/conf/tuning/train_gst+xvector_tacotron2.yaml
- egs2/vctk/tts1/conf/tuning/train_gst+xvector_transformer.yaml
- egs2/vctk/tts1/conf/tuning/train_xvector_conformer_fastspeech2.yaml
- egs2/vctk/tts1/conf/tuning/train_xvector_tacotron2.yaml
- egs2/vctk/tts1/conf/tuning/train_xvector_transformer.yaml
This PR adds configs for VCTK:
- X-vector + Taco2
- X-vector + GST + Taco2
- X-vector + Transformer
- X-vector + GST + Transformer
- X-vector + Conformer-FastSpeech2
- X-vector + GST + Conformer-FastSpeech2
I will also update the results once the training is finished.
> Add x-vector based configs for VCTK

- espnet/bin/asr_train.py
- espnet/bin/lm_train.py
- espnet/bin/mt_train.py
- espnet/bin/st_train.py
- espnet/bin/tts_train.py
- espnet/bin/vc_train.py
- espnet2/tasks/abs_task.py
This PR add version information in args.
This helps to change the behavior when adding the incompatible changes in the next version.
> Add version info in args

- egs/ljspeech/asr1/run.sh
> fix egs/ljspeech/asr1 #2865

- egs/must_c/asr1/run.sh
- egs/must_c/mt1/run.sh
- egs/must_c/st1/local/data_prep.sh
- egs/must_c/st1/run.sh
- Added the original dev set (not trimmed) to automatic evaluation in stage-5 + some refactoring.
- Enabled GPU decoding in stage-5.
> Refactor Must-C recipe

- egs/libri_trans/asr1/run.sh
- egs/libri_trans/mt1/run.sh
- egs/libri_trans/st1/run.sh
The same refactoring as #2901 for libri-trans recipe.
> Refactor libri-trans recipe

- egs/fisher_callhome_spanish/asr1b/run.sh
- egs/fisher_callhome_spanish/mt1/run.sh
- egs/fisher_callhome_spanish/st1/run.sh
The same refactoring as #2901 for Fisher-CallHome recipe.
> Refactor Fisher-CallHome recipe

- egs/mboshi_french/st1/RESULTS.md
- egs/mboshi_french/st1/conf/specaug.yaml
- egs/mboshi_french/st1/conf/train.yaml
- egs/mboshi_french/st1/conf/tuning/train_pytorch_conformer_kernel15_half.yaml
- egs/mboshi_french/st1/local/data_prep.sh
- egs/mboshi_french/st1/run.sh
Same refactoring as #2901 + add Conformer results.
Conformer is effective for very low-resource ST task.
> Refactor Mboshi-French corpus

- egs2/librispeech/asr1/conf/tuning/train_asr_transformer3_w2v_large_lv60_960h_finetuning_last_1layer.yaml
- espnet2/asr/encoder/extract_features.py
- espnet2/asr/encoder/wav2vec2_encoder.py
- espnet2/tasks/asr.py
- espnet2/torch_utils/initialize.py
- tools/Makefile
- tools/check_install.py
- tools/installers/install_fairseq.sh
This is the initial PR for importing the Wav2Vec2.0 model in ESPnet.
Before the code review, there is an issue that FairSeq is now made as an optional package, however, I cannot pass the test. The error message is related to failure for "import fairseq". Can anyone give some suggestions?
> add wav2vec_encoder

- egs/commonvoice/asr1/RESULTS.md
Update the transformer training results of German in part of the `Common Voice` dataset, which has been discussed in #2897
> Update transformer training results on common vioce dataset

- egs/how2/asr1/run.sh
- egs/how2/st1/local/data_prep_test.sh
- egs/how2/st1/run.sh
In stage-1, `utt2num_frames` was missed.
> Fix bug in How2 recipe

- egs/mini_an4/st1/run.sh
- egs/must_c/st1/run.sh
- espnet/nets/pytorch_backend/e2e_st.py
- utils/calculate_rtf.py
Added RTF calculation, mainly for methods which requires latency constraint such as non-autoregressive models.
> RTF calculation

- egs2/open_li52/asr1/README.md
- egs2/open_li52/asr1/conf/train_asr.yaml
- egs2/open_li52/asr1/conf/tuning/train_asr_transformer_bpe7000.yaml
- egs2/open_li52/asr1/conf/tuning/train_asr_transformer_bpe8000.yaml
- egs2/open_li52/asr1/local/data.sh
- egs2/open_li52/asr1/run.sh
- added RESULTS.md with uploaded models
- minor bug fix
> update the results of open li52 recipe

- espnet/nets/beam_search_transducer.py
- espnet/nets/transducer_decoder_interface.py
Follow-up of #2971. Closes #2970.
It can be merged after @siddalmia gives the go-ahead!
> Fix docker error caused by BeamSearchTransducer

- utils/recog_wav.sh
This is a simple change which will resample the audio to the default settings of ESPnet models.
> Auto Resampling to 16khz for pretrained models

- espnet/nets/pytorch_backend/e2e_tts_transformer.py
#2883 changed the arguments but Transformer-TTS's plotfn was not modifed.
This causes the error in #2984.
This PR fixes this issue
> Fix attention plot bug #2984

- espnet/nets/batch_beam_search_online_sim.py
- test/espnet2/asr/decoder/test_transformer_decoder.py
I found an error in decoding using entire encoded features instead of blocks.
Also, I modified configuration part for the decoder to be more versatile.
Added test for the configuration accordingly.
> bug fixed for streaming transformer ASR

- egs/iwslt21/asr1/run.sh
Added Must-C v2 and some minor fixes.
> Update IWSLT21 ASR recipe

- doc/espnet2_distributed.md
- espnet2/tasks/abs_task.py
- espnet2/train/trainer.py
- Fix to perform  sharded training with amp
- I also changed sharded_ddp to ddp_shared following pytorch-lightning
> Fix for sharded training with amp

- egs/iwslt21/asr1/run.sh
Use `dev` instead of `dev_org`.
> Fix dev set in IWSLT21 ASR recipe

- espnet2/asr/encoder/wav2vec2_encoder.py
1. Bug fix: using deepcopy() to copy the parameters of pretrained wav2vec encoder
2. Adding new freeze_finetune_updates parameter not to update the wav2vec encoder for a few iterations
> bug fix for Wav2Vec encoder

- egs/fisher_callhome_spanish/st1/conf/tuning/train_pytorch_conformer_kernel15_bpe_ctc_asr0.3.yaml
- egs/fisher_callhome_spanish/st1/conf/tuning/train_pytorch_conformer_kernel15_bpe_short.yaml
- espnet/nets/pytorch_backend/conformer/argument.py
- espnet/nets/pytorch_backend/e2e_asr_conformer.py
- espnet/nets/pytorch_backend/e2e_st_conformer.py
Add the latest RPE implementation to the ST task.
> Add the latest RPE implementation to the ST task.

- egs/mini_an4/asr_mix1/run.sh
- espnet/bin/asr_train.py
@simpleoier has reviewed this bug fix.
> Integration testing for asr_mix was using the wrong config.

- egs/fisher_callhome_spanish/st1/local/normalize_trans.sh
- egs/how2/st1/local/data_prep.sh
- egs/how2/st1/local/data_prep_test.sh
- egs/iwslt18/st1/local/data_prep_eval.sh
- egs/iwslt18/st1/local/data_prep_train.sh
- egs/libri_trans/st1/local/data_prep.sh
- egs/must_c/st1/local/data_prep.sh
> Fix local/remove_punctuation.pl -> remove_punctuation.pl

- espnet2/train/trainer.py
> Fix sharded_ddp mode

- doc/installation.md
Fix a typo in the installation document.
> fix a typo

- espnet/nets/pytorch_backend/lm/default.py
- espnet/nets/pytorch_backend/lm/transformer.py
- test/test_lm.py
These options are useful for better LM models.
> Add LM options like embedding dropout and tie weights

- espnet/nets/beam_search_transducer.py
Fix a typo and a mistake introduced in a previous refactor. It won't change performance/speed though.
> Minor fix for NSC

- espnet2/train/trainer.py
> fix a bug in #3014

- espnet/nets/pytorch_backend/transducer/custom_encoder.py
Fix `n_block` definition for custom encoder and add `normalize_before` option for intermediate layers representation.
> Fix related to custom encoder and aux task 

- espnet/nets/pytorch_backend/transducer/rnn_encoder.py
Only apply to RNN class (RNNP is not impacted):
- Fix case when eprojs != eunits
- Add projection for output layer
- Add projection for auxiliary output layers
> Fix+update RNN encoder

- egs/puebla_nahuatl/asr1/local/download_and_untar.sh
1. add `-N` for download and untar to skip downloading
2. fix bug for concat multiple parts
> Bugfix for download_and_untar for nahuatl

- egs/puebla_nahuatl/st1/run.sh
I think the remixed data was not being generated causing an error.
@ftshijt could you review this?
> Remix Script needs to be run

- espnet/nets/pytorch_backend/transformer/decoder.py
- espnet/nets/pytorch_backend/transformer/encoder.py
Follow Conformer's layer definition.
> Refactor layer selection in Transformer

- setup.py
> Fix setup.py to install filelock

- egs/aishell/asr1/conf/tuning/train_pytorch_conformer_kernel15.yaml
Thanks, Tatsuya Komatsu for pointing out the issue!
> Fix a typo in the aishell config

- tools/installers/install_pyopenjtalk.sh
For quick fixing, specify the commit id.
> quick fix for pyopenjtalk installation

- espnet2/samplers/length_batch_sampler.py
- espnet2/samplers/num_elements_batch_sampler.py
I made length_batch_sampler.py  and  num_elements_batch_sampler.py  faster. This refactoring shouldn't change the output samples.
#3104
> Make batch bins sampler faster

- egs/csmsc/tts1/local/data_download.sh
- egs2/csmsc/tts1/local/data.sh
Now CSMSC is not free.
I modified download script to show how-to-locate the corpus.
Related: #3075
> Fix CSMSC download script

- espnet2/tts/fastspeech.py
- espnet2/tts/fastspeech2.py
Follow https://github.com/espnet/espnet/pull/3068
> Fix ESPnet2-TTS conformer backward compatibility

- espnet/asr/pytorch_backend/asr.py
- espnet/nets/pytorch_backend/e2e_asr_transducer.py
- espnet/nets/pytorch_backend/transducer/auxiliary_task.py
- Update loss report for transducer models and include all auxiliaries losses
- Fix `mtl_mode` with custom transducer model (forgot to update when I replaced `transformer|conformer` type to `custom`)
For transducer model reporting in `asr.py`, I went for a straightforward solution (I didn't have too much time to think about it), if anyone have a proper solution feel free to ask for modifications!
> Update loss report

- egs2/jvs/tts1/README.md
> fixed typo #3121

- egs/iwslt21/asr1/run.sh
Added tokenization with moses for TEDLIUM2 in `stage-0`.
> Fix tokenization on TEDLIUM2 in IWSLT21 ASR recipe

- espnet2/train/trainer.py
> remove find_unused_parameters from DataParallel

- egs/iwslt18/st1/local/score_bleu_reseg.sh
- egs/iwslt18/st1/local/score_sclite_reseg.sh
- egs/iwslt21/asr1/local/data2json.sh
- egs/iwslt21/asr1/local/json2trn_reorder.py
- egs/iwslt21/asr1/local/score_bleu_reseg.sh
- egs/iwslt21/asr1/local/score_sclite_reseg.sh
- egs/iwslt21/asr1/run.sh
- egs/iwslt21/st1/run.sh
Supported evaluation of `dev2010` and `tst2010`-`tst2019`.
> Fix IWSLT21 recipe for test set evaluation

- egs2/wsj/asr1/README.md
fix: conf/decode.conf to conf/decode.yaml
> Update README.md, edit wrong file link.

- egs/iwslt18/st1/local/data_prep_eval.sh
- egs/iwslt18/st1/local/data_prep_train.sh
Fix bugs regarding yaml files.
> Fix ST-TED data preparation

- egs/iwslt18/st1/local/data_prep_eval.sh
- egs/iwslt18/st1/local/json2trn_reorder.py
Fix `data_prep_eval.sh` for new test sets.
> Fix IWSLT evaluation data preparation

- egs/iwslt21/asr1/local/data_prep_eval_iwslt.sh
- egs/iwslt21/asr1/local/parse_xml.py
- egs/iwslt21/asr1/local/wrap-xml.perl
- egs/iwslt21/asr1/path.sh
- egs/iwslt21/asr1/run.sh
- egs/iwslt21/st1/path.sh
- egs/iwslt21/st1/run.sh
> Fix segmentation in IWSLT21 ASR

- egs/iwslt21/asr1/local/merge_short_segments.py
Fixed a bug for speaker id (follow-up of #3168).
> Fix merge_short_segments.py

- espnet/transform/channel_selector.py
- espnet2/diar/decoder/linear_decoder.py
- espnet2/diar/label_processor.py
- espnet2/enh/decoder/conv_decoder.py
- espnet2/enh/decoder/stft_decoder.py
- espnet2/enh/encoder/conv_encoder.py
- espnet2/enh/encoder/null_encoder.py
- espnet2/enh/encoder/stft_encoder.py
- espnet2/enh/separator/asteroid_models.py
Black complains because of trailing white spaces at the end of strings. I don't know why, maybe because of a new version of black? 
This PR fixes these errors. @sw005320 @kamo-naoyuki
> Fix black errors

- espnet/nets/pytorch_backend/transformer/layer_norm.py
> update layer norm to reflect the dimension variable

- README.md
Add ASR demonstration with ESPNet2 (correspond to https://github.com/espnet/notebook/blob/master/espnet2_asr_realtime_demo.ipynb )
> update asr demo

- .mergify.yml
> Fix  .mergify.yml

- egs2/open_li52/asr1/local/data.sh
- Fix a minor bug of using extglob for string compare
- Remove punctuation for open_li52 text
> Normalization for Open_li52

- README.md
I also put the colab notebook to the [notebook repo](https://github.com/espnet/notebook/pull/19).
Maybe we can update the colab link later.
Add `__init__.py` for  SE related packages.
> Update the readme file for the SE demo page.

- espnet2/text/char_tokenizer.py
- espnet2/text/phoneme_tokenizer.py
- espnet2/text/word_tokenizer.py
> Workaround for missing nlsyms.txt

- egs2/TEMPLATE/asr1/asr.sh
- espnet2/text/char_tokenizer.py
- espnet2/text/phoneme_tokenizer.py
- espnet2/text/word_tokenizer.py
Fix a bug in #3232
We need to reupload WSJ and related models.
> Changed to include nlsyms.txt in the pretrained model

- egs/mgb2/asr1/local/mgb_data_prep.sh
I see that the required number of arguments are 4 instead of 3
> fix the required number of arguments

- espnet2/tts/transformer.py
pointed out by @Hiroshiba in #3250
> Fix a bug in the TTS transformer initialization

- espnet2/tasks/abs_task.py
> Add a comment for disabling the attention plot

- espnet/bin/asr_recog.py
> Add quantize args

- espnet2/asr/specaug/specaug.py
- espnet2/enh/espnet_model.py
- espnet2/enh/layers/beamformer.py
- espnet2/enh/layers/dnn_beamformer.py
- espnet2/layers/time_warp.py
- espnet2/schedulers/abs_scheduler.py
- espnet2/schedulers/noam_lr.py
- espnet2/schedulers/warmup_lr.py
- espnet2/tasks/abs_task.py
- espnet2/torch_utils/recursive_op.py
- espnet2/train/iterable_dataset.py
- espnet2/train/reporter.py
- espnet2/train/trainer.py
- test/espnet2/bin/test_enh_inference.py
- test/espnet2/enh/decoder/test_stft_decoder.py
- test/espnet2/enh/encoder/test_stft_encoder.py
- test/espnet2/enh/separator/test_beamformer.py
- test/espnet2/layers/test_stft.py
- test/espnet2/schedulers/test_noam_lr.py
- test/espnet2/schedulers/test_warmup_lr.py
- test/espnet2/train/test_iterable_dataset.py
- test/espnet2/train/test_reporter.py
> Delete codes for old pytorch in espnet2.

- egs2/swbd/asr1/local/score.sh
this should fix path error when scoring ctm
> fix path error in local/score.sh in swbd

- espnet/nets/pytorch_backend/e2e_tts_tacotron2.py
- espnet/nets/pytorch_backend/e2e_tts_transformer.py
- espnet/nets/pytorch_backend/e2e_vc_tacotron2.py
- espnet/nets/pytorch_backend/e2e_vc_transformer.py
- espnet2/tts/tacotron2.py
- espnet2/tts/transformer.py
- test/espnet2/tts/test_tacotron2.py
- test/espnet2/tts/test_transformer.py
> Fixed label modification in Taco2 or Transformer-TTS with R > 1

- egs2/TEMPLATE/asr1/asr.sh
- espnet2/bin/k2_asr_inference.py
- test/espnet2/bin/test_k2_asr_inference.py
As discussed in https://github.com/espnet/espnet/pull/3358, this pr is about batch decoding part in following whole plan:
0. encoder + ctc decocer （#3358）
1.  support batch decoding (**_current pr_**)
2.  support ctc_topo + 3-gram decoding, which will be referred as TLG decoding and T is short for "Token".
3.  4-gram lattice rescore 
4.  ransformer-decoder nbest rescore
5.  neural net language model nbest rescore
> [WIP] batch decode with k2 ctc

- espnet2/tasks/tts.py
- espnet2/tts/feats_extract/linear_spectrogram.py
- espnet2/tts/feats_extract/log_mel_fbank.py
- test/espnet2/tts/feats_extract/test_linear_spectrogram.py
Subset of #3423 
Support linear spectrogram as acoustic frontend.
And this PR adds the support of log_base change in fbank.
> Support linear spectrogram

- README.md
- setup.py
> Added a link and a classifier for Python 3.9

- espnet2/asr/encoder/conformer_encoder.py
- espnet2/bin/asr_align.py
- espnet2/bin/asr_inference.py
- espnet2/bin/diar_inference.py
- espnet2/bin/enh_inference.py
- espnet2/bin/launch.py
- espnet2/enh/espnet_model.py
- espnet2/enh/layers/beamformer.py
- espnet2/enh/separator/asteroid_models.py
- espnet2/enh/separator/conformer_separator.py
- espnet2/enh/separator/transformer_separator.py
- espnet2/iterators/chunk_iter_factory.py
- espnet2/layers/mask_along_axis.py
- espnet2/samplers/build_batch_sampler.py
- espnet2/tasks/diar.py
- espnet2/train/dataset.py
- espnet2/tts/feats_extract/dio.py
- espnet2/tts/gst/style_encoder.py
- espnet2/tts/transformer.py
Detected typos by using [typos](https://github.com/crate-ci/typos) and fixed them with manual check
> Fix typos in "espnet2"

- egs2/TEMPLATE/asr1/pyscripts/utils/utt2spk_to_utt2sid.py
- egs2/TEMPLATE/tts1/tts.sh
- espnet2/bin/tts_inference.py
- espnet2/tasks/tts.py
- espnet2/tts/espnet_model.py
This PR add the support of the `sids` inputs for ESPnet2-TTS models.
> Support speaker id input for TTS models

- egs2/TEMPLATE/tts1/tts.sh
> Follow up of the support speaker id input

- egs2/TEMPLATE/diar1/diar.sh
- egs2/mini_librispeech/diar1/local/data.sh
This PR is for fixing the following minor bugs.
1. Stage numbers in egs2/TEMPLATE/diar1/diar.sh
2. Directory paths in egs2/mini_librispeech/diar1/local/data.sh
> Fix minor bugs in ESPnet2 diarization recipe

- egs2/TEMPLATE/tts1/tts.sh
- espnet2/tasks/tts.py
- espnet2/tts/espnet_model.py
This PR supports the use language id in recipe level.
I did not touch the model part (I will do it in the next PR).
> Support language ID input for espnet2 TTS

- .github/workflows/centos7.yml
- .github/workflows/debian9.yml
- ci/install.sh
K2 version is not fixed when using conda in CI.
> Fix k2 version in CI using conda

- egs2/ljspeech/tts1/conf/tuning/decode_vits.yaml
- egs2/vctk/tts1/conf/tuning/decode_vits.yaml
- espnet2/bin/tts_inference.py
- espnet2/gan_tts/vits/generator.py
- espnet2/gan_tts/vits/vits.py
- test/espnet2/gan_tts/vits/test_generator.py
- test/espnet2/gan_tts/vits/test_vits.py
This PR enhances the tts inference
- Support the overwriting of any decoding params
- Support fixing of the seed
- Add VITS-related decoding options
- Support teacher forcing in VITS
> Update the TTS inference

- egs2/TEMPLATE/tts1/tts.sh
I wrongly removed lines. This PR reverts the change.
> Revert wrongly removed lines in `tts.sh`

- egs2/csmsc/tts1/conf/tuning/train_full_band_vits.yaml
- egs2/csmsc/tts1/conf/tuning/train_vits.yaml
- egs2/jsut/tts1/conf/tuning/train_full_band_vits.yaml
- egs2/jsut/tts1/conf/tuning/train_vits.yaml
- egs2/libritts/tts1/conf/tuning/train_xvector_vits.yaml
- egs2/ljspeech/tts1/conf/tuning/train_vits.yaml
- egs2/vctk/tts1/conf/tuning/train_multi_spk_vits.yaml
- espnet2/gan_tts/hifigan/hifigan.py
- espnet2/gan_tts/hifigan/residual_block.py
- espnet2/gan_tts/vits/generator.py
- espnet2/tts/fastspeech/fastspeech.py
- espnet2/tts/fastspeech2/fastspeech2.py
- espnet2/tts/gst/style_encoder.py
- espnet2/tts/tacotron2/tacotron2.py
- espnet2/tts/transformer/transformer.py
- test/espnet2/gan_tts/hifigan/test_hifigan.py
> Fix typo in hifigan

- egs2/aishell3/tts1/local/data.sh
- egs2/aishell3/tts1/local/download_and_untar.sh
1. data/train_phn/wav.scp.tmp may be typo
2. set data_aishell3.tgz file size
> aishell3 dataset preparation

- egs2/vctk_noisy/enh1/cmd.sh
- egs2/vctk_noisy/enh1/conf/pbs.conf
- egs2/vctk_noisy/enh1/conf/queue.conf
- egs2/vctk_noisy/enh1/conf/slurm.conf
- egs2/vctk_noisy/enh1/conf/train.yaml
- egs2/vctk_noisy/enh1/conf/tuning/train_enh_conv_tasnet.yaml
- egs2/vctk_noisy/enh1/db.sh
- egs2/vctk_noisy/enh1/enh.sh
- egs2/vctk_noisy/enh1/local/data.sh
- egs2/vctk_noisy/enh1/local/vctk_data_prep.sh
- egs2/vctk_noisy/enh1/path.sh
- egs2/vctk_noisy/enh1/pyscripts
- egs2/vctk_noisy/enh1/run.sh
- egs2/vctk_noisy/enh1/scripts
- egs2/vctk_noisy/enh1/steps
- egs2/vctk_noisy/enh1/utils
README.md will be on the next PR after the training is finished.
> Add Voicebank (vctk_noisy) script

- ci/test_integration.sh
- egs2/TEMPLATE/tts1/README.md
- egs2/TEMPLATE/tts1/tts.sh
- egs2/an4/tts1/conf/fbank.conf
- egs2/an4/tts1/conf/pitch.conf
- egs2/mini_an4/tts1/conf/fbank.conf
- egs2/mini_an4/tts1/conf/pitch.conf
- espnet2/bin/tts_inference.py
- espnet2/gan_tts/espnet_model.py
- espnet2/tasks/gan_tts.py
- espnet2/tasks/tts.py
- espnet2/tts/espnet_model.py
Should merge after #3513 
No one use this feats_types except for CI so I will remove them to simplify `tts.sh`.
> Remove the support of feats_type=fbank/stft in ESPnet2-TTS

- espnet2/gan_tts/joint/joint_text2wav.py
- espnet2/gan_tts/parallel_wavegan/__init__.py
- espnet2/gan_tts/parallel_wavegan/parallel_wavegan.py
- espnet2/gan_tts/parallel_wavegan/upsample.py
- test/espnet2/gan_tts/hifigan/test_hifigan.py
- test/espnet2/gan_tts/joint/test_joint_text2wav.py
- test/espnet2/gan_tts/parallel_wavegan/test_parallel_wavegan.py
This PR adds parallel wavegan for joint training.
> Add parallel wavegan module for joint training

- espnet2/bin/diar_inference.py
This PR is related to https://github.com/espnet/espnet/pull/3535.
This is to support `from_pretrain` also for DIAR.
> Support `from_pretrain` for DIAR

- egs2/TEMPLATE/diar1/diar.sh
- egs2/TEMPLATE/enh1/enh.sh
- egs2/TEMPLATE/enh1/scripts/utils/enhance_dataset.sh
- espnet2/bin/diar_inference.py
- espnet2/bin/enh_inference.py
- test/espnet2/bin/test_enh_inference.py
Follow up of #3537 #3535 
- Removed the prefix `enh_` and `diar_`
- Cleaned `diar.sh`
> Remove prefix `enh_` and `diar_`

- .gitignore
- tools/check_install.py
- tools/installers/install_pyopenjtalk.sh
- tools/installers/install_tdmelodic_pyopenjtalk.sh
This PR adds the installer of pyopenjtalk enhanced with tdmelodic_openjtalk.
https://github.com/sarulab-speech/tdmelodic_openjtalk
> Add the installer of tdmelodic pyopenjtalk

- egs2/TEMPLATE/asr1/pyscripts/utils/evaluate_mcd.py
- egs2/TEMPLATE/tts1/tts.sh
Support both dir and scp specification.
> Update `evaluate_mcd.py` script

- egs2/librispeech/asr1/README.md
update pretrained models of librispeech using self-supervised representations.
> update pretrained models of librispeech using hubert/wav2vec2

- egs2/TEMPLATE/asr1/scripts/audio/format_wav_scp.sh
The quota mark is not in the right place
> Minor bug in format_wav_scp.py

- egs2/TEMPLATE/asr1/scripts/utils/evaluate_asr.sh
- test_utils/test_evaluate_asr.bats
This PR adds a portable ASR script, which can be used for other tasks (e.g., tts).
> Add ASR portable evaluation script

- egs2/TEMPLATE/asr1/scripts/utils/evaluate_asr.sh
Changed tmp directory removal timing.
> Minor fix of `evaluate_asr.sh`

- tools/installers/install_pyopenjtalk.sh
- tools/installers/install_tdmelodic_pyopenjtalk.sh
> Update pyopenjtalk version

- egs2/TEMPLATE/tts1/tts.sh
Changed to create `srctexts` in stage 4.
> Change the timing of srctexts creation

- egs2/TEMPLATE/tts1/README.md
> Fix readme

- .github/workflows/test_import.yaml
- tools/Makefile
- tools/installers/install_chainer.sh
#3708
I createad a script to install chainer=6.0.0 with modified requirements: I removed typing and made the version requirement of protobuf relaxing.
> Add  installers/install_chainer.sh

- espnet/nets/beam_search_transducer.py
> fix rnn-t ALSD beam search index bug

- espnet/nets/pytorch_backend/transducer/blocks.py
> Add exception for conformer decoder

- .github/workflows/ci.yaml
- ci/test_import_all.py
- ci/test_integration_espnet2.sh
- egs2/TEMPLATE/asr1/asr.sh
- egs2/librispeech/asr1/README.md
- egs2/librispeech/asr1/conf/decode_asr_transformer_with_k2.yaml
- egs2/mini_an4/asr1/conf/decode_asr_transformer_with_k2.yaml
- espnet/nets/pytorch_backend/nets_utils.py
- espnet2/asr/decoder/transformer_decoder.py
- espnet2/asr/espnet_model.py
- espnet2/bin/asr_inference_k2.py
- espnet2/fst/lm_rescore.py
- espnet2/lm/espnet_model.py
- test/espnet2/bin/test_asr_inference_k2.py
- tools/installers/install_k2.sh
Performance on librispeech **_test_clean_** :
With batch_size=5, decoding duration is 665 seconds.
|method|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|espnet baseline 70d16d210cdce28e71b7892a0ec96eaaa6474d64 |2620 | 52576 | 98.1 | 1.7 | 0.2 | 0.3 | 2.1 | 26.2
|nbest_rescoring with k2|2620|52576|98.0|1.8|0.2|0.3|2.3|27.5|
> nbest rescoring with k2

- egs/librispeech/asr1/conf/tuning/train_pytorch_conformer_selfconditioned.yaml
- espnet/nets/pytorch_backend/conformer/encoder.py
- espnet/nets/pytorch_backend/e2e_asr_conformer.py
- espnet/nets/pytorch_backend/e2e_asr_transformer.py
- espnet/nets/pytorch_backend/transformer/argument.py
- espnet/nets/pytorch_backend/transformer/encoder.py
- test/test_e2e_asr_conformer.py
- test/test_e2e_asr_transformer.py
This implements self-conditioned CTC for Transformer and Conformer encoders.
https://arxiv.org/abs/2104.02724
> Implement self-conditioned CTC

- egs2/TEMPLATE/enh1/enh.sh
- egs2/TEMPLATE/enh1/scripts/utils/show_asr_result.sh
- egs2/TEMPLATE/enh1/scripts/utils/show_enh_score.sh
@Emrys365 
I modified enh.sh.
- I added a for-loop for scoring observation signal without enhancement.
- I modified the structure of the output directory for ASR evaluation to run `show_asr_result.sh`
> Scoring for observation signal for enhancement task

- README.md
- doc/tutorial.md
- espnet/nets/pytorch_backend/transducer/custom_decoder.py
- espnet/nets/pytorch_backend/transducer/rnn_decoder.py
Closes #3863 + minor fix/improve of Transducer-related doc.
> Fix cache for Transducer search strategies + doc

- CONTRIBUTING.md
- espnet2/asr/espnet_model.py
- tools/Makefile
I added an option for espnet developers in Makefile. To ensure that we use the same black and not use black from conda which is a different version.
> Black is included in conda which is a different version from pip

- CONTRIBUTING.md
- espnet2/asr/espnet_model.py
- tools/Makefile
> Revert "Black is included in conda which is a different version from pip"

- espnet/nets/pytorch_backend/transducer/utils.py
> Fix recombine_hyps

- egs2/speechcommands/asr1/README.md
- egs2/speechcommands/asr1/local/data.sh
- egs2/speechcommands/asr1/local/score.sh
- egs2/speechcommands/asr1/run.sh
This PR updates the SLU recipe: Google Speech Commands
- Fix issues when the data directory is not default (`download`)
- Update `run.sh` to call `local/score.sh` inside `asr.sh`
- Update README to include Zenodo model links
> Update Google Speechcommands (SLU recipe)

- egs2/an4/asr1/README.md
- egs2/an4/asr1/conf/decode_asr.yaml
- egs2/an4/asr1/conf/train_asr_transformer.yaml
- egs2/an4/asr1/run.sh
The transformer configuration of AN4 is updated in ESPnet2.
- Reduced `warmup_steps`
- Added speed perturbation
> Update an4 config

- egs2/TEMPLATE/st1/st.sh
- egs2/fisher_callhome_spanish/asr1/conf/decode_asr.yaml
- egs2/fisher_callhome_spanish/asr1/conf/train_asr.yaml
- egs2/fisher_callhome_spanish/st1/conf/decode_st.yaml
- egs2/fisher_callhome_spanish/st1/conf/train_st.yaml
- egs2/fisher_callhome_spanish/st1/local/data.sh
The conformer with the previous config has some unstable issues, thus I change the default baseline to transformer now.
> update transformer config as baseline (stable)

- test/espnet2/bin/test_diar_inference.py
- test/espnet2/bin/test_diar_train.py
- test/espnet2/diar/attractor/test_rnn_attractor.py
- test/espnet2/diar/decoder/test_linear_decoder.py
- test/espnet2/tasks/test_diar.py
This is a follow-up PR of https://github.com/espnet/espnet/pull/3900.
> Add test codes for diarization

- egs2/TEMPLATE/st1/st.sh
This PR serves for the scoring bugfix.
Current results could reach similar performances to egs1 on transformer with pre-trained ASR.
I will finish this PR after adding support for multiple references setting
> Bugfix for ST scoring

- espnet2/asr/espnet_model.py
- espnet2/train/reporter.py
- espnet2/train/trainer.py
- test/espnet2/train/test_reporter.py
cleaned the tensorboard logging for espnet2 and also logged stats only for the branches that are active.
> cleaned tensorboard and stats logging for espnet2

- setup.py
https://pypi.org/project/pypinyin/#history
New Pypinyin version is released but it seems no compatible.
I temporary fixed the version.
> temporary fixed pypinyin version

- egs2/mls/asr1/steps
- egs2/mls/asr1/utils
@ftshijt the links were pointing to your kaldi and not a relative link :). Fixed it.
> Minor bug fix - MLS steps and utils links were broken

- tools/installers/install_pyopenjtalk.sh
- tools/installers/install_tdmelodic_pyopenjtalk.sh
Fix the issue
- https://github.com/r9y9/pyopenjtalk/issues/27
- https://github.com/espnet/espnet/discussions/4001
> Update pyopenjtalk from v0.1.5 to v0.1.6

- egs2/TEMPLATE/asr1/asr.sh
Train the ngram model using the whole utterance instead of just the first token.
> Bugfix for espnet2 ngram

- egs2/jvs/tts1/README.md
- egs2/tsukuyomi/tts1/README.md
> Fix typo in README.md

- .github/workflows/ci.yaml
Will fix the main README.md later
> remove the support of pytorch 1.3.1

- test/espnet2/gan_tts/hifigan/test_hifigan.py
- test/espnet2/gan_tts/melgan/test_melgan.py
- test/espnet2/gan_tts/parallel_wavegan/test_parallel_wavegan.py
- test/espnet2/gan_tts/style_melgan/test_style_melgan.py
> Simplify vocoder compatibility test

- .gitignore
- egs2/fisher_callhome_spanish/st1/local/mapping
@ftshijt based on our discussion. a more permanent fix :)
> avoid adding mapping file for fisher callhome

- test/espnet2/asr/transducer/test_beam_search_transducer.py
- test/espnet2/gan_tts/hifigan/test_hifigan.py
- test/espnet2/gan_tts/melgan/test_melgan.py
- test/espnet2/gan_tts/parallel_wavegan/test_parallel_wavegan.py
- test/espnet2/gan_tts/style_melgan/test_style_melgan.py
Fix the problems of #4059 and #4052
> Make the test smaller and the execution time longer

- egs2/librispeech/asr1/conf/tuning/train_asr_conformer7_hubert_ll60k_large.yaml
- egs2/librispeech/asr1/conf/tuning/train_asr_conformer7_wav2vec2_960hr_large.yaml
- egs2/librispeech/asr1/conf/tuning/train_asr_conformer7_wavlm_large.yaml
> fix errors in configs of librispeech ssl frontends

- espnet2/st/espnet_model.py
The lines https://github.com/espnet/espnet/blob/master/espnet2/st/espnet_model.py#L429-L433 had a minor bug from https://github.com/espnet/espnet/pull/3987
@ftshijt please confirm and merge.
> Bug fix ST model

- egs2/how2_2000h/asr1/README.md
- egs2/how2_2000h/sum1/README.md
Minor update in README for How2 ASR and SUM based on #4150 #4071
> Update README.md for How2 2000h ASR,SUM

- espnet2/bin/asr_inference.py
https://github.com/espnet/espnet/issues/4105
> Fix n-gram decoding

- egs2/wsj/asr1/README.md
- egs2/wsj/asr1/conf/tuning/train_asr_transformer_ctc.yaml
This is a follow-up PR of #4158. I've updated the training configuration and added results in README.
> Add Mask-CTC results

- README.md
Current SUM task is in the middle of description for ASR
> Change the order of  README

- espnet2/layers/utterance_mvn.py
This PR fix the bug mentioned in https://github.com/espnet/espnet/issues/4296.
> Fix a bug in utterance_mvn

- espnet2/bin/st_inference.py
> fix the enh_s2t_task argument in espnet2/bin/st_inference.py

- egs2/TEMPLATE/asr1/pyscripts/utils/convert_text_to_phn.py
I have added a simple progress bar displaying how much time is remaining of a batch phonemization job.
> Add progress bar to phonemization

- espnet2/gan_tts/vits/vits.py
> fix loss = NaN in VITS with mixed precision

- espnet2/bin/asr_inference_streaming.py
- test/espnet2/bin/test_asr_inference.py
Added edge test case for streaming asr unit test and increased execution time out.
This PR also includes the content of PR https://github.com/espnet/espnet/pull/4216.
> Add unit test to streaming ASR inference

- tools/Makefile
The problem of libsndfile has been resolved, so I removed the restriction for libsndfile version.
> Remove the restriction for libsndfile version

- egs2/kss/tts1/README.md
- egs2/ljspeech/tts1/README.md
Hi, I pre-trained jets recently and updated the recipe README following #4364 
Thanks :)
> add pre-trained model jets in the recipe of ljspeech, kss

- egs2/TEMPLATE/tts1/tts.sh
This implements my suggested fix for issue #4401
> Fix for issue #4401

- setup.py
Fix https://github.com/espnet/espnet/runs/6646737793?check_suite_focus=true#step:8:7651
> Temporary fix protobuf version

- egs/an4/asr1/run.sh
- egs/an4/tts1/run.sh
- egs2/an4/asr1/local/data.sh
Hi, this PR adds a backup URL for AN4.
If the original website doesn't respond, the following URL should work:
```bash
wget https://huggingface.co/datasets/espnet/an4/resolve/main/an4_sphere.tar.gz
```
> Fix an4 URL

- .github/workflows/test_import.yaml
To check the case #4465, I modified test_import.yml
> Canged to install espnet from wheel in the test_import CI test

- espnet2/tasks/abs_task.py
- espnet2/train/trainer.py
This PR optionizes the graph creation in tensorboard.
The graph in tensorboard is informative but it requires extra gpu memory and show a lot of tracerwarning (See #4543).
Therefore, it should be optionized and be False as a default.
> Optionize graph creation

- doc/espnet2_tutorial.md
- test_utils/asr_inference.1.log
- test_utils/test_calculate_rtf_py.bats
Added test script and usage for calculate_rtf.py script to ESPnet2 tutorial page 
Original PR: https://github.com/espnet/espnet/pull/4382
> Added test script and usage for calculate_rtf.py script to ESPnet2 tutorial page 

- .github/workflows/ci.yaml
- .github/workflows/test_import.yaml
- espnet/nets/pytorch_backend/transformer/plot.py
- setup.py
I don't know why the matplotlib version is fixed. I opened this PR to check CI tests.
> Unfix matplotlib version

- README.md
We will wait for the videos and materials ready for the 2022 tutorial.
Please let me know if it is on the boat @pyf98
> Documentation of Tutorial and Muskits

- espnet2/asr_transducer/encoder/blocks/conformer.py
- espnet2/asr_transducer/encoder/modules/convolution.py
- espnet2/asr_transducer/espnet_transducer_model.py
- espnet2/tasks/asr_transducer.py
Some commits I extracted from #4698 that I need to merge alongside #4720. In short:
- Add zero padding in conformer convolution module (extract from Icefall)
- Rewrite aux. LM loss computation
- Fix some docstrings, args and typos.
These changes are minor so I'll merge it after CI is done.
> Small changes for standalone Transducer

- espnet2/gan_tts/jets/jets.py
> Fix JETS inference with GST (#4743)

- egs2/chime4/enh_asr1/README.md
- egs2/chime4/enh_asr1/conf/train_lm_transformer.yaml
Related to @sw005320's [comment related to my previous PR](https://github.com/espnet/espnet/pull/4765#issuecomment-1329776040), I update the `README.md`. Also, I update lm config used in @simpleoier 's model as mentioned in [this issue](https://github.com/espnet/espnet/issues/4503).
Could you check whether the specified config files are as you used ore not, @simpleoier?
> Update README in chime4/enh_asr1

- egs2/TEMPLATE/asr1/asr.sh
This PR fixes https://github.com/espnet/espnet/issues/4839
> Fix argument parsing for non_linguistic_symbols in asr.sh

- egs2/TEMPLATE/asr1/asr.sh
- egs2/TEMPLATE/asr1/scripts/audio/format_wav_scp.sh
- egs2/msuperb/asr1/local/data.sh
- egs2/msuperb/asr1/local/data_prep.py
- egs2/msuperb/asr1/local/single_lang_data_prep.py
- egs2/msuperb/asr1/run.sh
add suffix for clear data preparation; update a reserve lang for zero-shot training;
> Minor fix for MSUPERB recipe

- doc/paper/espnet-se++/paper.md
Update minor changes in the draft of paper.md
> Update for the latest changes in the draft (minor changes)

- egs/commonvoice/asr1/run.sh
To fix one of the legacy issues reported in #2678.
> Minor fix to commonvoice espnet1

- README.md
Hi, I added a short description and link for Whisper. Please take a look, thanks!
> Add description for Whisper ASR in homepage readme

- egs2/msuperb/asr1/conf/decode_asr.yaml
- egs2/msuperb/asr1/local/data.sh
- egs2/msuperb/asr1/run_single_lang.sh
Use phone as output for msuperb single-lang track in jpn and cmn.
> MSUPERB setting update

- egs2/chime7_task1/asr1/README.md
- egs2/chime7_task1/asr1/local/install_dependencies.sh
- egs2/chime7_task1/asr1/run.sh
I wanted to update the readme with data generation instruction but mergify bot merged my PR
> Update CHiME-7 Task 1 README.md

- egs2/chime7_task1/asr1/README.md
- egs2/chime7_task1/asr1/run.sh
these are very minor things. @simpleoier can you merge when it passes the tests.
> CHiME-7 DASR correct development results

- doc/installation.md
made by @Bereket-Desbele in https://github.com/espnet/espnet/discussions/4909
> Added WSLII installation instruction

- egs2/TEMPLATE/svs1/svs.sh
- egs2/ofuton_p_utagoe_db/svs1/conf/tuning/finetune_joint_rnn_hifigan.yaml
- egs2/ofuton_p_utagoe_db/svs1/conf/tuning/finetune_joint_xiaoice_hifigan.yaml
- egs2/ofuton_p_utagoe_db/svs1/conf/tuning/train_joint_rnn_hifigan.yaml
- egs2/ofuton_p_utagoe_db/svs1/conf/tuning/train_joint_xiaoice_hifigan.yaml
- egs2/opencpop/svs1/local/data_prep.py
- espnet2/gan_svs/espnet_model.py
- espnet2/gan_svs/joint/__init__.py
- espnet2/gan_svs/joint/joint_score2wav.py
- espnet2/svs/espnet_model.py
- espnet2/svs/naive_rnn/naive_rnn_dp.py
- espnet2/svs/xiaoice/XiaoiceSing.py
- espnet2/tasks/gan_svs.py
- espnet2/tasks/svs.py
Hi @ftshijt, here are updates on Muskits.
- Add joint-train for SVS. Prepare joint train config for Xiaoice and Naive_RNN_DP.
- fix bugs in previous gan_svs.
- fix a bug in data_prep for opencpop.
> [SVS] Add Joint-training

- egs2/TEMPLATE/asr1/pyscripts/audio/format_wav_scp.py
- `np.int16` is specified for the soundfile.read: `soundfile.read(-. dtype=np.int16)`. This indicates some problems if the PCM data has uint8 or float type.
- Using kaldiio for segmentation, but kaldiio requires that the input file is wav file
- I chanced to to `soundfile.read()` withtou specifying the dtype. Note that `soundfile.read()` always returns float64 array in spite of the dtype of input pcm, and `soundfile.write` write a float64 array in int16 pcm.
- I implemented a segmentation module independent from kaldiio. This realizes supporting flac format for inputting.
e.g. The following `wav.scp` with `segments` also works.
```
ID1 cat a.flac |
```
> Modify format_wav_scp.py to support PCM of uint8, int32, float32, float64, etc.

- tools/installers/install_whisper.sh
Install `openai-whisper==20230308` to use huggingface tokenizer
> Fix Whisper tokenizer CI error

- egs2/TEMPLATE/asr1/pyscripts/audio/format_wav_scp.py
> Fix for  format_wav_scp.py

- egs2/chime7_task1/asr1/local/da_wer_scoring.py
this small PR fixes a bug for accumulating DER and JER on the three scenarios
> CHiME-7 DASR recipe, fix display bug for scenario-wide DER and JER 

- egs2/TEMPLATE/svs1/svs.sh
Hi @ftshijt, here is new update on fixing the bug of sample rate.
> [SVS] Bug fix: sample rate

- egs2/TEMPLATE/asr1/steps/libs/__init__.py
- egs2/TEMPLATE/asr1/steps/libs/common.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/__init__.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/report/__init__.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/report/log_parse.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/train/__init__.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/train/chain_objf/__init__.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/train/chain_objf/acoustic_model.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/train/common.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/train/dropout_schedule.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/train/frame_level_objf/__init__.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/train/frame_level_objf/acoustic_model.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/train/frame_level_objf/common.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/train/frame_level_objf/raw_model.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/__init__.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/attention.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/basic_layers.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/composite_layers.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/convolution.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/gru.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/layers.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/lstm.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/parser.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/stats_layer.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/trivial_layers.py
- egs2/TEMPLATE/asr1/steps/libs/nnet3/xconfig/utils.py
> Add kaldi steps/libs

- setup.py
I don't know the detail of the update. Please unfix if anyone knows.
> Fix sentencepice version to v0.1.97

- docker/.default_args
- docker/README.md
- docker/build.sh
- docker/prebuilt/devel.dockerfile
- docker/prebuilt/gpu.dockerfile
- docker/prebuilt/runtime.dockerfile
Update containers with new versions:
Python: 3.9
CUDA: 11.7
Pytorch: 1.13.1
Ubuntu: 22.04
> [WIP] Update Docker

- egs2/chime7_task1/asr1/README.md
correcting typo on README many thanks to @jungjee
> Update README.md of CHiME-7 DASR: fixing typos 

- egs2/chime7_task1/asr1/local/install_dependencies.sh
fixing lhotse version for now git+https://github.com/lhotse-speech/lhotse@1b31bf2e341e7143ad0a67ba1d7484b8353ba45b with this commit as things are changing in the master and it breaks the recipe.
> CHiME-7 DASR: Update install_dependencies.sh, fix lhotse version

- egs2/TEMPLATE/svs1/README.md
Hi @ftshijt @A-Quarter-Mile  , here are new updates:
- update README.md
> [SVS] Update docs README.md

- egs2/librimix/enh_diar1/README.md
- egs2/librimix/enh_diar1/conf/tuning/train_diar_enh_convtasnet_adapt.yaml
- egs2/librimix/enh_diar1/conf/tuning/train_diar_enh_convtasnet_concat_feats_adapt.yaml
Added model links to pretrained models for Librimix.
Updated training config for flexible speaker with batch_size=1 for temporary fix.
> Adding eendss models

- espnet2/asr/encoder/whisper_encoder.py
The specaug applied in whisper encoder has the issue mentioned here - https://github.com/espnet/espnet/issues/5198. This PR fixes it
> Quick fix for whisper specaug

- README.md
- espnet2/asr_transducer/decoder/modules/rwkv/attention.py
- espnet2/asr_transducer/decoder/rwkv_decoder.py
Fix some typos/typing/doc errors I forgot to include in # #5140. Auto-merging as it's superficial.
> Small fixes for Transducer

- egs2/ml_superb/asr1/local/score.sh
A quick fix for a bug where the few shot sets are not activated correctly.
> Fix a bug in score script for ML-SUPERB

- egs2/ml_superb/asr1/run_multi.sh
This is mainly for the case of potential issue in dict generation as 10min and 1h might have different token list during training.
> Some name update for ml-superb

- doc/espnet2_tutorial.md
Fix indent in k2 section introduced in #5268. Replace the tabs with spaces.
> Fix Transducer doc

- espnet2/gan_tts/utils/get_random_segments.py
https://github.com/espnet/espnet/issues/5266
> Fix random segments

- .github/workflows/centos7.yml
- .github/workflows/ci.yaml
- .github/workflows/debian11.yml
- .github/workflows/doc.yml
- .github/workflows/draft-pdf.yml
- .github/workflows/macos.yml
- .github/workflows/test_import.yaml
- .github/workflows/windows.yml
> Skip CI for draft PR

- .github/workflows/doc.yml
Fix the condition of doc.yml job.
The job is always skipped when merged.
https://github.com/espnet/espnet/pull/5320
https://github.com/orgs/community/discussions/25641
> Fix doc condition

- .github/ISSUE_TEMPLATE/question.md
> Update issue templates

- README.md
Update CI table in README.md
CI is updated but not reflected.
> Update CI table

- test/espnet2/gan_tts/parallel_wavegan/test_parallel_wavegan.py
- Fix numerical error issue of parallel wavegan compatibility test in CI
- To avoid randomly happened CI error 
https://github.com/espnet/espnet/pull/5269#issuecomment-1652290251
> fix numerical error of parallel wavegan compatibility test in CI

- egs/dipco/asr1/local/download_data.sh
Update Dipco Data URL
Fixes #5286
> Update Dipco Data URL

- .github/workflows/ci_on_centos7.yml
- test/espnet2/bin/test_asr_inference.py
- tools/Makefile
- fix twice numpy installation issue
- Numpy is installed twice
- https://github.com/espnet/espnet/actions/runs/6295641418/job/17089228428?pr=5400#step:6:2889
- https://github.com/espnet/espnet/actions/runs/6295641418/job/17089228428?pr=5400#step:6:5601
- This causes the following errors:
- https://github.com/espnet/espnet/actions/runs/6283509643/job/17064296788#step:7:11891
> fix twice numpy installation issue

- espnet2/bin/whisper_export_vocabulary.py
- espnet2/text/whisper_token_id_converter.py
- test/espnet2/bin/test_whisper_export_vocabulary.py
- test/espnet2/text/test_whisper_token_id_converter.py
Make changes to Whisper CI tests and assertion statements
Whisper CI checks fail because of Release 20230918 in https://github.com/openai/whisper
> Fix whisper test

- README.md
- egs2/TEMPLATE/s2t1/README.md
This PR adds documentation for [OWSM](https://arxiv.org/abs/2309.13876) (ASRU 2023).
> Add doc for OWSM

- egs2/libritts/asr1/README.md
- egs2/libritts/asr1/asr.sh
- egs2/libritts/asr1/cmd.sh
- egs2/libritts/asr1/conf/decode_asr.yaml
- egs2/libritts/asr1/conf/fbank.conf
- egs2/libritts/asr1/conf/pbs.conf
- egs2/libritts/asr1/conf/pitch.conf
- egs2/libritts/asr1/conf/queue.conf
- egs2/libritts/asr1/conf/slurm.conf
- egs2/libritts/asr1/conf/train_asr.yaml
- egs2/libritts/asr1/conf/tuning/train_asr_e_branchformer.yaml
- egs2/libritts/asr1/db.sh
- egs2/libritts/asr1/local/data.sh
- egs2/libritts/asr1/local/data_prep.sh
- egs2/libritts/asr1/local/download_and_untar.sh
- egs2/libritts/asr1/local/phonemize_dir.py
- egs2/libritts/asr1/path.sh
- egs2/libritts/asr1/pyscripts
- egs2/libritts/asr1/run.sh
- egs2/libritts/asr1/scripts
- egs2/libritts/asr1/steps
- egs2/libritts/asr1/utils
ASR recipe for LibriTTS with phonemized transcriptions.
As per discussion in https://github.com/espnet/espnet/issues/5393 
The system is similar to the system described in [this](https://www.voiceprivacychallenge.org/results-2022/docs/3___T04.pdf) paper.
I'll add results and model link in a week or two.
> Add phonemized LibriTTS ASR recipe

- egs2/ml_superb/asr1/README.md
- egs2/ml_superb/asr1/run_multi.sh
To change the default value with regard to readme
https://github.com/espnet/espnet/issues/5486
> Fix default value in ML-SUPERB

- doc/paper/espnet-se++/paper.bib
- doc/paper/espnet-se++/paper.md
Updated the reference of the JOSS paper:
Removed the unused citations in the paper.bib and updated the cite keys in the paper.md.
Solve the issue of generating pdf for the accepted JOSS paper:
https://github.com/openjournals/joss-reviews/issues/5403#issuecomment-1783349805
https://github.com/openjournals/joss-reviews/issues/5403#issuecomment-1783353740
> Updated the reference of the accepted JOSS paper

- egs2/TEMPLATE/s2t1/README.md
This PR adds a step-by-step guide on how to fine-tune existing OWSM models on a specific dataset.
> Add instructions for finetuning owsm

- egs2/TEMPLATE/enh1/enh.sh
- egs2/chime7_task1/asr1/README.md
- egs2/chime7_task1/asr1/conf/tuning/train_asr_transformer_fbank_lr1e-3_specaugm_accum1_warmup40k.yaml
- egs2/chime7_task1/asr1/conf/tuning/train_asr_transformer_wavlm_small_lr1e-4_specaugm_accum1_preenc128_warmup20k.yaml
- egs2/chime7_task1/asr1/local/data.sh
- egs2/chime7_task1/asr1/local/run_gss.sh
- egs2/chime7_task1/asr1/run.sh
- egs2/chime7_task1/diar_asr1/README.md
- egs2/chime7_task1/diar_asr1/run.sh
I have fixed some issues (bash script errors) encountered when training the ASR baseline model from scratch. 
I have also added for the gss a check whether the GPUs are in exclusive thread mode.
> Fixes for CHiME-7 DASR recipe ASR training

- README.md
Add Discord Server link
Extend community channels.
> Add Discord Server link

- egs2/acesinger/svs1/local/data.sh
Fix a bug in downloading ACESinger dataset. @ftshijt 
The data path is wrong.
> [SVS] fix download acesinger

- egs2/acesinger/svs1/README.md
- egs2/acesinger/svs1/local/data_prep.py
throw a msg on skipping preparation (if not, it may result partial set for training).
Also the official release, accidentally include some ._file, add a if case for skipping.
> Minor fix to ACEsinger preparation

- egs2/espnet_tutorial/asvspoof1/steps
- egs2/espnet_tutorial/asvspoof1/utils
Fix Kaldi dependency from ESPnet Tutorial on ASVSpoof
> Fix ESPnet tutorial

- egs2/kising/svs1/local/data.sh
- egs2/kising/svs1/local/data_prep.py
For easier switch between all, original, acesinger settings in KiSing-v2 corpus
> Fix relative setting of train-dev-test

- egs/chime4/asr1/RESULTS.md
Added clean speech results on the Conformer model.
> Added clean speech results

- doc/make_release_note_from_milestone.py
- Add script to make release note from milestone
- To generate the release note automatically
Usage:
```bash
$ python doc/make_release_note_from_milestone.py ghp_XXXXXXXXXXXXXXXXXX v.202312
```
Generated example: https://github.com/espnet/espnet/releases/tag/v.202402
> Add script to make release note from milestone

- egs2/TEMPLATE/asr1/pyscripts/utils/evaluate_speechbertscore.py
- egs2/TEMPLATE/asr1/pyscripts/utils/evaluate_speechbleu.py
- egs2/TEMPLATE/tts1/README.md
- tools/Makefile
- tools/check_install.py
- tools/installers/install_discrete_speech_metrics.sh
This PR adds evaluation scripts using discrete-speech-metrics, which can be used to evaluate text-to-speech, noisy speech, and speech enhancement.
The evaluation metrics are computed between the candidate speech and the corresponding reference speech.
<div align="left">
</div>
The metrics in discrete-speech-metrics are effective for speech synthesis evaluation because they better correlate with human subjective evaluation scores than MCD.
They also show higher correlations than UTMOS if reference speech is available.
<div align="left">
</div>
They can also be effective for noisy speech evaluation.
<div align="left">
</div>
Toolkit: https://github.com/Takaaki-Saeki/DiscreteSpeechMetrics
> Add evaluation scripts with DiscreteSpeechMetrics.

- .gitignore
- setup.py
- test_utils/test_addjson_py.bats
- test_utils/test_concatjson_py.bats
- test_utils/test_data2json_sh.bats
- test_utils/test_make_pair_json_py.bats
- test_utils/test_merge_scp2json_py.bats
- test_utils/test_mergejson_py.bats
- test_utils/test_scp2json_py.bats
- test_utils/test_splitjson_py.bats
- test_utils/test_update_json_sh.bats
- utils/data2json.sh
Fix CI Multilingual ST test
Errors
> Fix CI Multilingual ST test

- egs2/TEMPLATE/asr1/pyscripts/utils/calculate_bitrate.py
A quick fix to the calculation of bitrate
> Quick fix to calculation of bitrate

- egs2/voxtlm_v1/lm1/README.md
> Add Readme for Voxtlm

- egs2/voxtlm_v1/lm1/conf/decode_lm_asr.yaml
- egs2/voxtlm_v1/lm1/conf/train_transformer_opt350.yaml
- espnet2/lm/huggingface_pretrained_opt_lm.py
- espnet2/tasks/lm.py
Adding huggingface transformer opt model to voxtlm_v1
Huggingface transformer opt model requires additional lm model file to matcha names
Transformer with opt models can be used with _transformer_opt_
> Adding transformer_opt

- tools/setup_anaconda.sh
> Fix minor issue in anaconda downloading

- espnet2/asr/frontend/whisper.py
Small Fix to Whisper frontend to address bugs likely caused by recent code updates.
See https://github.com/espnet/espnet/issues/5550
> Fix Whisper frontend

- egs2/reverb/asr1/scripts
I added egs2/reverb/asr1/scripts
egs2/reverb/asr1/scripts doesn't exist.
> Add egs2/reverb/asr1/scripts

- egs2/TEMPLATE/lm1/lm.sh
- egs2/voxtlm_v1/lm1/README.md
- egs2/voxtlm_v1/lm1/conf/decode_lm_tts.yaml
- egs2/voxtlm_v1/lm1/db.sh
- egs2/voxtlm_v1/lm1/local/data_librilight.sh
- egs2/voxtlm_v1/lm1/local/data_librispeech.sh
- egs2/voxtlm_v1/lm1/local/data_libritts.sh
- egs2/voxtlm_v1/lm1/local/data_vctk.sh
- egs2/voxtlm_v1/lm1/local/librilight/data_prep_librilight.sh
- egs2/voxtlm_v1/lm1/local/prepare_bpe_text.py
- egs2/voxtlm_v1/lm1/local/prepare_lm_test.py
- egs2/voxtlm_v1/lm1/path.sh
Fixed bugs when running `egs2/voxtlm_v1/lm1/run.sh`. Specifically:
- Add missing files (commit c69c0a0ef3a4874b3af12365b0fbc232b51b427b, ddad665896ba3e344ee8aa2c79537366abdfd68a)
- Fix path related problems (commit 0dffa60dc55e328cf047579398359d547301d685, 08f322f6031cda9e28ab01aa044e03bdd10cd1fb, f5f012149ea47c07309acc74169f5a23f3aaac0c)
- Fix variable related problems (commit ddad665896ba3e344ee8aa2c79537366abdfd68a, ed37105d63091faebfd9cd25899496f4ead956aa, 4f920f4a068f1708ec71d5f00b2c17012bde2c24, 22cc66338e99dfeffc9a055214e5c74c168b9344, d6915e85501d84841f7383d09ce938e0e0deaea6)
- Fix typo (commit 10e6ec6b178a56800e98d6e8f7a1fcd0e406e5b5)
- Here I kept the changes minimal so that current recipe runs smoothly. More changes could be made to improve the code.
- Especially I think it …
> Bug fix for VoxtLM v1 recipe

- egs2/TEMPLATE/asr1/pyscripts/utils/make_speechlm_json.py
- egs2/TEMPLATE/asr1/pyscripts/utils/make_token_list_speechlm.py
- espnet2/bin/speechlm_inference.py
- espnet2/gan_codec/abs_gan_codec.py
- espnet2/gan_codec/espnet_model.py
- espnet2/gan_codec/soundstream/soundstream.py
- espnet2/speechlm/core_lm/abs_core_lm.py
- espnet2/speechlm/core_lm/ar_multiscale.py
Add explicit meta information for the codec models
> update meta info for reference usage

- espnet2/spk/encoder/conformer_encoder.py
Fix spk mfa-conformer forwarding
The current implementation appears to propagate only one layer of the model.
> fix spk mfa-conformer forwarding

- egs2/ml_superb/asr1/README.md
Add huggingface download options
Add 8th version for ML-SUPERB 2.0
> Add more download links for ML-SUPERB

- doc/argparse2rst.py
- doc/members2rst.py
- doc/usage2rst.sh
The source link on the homepage does not work.
This is a bugfix for it
#5847 
- Source link
- bug
- Fixed version (tested on local)
> Bug fix for source link

- egs2/TEMPLATE/asr1/pyscripts/text/huggingface_tokenize_text.py
- egs2/TEMPLATE/asr1/pyscripts/utils/speechlm_extend_vocab.py
- egs2/TEMPLATE/speechlm1/README.md
Add a script to extend the vocabulary of pre-trained Speechlm model so that it can better support fine-tuning.
> Add a script to extend the vocabulary of SpeechLM

- egs2/TEMPLATE/asr1/pyscripts/text/huggingface_tokenize_text.py
- egs2/TEMPLATE/asr1/pyscripts/utils/speechlm_extend_vocab.py
- egs2/TEMPLATE/speechlm1/README.md
Previous script didn't consider the new modality and new task. Now it is supported.
> Revision on Speechlm vocabulary extension script

- espnet2/speechlm/definitions.py
add voice conversion task and vocoder task to ESPnet speechlm.
> add vc ssl2codec template to ESPnet_speechlm

- doc/README.md
PR updates reference to the CI config file.
Commit 890ba71a267ca2fc540803fa27ee52f261cd6f8c renamed the CI config file.
> Update CI reference

- egs2/TEMPLATE/svs1/README.md
Add instruction for training VISinger 2 Plus @ftshijt
> add visinger2 plus readme

- espnetez/trainer.py
> Bug fixed for #5949

- .continueignore
- .github/workflows/publish_doc.yml
- .gitignore
- doc/.gitignore
- espnet2/bin/lightning_train.py
update parser on lightning_train
Breaks CI
https://github.com/espnet/espnet/actions/runs/12887088909
https://github.com/espnet/espnet/actions/runs/12779405259
> [Doc] Update parser on lightning_train

- egs2/TEMPLATE/s2t1/README.md
* Updating OWSM data preparation instructions
* I ran into issues while preparing the OWSM data and want to ensure future users do not ran into the same issues
> doc: update OWSM data preparation instructions

- tools/installers/install_kenlm.sh
Fix the boost URL
The boost download URL was changed
#6013
> Fix boost URL

- egs2/TEMPLATE/spk1/spk.sh
- espnet2/train/preprocessor.py
Minor fixes for SID recipe 
- preprocessor setting in no data augmentation condition
- speech shape mismatch when extracting test features
> fix some minor errors in SID recipe

- .github/workflows/publish_doc.yml
- .github/workflows/stale.yml
- Update Cache action on Publish Doc action
- Add Stale Bot for PR/Issues
Control of Issues/PRs
> Github Actions Update

- egs2/TEMPLATE/asr1/pyscripts/utils/calculate_eer_mindcf.py
- egs2/TEMPLATE/asr1/pyscripts/utils/spk_calculate_scores_from_embeddings.py
- test_utils/test_calculate_eer_mindcf_py.bats
Changed few minor typos in egs2 - asr1/pyscripts/utils shared resource template causing bugs 
I am actively using the this shared resource in my project and it was affecting my results
> fixed few typos on egs2/spk template

- egs2/TEMPLATE/tts1/README.md
Fixed link of TTS recipe
Bugfix of #6057
-
> Bugfix #6057

- .github/workflows/publish_docker_image.yml
- tools/installers/install_parallel-wavegan.sh
Update version of Docker Login Action
V1 seems to occur into troubles
Actions
> [Actions] Update Docker login

- espnet2/tasks/svs.py
update svs.py
---
fix bugs in svs.py
---
yes
---
> [svs]: fix bugs in svs.py

- egs2/longlibriheavy/asr1/asr.sh
- egs2/longlibriheavy/asr1/cmd.sh
- egs2/longlibriheavy/asr1/conf/decode_asr.yaml
- egs2/longlibriheavy/asr1/conf/fbank.conf
- egs2/longlibriheavy/asr1/conf/pbs.conf
- egs2/longlibriheavy/asr1/conf/pitch.conf
- egs2/longlibriheavy/asr1/conf/queue.conf
- egs2/longlibriheavy/asr1/conf/slurm.conf
- egs2/longlibriheavy/asr1/conf/train_asr.yaml
- egs2/longlibriheavy/asr1/conf/tuning/train_asr_e_branchformer.yaml
- egs2/longlibriheavy/asr1/db.sh
- egs2/longlibriheavy/asr1/local/data.sh
- egs2/longlibriheavy/asr1/path.sh
- egs2/longlibriheavy/asr1/pyscripts
- egs2/longlibriheavy/asr1/run.sh
- egs2/longlibriheavy/asr1/scripts
- egs2/longlibriheavy/asr1/steps
- egs2/longlibriheavy/asr1/utils
Created the recipe for LongLibriHeavy for evaluating long-form speech. There is no model trained. One can use the model trained from libriheavy_small (or any other librispeech model) to do inference on this data. 
---
---
YES
---
Benchmark Work from LongLibriHeavy accepted for Interspeech.
> LongLibriHeavy benchmark (Basic Recipe without training for now)
