.travis.yml
src/nets/e2e_asr_attctc_th.py
test/test_e2e_model.py

Pytorch 0.3.0 binary is larger than travis-CI limit (https://github.com/pytorch/pytorch/issues/4178). As a workaround, we can use pytorch0.2.0 like pyro https://github.com/uber/pyro/blob/dev/.travis.yml
There were two incompatible parts between 0.2.0 and 0.3.0
1. no `.shape` attribute in 0.2.0. we have to use `.size()` method (these are exactly same)
2. softmax/log_softmax has no `dim=1` argument in 0.2.0 but 0.3.0 raise warnings if it is missing

use pytorch0.2.0 in travis.yml and add some 0.2.0 compatiblity workaround

---

src/bin/asr_recog.py
src/bin/asr_recog_th.py
src/nets/e2e_asr_attctc.py
src/nets/e2e_asr_attctc_th.py
src/nets/e2e_asr_common.py

Added end detection described in Eq. (50) of S. Watanabe et al "Hybrid CTC/Attention Architecture for End-to-End Speech Recognition,"
If we set maxlenratio 0.0, this automatic detection is triggered.
With WSJ and Voxforge experiments, it is confirmed that the detection works well.

added end detection

---

.travis.yml
src/nets/e2e_asr_attctc.py
src/nets/e2e_asr_attctc_th.py

see #57 
Additionally, this PR requires a personal access token as `GH_TOKEN` env variable in Travis-CI. See [this instruction](https://github.com/Syntaf/travis-sphinx#obtaining-a-personal-access-token)
- NOTE: Github UI is changed from `Settings > Personal Settings > Personal access token` to `Settings > Developer Settings > Personal access token`
- NOTE: this token seems to require enabling `repo` scope in `Personal access token` settings.
I think the personal access token should be provided from @sw005320 . Anyway it is no problem to provide mine used in [my personal travis](https://travis-ci.org/ShigekiKarita/espnet) because it can be changed anytime.

Patch travis sphinx

---

src/nets/e2e_asr_attctc.py

I simplified `reshape`. In `reshape`, `-1` is converted as the number of rest of elements.
This fix does no affect performance maybe, but can simplify the code.

Simplify reshape

---

src/nets/e2e_asr_attctc.py

I replaced `xp.ones` and multiplication with `xp.full`.

Use xp.full

---

src/nets/e2e_asr_attctc.py

I think `pad_ys_out` is a `Variable` and is not a list. In such case, `concat` is not efficient. I replaced it with `flatten`.

Replace concat with flatten

---

.travis.yml
egs/ami/asr1/path.sh
egs/ami/asr1/run.sh
egs/an4/asr1/path.sh
egs/an4/asr1/run.sh
egs/chime4/asr1/path.sh
egs/chime4/asr1/run.sh
egs/csj/asr1/path.sh
egs/csj/asr1/run.sh
egs/fisher_swbd/asr1/path.sh
egs/fisher_swbd/asr1/run.sh
egs/hkust/asr1/path.sh
egs/hkust/asr1/run.sh
egs/librispeech/asr1/path.sh
egs/librispeech/asr1/run.sh
egs/swbd/asr1/path.sh
egs/swbd/asr1/run.sh
egs/tedlium/asr1/path.sh
egs/tedlium/asr1/run.sh
egs/voxforge/asr1/path.sh
egs/voxforge/asr1/run.sh
egs/wsj/asr1/path.sh
egs/wsj/asr1/run.sh
src/bin/asr_train.py
src/nets/e2e_asr_attctc.py
test/test_e2e_model.py
tools/Makefile

This PR adds warp-ctc to the Chainer model speeding up the training process (for me by roughly 35% using a GTX 980).
The new CTC method can be selected by specifying the new argument`ctctype`. There are two options:
`chainer`: Use the vanilla chainer implementation of CTC
`warpctc`: Use the warp-ctc wrapper
By default, all recipes use `chainer` for now. Maybe this can be changed in the future.
To find the warp-ctc shared library, the `path.sh` extends the `LD_LIBRARY_PATH` to include the warp-ctc build folder.
A small test verifying that the loss and the gradients are the same for both CTC types is included.
I also ran the WSJ recipe (without an external LM) and the results seem to be reasonable:
*eval92*: 18.4% WER
*dev93*: 24.2% WER

Add warp-ctc implementation to Chainer model

---

egs/ami/asr1/path.sh
egs/an4/asr1/path.sh
egs/chime4/asr1/path.sh
egs/csj/asr1/path.sh
egs/fisher_swbd/asr1/path.sh
egs/hkust/asr1/path.sh
egs/librispeech/asr1/path.sh
egs/swbd/asr1/path.sh
egs/tedlium/asr1/path.sh
egs/voxforge/asr1/path.sh
egs/wsj/asr1/path.sh

`libwarpctc.so` is located at `tools/chainer_ctc/ext/warp-ctc/build`, not `tools/chainer_ctc/ext/build`.
And we need to export `LD_LIBRARY_PATH`.

Fixed LD_LIBRARY_PATH about chainer_ctc

---

README.md
doc/requirements.txt
docker/espnet.devel
docker/run.sh

-Docker updates for automatic CUDA/CUDNN detection & building.
-docker_egs now accept subdirectories such as chime5/asr1 ...
-Fix on chime5 run.sh lm. If ngpu is 1 then lmgpu becomes 0 and cannot initialize the lm_train in gpu mode
-.dockerignore added at the parent directory so there is no need to copy folder into docker folder
-devel builds espnet by parts. In computers with low tmp memory, the make all breaks the building.

Docker & fixes

---

README.md
egs/librispeech/asr1/RESULTS

lm_weight = 0.4 seemed to show best result overall among 0.2, 0.3, and 0.4 configuration. Please refer to RESULT for details.
Also, let me know if you want me to change lm_weight in run.sh to 0.4 (it is set to 0.3 now)

librispeech RESULT update w/ diff lm_weight

---

egs/librispeech/asr1/run.sh

Utterances with more than 3000 frames (30 seconds) is causing GPU out-of-memory err
This happened in c nodes in clsp grid

Long utterance removal in librispeech recipe 

---

src/asr/asr_chainer.py
src/asr/asr_pytorch.py
src/nets/e2e_asr_attctc_th.py

- In python 3 dict.items() coud not be `dict.items()[:n]`. need to be `list(dict.items())[:n]` 
- In pytorch 0.4, `torch.LongTensor([0,1,2])[0]` is not `0` but `tensor(0)`. need explicit cast `int(...)`

fix python3 pytorch0.4 errors

---

src/nets/e2e_asr_attctc_th.py
test/test_loss.py
test/test_torch.py

In comparison with chainer VGG implementation, pytorch has been worse (BLSTMP was fine). When I discussed with @sw005320 yesterday, I found that pytorch `pad_list` causes a serious unexpected behavior in `E2E` as follows 
https://github.com/espnet/espnet/blob/3e7af572f031b4c6819172067d2ed76aea978060/src/nets/e2e_asr_attctc_th.py#L146
https://github.com/espnet/espnet/blob/3e7af572f031b4c6819172067d2ed76aea978060/src/nets/e2e_asr_attctc_th.py#L323-L325
Except for here, the `pad_value` is 0, `self.eos` or something not the default value. Although the `NaN` padding is good for finding out-of-bounds access, VGG is also set to `padding=(1, 1)` in  `torch.nn.Conv2d`. Hence it had convolved over NaN values while BLSTMP does not input over bounds of sequences.
- chainer VGGBLSTMP
- pytorch …

fix pytorch nan pad for vgg

---

src/utils/splitjson.py

Sometime `splitjson.py` is failed (e.g. #keys=250, #split=32) so I refactored it and added more logging.

Refactoring splitjson.py

---

tools/Makefile

warp-ctc fails to build with latest version of pytorch (0.4.1).
This modification fixes the version of pytorch so that you can install with make.

fix pytorch vertion to 0.4.0

---

src/utils/dump.sh

got this error in the CSJ recipe "assert(format == 'CM ') # The formats CM2, CM3 are not supported..." in "_read_compressed_mat" of kaldi_io_py. When checked some utts had CM2 header. I think copy-feats uses two CM methods by default  "kSpeechFeature if the num-rows is more than 8, and kTwoByteAuto otherwise" and kaldi_io_py doesn't have the functionality to read CM2.

force compression-method as 2 to have CM header so that there are no issues with kaldi_io_py read_mat

---

src/asr/asr_pytorch.py

Snapshot file contains the information about #iterations or #epochs, which is needed to resume training.
I added snapshot saving and modified the filename format to be the same as `tts_pytorch.py`.
- snapshot
- no save -> `snapshot.ep.1`
- model
- `model_epoch1` -> `model.ep.1`
When resuming, `model.ep.1` is loaded instead of `model.acc.best`.

Save snapshot to resume

---

tools/Makefile

As `master` branch of ESPnet supports only pytorch>=0.4.1, I fixed default branch of warp-ctc to follow recent update. cf. https://github.com/jnishi/warp-ctc/pull/3

fix branch to fetch warp-ctc

---

README.md
tools/Makefile

This PR makes it possible to setup again easily.
If we want to re-setup only python libraries, use following commands.
```sh
$ cd tools
$ make clean_python
$ make all_python
```

Add shortcut to re-setup python libraries 

---

src/asr/asr_chainer.py
src/asr/asr_pytorch.py

Use `SerielIterator` to validation dataset and set `n_processes=1` to train dataset to reduce memory usage which is discussed in https://github.com/espnet/espnet/pull/340#issuecomment-416615426.

Reduce processes 

---

src/tts/tts_pytorch.py

This PR removes duplicated lines in `tts_pytorch.py`.
Snapshot is saved with `torch_snapshot()`, no need to take snapshot with `extensions.snapshot`.

Remove duplicated lines

---

.travis.yml
tools/conda.mk

It needs to be updated because current miniconda env in `tools/conda.mk` uses python3.7 rather than 3.6.

Update travis.yml to use python 3.7

---

tools/Makefile

Changing from venv to virtualenv
I found that venv exists for python 3.5+, but not for 2.7 (ESPnet default).
I cannot build the docker containers if I use venv, because it does not exists. 
Should I install python 3.5 venv in the docker containers to support this config? otherwise merge please.

command fix

---

.gitignore
tools/Makefile
tools/check_install.py

This PR fixes following problems:
- fixed Makefile to install torch in the case of w/o conda
- fixed .gitignore to ignore some files related to new installation. e.g. `.eggs`, `*.done`, and so on.
- fixed check_install.py (#451)

Fix Makefile

---

espnet/nets/e2e_asr_th.py

Fix #479 
(LongTensor) * (float value) will be 0.
Please be careful. 
```
In [4]: import torch
In [5]: lens = torch.LongTensor([324])
In [6]: max(lens) * 0.5
Out[6]: tensor(0)
In [7]: max(lens)
Out[7]: tensor(324)
```

Fix a bug related to LongTensor * float = 0

---

espnet/nets/e2e_asr_th.py
espnet/nets/e2e_tts_th.py

Current `make_pad_mask` and `make_non_pad_mask` cause error when `lengths` is `cuda.Tensor`.
I added type check to convert to `list` in order to avoid this error.

Fix make_pad_mask and make_non_pad_mask

---

egs/ami/asr1/path.sh
egs/an4/asr1/path.sh
egs/babel/asr1/path.sh
egs/chime4/asr1/path.sh
egs/chime5/asr1/path.sh
egs/csj/asr1/path.sh
egs/fisher_callhome_spanish/asr1/path.sh
egs/fisher_swbd/asr1/path.sh
egs/hkust/asr1/path.sh
egs/hub4_spanish/asr1/path.sh
egs/iwslt18st/st1/path.sh
egs/jsalt18e2e/asr1/path.sh
egs/li10/asr1/path.sh
egs/librispeech/asr1/path.sh
egs/librispeech/tts1/path.sh
egs/ljspeech/tts1/path.sh
egs/ljspeech/tts2/path.sh
egs/reverb/asr1/path.sh
egs/swbd/asr1/path.sh
egs/tedlium/asr1/path.sh
egs/voxforge/asr1/path.sh
egs/wsj/asr1/path.sh

Fixed the following problem:
Named as test.sh
```bash
source venv/bin/activate
which python
```
Type this,
```bash
test.sh aaaa
```
Then got,
```
Could not find conda environment: aa
You can list all discoverable environments with `conda info --envs`.
(original python, not espnet's)
```
This can happen if the scripts in `utils` source `path.sh` and it requires some arguments as the following,
```bash
. path.sh 
echo $1
```
Thus, I change to `path.sh` to use `conda activate` instead of  `source activate` .
Note that this issue is only particular to use `conda`, so if using `virtualenv`, you don't met it. 
I also inserted `conda deativate` before `conda activate` to avoid the following case,
```
conda activate
which python #  Return conda/bin/python
export PATH=/somewhere/bin/:$PATH
conda …
```

Fix conda source problem

---

.gitignore
espnet/asr/chainer_backend/asr.py
espnet/nets/chainer_backend/e2e_asr.py
espnet/utils/training/tensorboard_logger.py
test/test_e2e_asr.py

There are few observations:
The Loss E2E code from previous versions returned `return self.loss`
Now, the E2E model is returning `return self.loss, loss_ctc, loss_att, acc`. This generates a error in the [Worker](https://github.com/chainer/chainer/blob/6b292dee96ad7b281589632ccecdd1348eef0f5f/chainer/training/updaters/multiprocess_parallel_updater.py#L238) of the ParallelUpdater since the code is not controlling the return of the self.loss only.
Given this, I added a flag to return only Loss during training. This flag was added in order to avoid additional changes in the code, especially in the test that request the loss as a part of a tuple.
The updates were tested on a docker container. My current setup (if I do not use docker) is having a miscalculation in the grad (Extremely larges …

Chainer MultiGPU fix v.0.3.0

---

egs/librispeech/asr1/run.sh
utils/reduce_data_dir.sh

First `utt2num_frames` is not combined by `utils/combine_data.sh`, and next it is not copied in `reduce_data_dir.sh` called from `remove_longshortdata.sh`.

Avoid utt2num_frames regeneration in LibriSpeech recipe

---

setup.py

- Change to use `commonmark==0.8.1` to avoid `ImportError: No module named 'CommonMark'`: https://github.com/conda-forge/recommonmark-feedstock/issues/2
- I don't understand why this happens now.
- Apppend `encoding='utf-8'`Unicode problem when 'LC_ALL=C', which is set by kaldi

Fix:   setup.py

---

.travis.yml
tools/conda.mk

I can't understand why this part we needs:
https://github.com/espnet/espnet/blob/c6b78d73eee35c2116d19d24a8ccbb03653c6749/tools/conda.mk#L21
The both is not recommended for normal usage.

Stop to change conda-config

---

espnet/transform/transformation.py
espnet/utils/cli_utils.py
espnet/utils/io_utils.py
utils/apply-cmvn.py
utils/copy-feats.py
utils/data2json.sh
utils/feat-to-shape.py

Minor fixes for #493
- Changed `dataset[...]` -> `dataset[()]`: The former may cause memory issue. 
- FYI: `dataset.value` is deprecated now and `dataset[()]` is recommended.
- I don't understand why these two are different and the former causes memory issue, I doubt this is a bug of h5py. h5py is not documented about this yet.
- Implemented `return_shape` option for `FileReaderWrapper`. 
- `feats-to-shape.py` requires the shape information only, so the whole data loading for the dataset is not efficient for speed. 
- It doesn't make sense for `kaldi-ark` because `kaldiio` doesn't support loading the header only.
- Changed not to use `collections.Sequence` if PY3, which will be removed in `python=3.8`

Fix memory issue and optimize the speed for feat-to-shape.py

---

.travis.yml
espnet/bin/asr_train.py
espnet/nets/chainer_backend/ctc.py
espnet/nets/pytorch_backend/ctc.py
espnet/nets/pytorch_backend/decoders.py
espnet/nets/pytorch_backend/e2e_asr.py
espnet/nets/pytorch_backend/encoders.py
test/test_e2e_asr.py
test/test_initialization.py
test/test_loss.py
test/test_optimizer.py
test/test_recog.py
tools/Makefile
tools/conda.mk

#514 
- Uses `torch.nn.CTCLoss` instead of `warp-ctc` if `pytorch>=1.0.0`.
- `size_average=True` -> `reduction="mean"` if `pytorch>=1.0.0` or `reduction="elementwise_mean"` if `pytorch<1.0.0` .
- Travis: Tests both `0.4.1` and `1.0.0`.

Support PyTorch==1.0

---

.travis.yml
tools/Makefile

Today when I tried to build ESPnet from scratch, I found the file structure of "kaldi-io-for-python" has been changed (https://github.com/vesis84/kaldi-io-for-python). So I made a small modification of the Makefile under "tools".

Small change of the "Makefile" under "tools"

---

test_utils/test_merge_scp2json_py.bats
utils/data2json.sh
utils/merge_scp2json.py

The current flow of `data2json.sh`:
1. Creates text files, e.g. feats.scp, text, ...
1. Change each files to JSON files using `scp2json.py`
1. Merge JSON files into one
The second step looks redundant. So I modified it to
1. Creates text files, e.g. feats.scp, text, ...
1. Merge text files into a JSON file
For this, I created a new util: `merge_scp2json.py`
```sh
merge_scp2json.py ¥
--input-scps feat:feats.scp shape:shape.scp:shape ¥
--input-scps feat:feats2.scp shape:shape2.scp:shape ¥
--output-scps text:text ¥
--scps utt2spk 
```
The format of each arguments is `<key>:<filepath>:<type>`, where `<type>` indicated the data type registered in the output json, e.g. :
```sh
% cat foo.txt
a 3
b 10
% merge_scp2json.py --input-scps bar:foo.txt:int
{
"utts": {
"a": {
"input": [
{
"bar": 3, …
```

[Need to discuss] New style of mergejson.py

---

espnet/asr/pytorch_backend/asr.py
espnet/nets/pytorch_backend/ctc.py
espnet/nets/pytorch_backend/e2e_asr.py
test/test_e2e_asr.py
test/test_initialization.py
test/test_recog.py

The CER between true sentences and sentences estimated by CTC without beam search is written to a log file and a png file during training. The following example is a png generated by running the WSJ recipe.

[WIP] Exploit information from CTC

---

espnet/nets/pytorch_backend/ctc.py

#616 
This is a fatal bug because now always using pytorch.CTCLoss instead of warpctc for testing.

Fix a fatal bug around CTC when testing

---

egs/swbd/asr1/local/score_sclite.sh
egs/swbd/asr1/run.sh
utils/trn_to_ctm.py
utils/trn_to_stm.py

Adds trn_to_ctm and trn_to_stm to create appropriate files for scoring and adapts kaldi swbd's score_sclite for espnet
By using this scoring scheme (the same as kaldi, so we have a common scoring now), I got a WER reduction from, for example, 58.3% to 44.1%, 37.7% to 26.3%, etc
It could probably be applied to other hub5 benchmarks like fisher or callhome too

Uses hubscr for swbd scoring

---

egs/fisher_swbd/asr1/local/score_sclite.sh
egs/fisher_swbd/asr1/run.sh
egs/swbd/asr1/local/score_sclite.sh
utils/filt.py
utils/json2sctm.py
utils/json2trn.py
utils/score_sclite.sh
utils/trn2ctm.py
utils/trn2stm.py

I've found a local/score_sclite on kaldi only for fisher_swbd    
- Renamed trn_to_* to trn2* to follow other files convention
- Adds json2sctm to directly go from json to ctm and stm files
- local/score_sclite can take an optional `dict` argument. If it's not supplied, it assumes that the ref/hyp.wrd.trn exist and uses trn2*. Otherwise it uses json2sctm.

Fisher_swbd scoring

---

tools/Makefile

I found `mecab-python3` is not installed in `venv`.
This PR fixed this issue.

Fix mecab installation

---

egs/aishell/asr1/run.sh
egs/ami/asr1/run.sh
egs/an4/asr1/run.sh
egs/babel/asr1/run.sh
egs/chime4/asr1/run.sh
egs/chime5/asr1/run.sh
egs/csj/asr1/run.sh
egs/fisher_callhome_spanish/asr1/run.sh
egs/fisher_callhome_spanish_st/st1/run.sh
egs/fisher_swbd/asr1/run.sh
egs/hkust/asr1/run.sh
egs/hub4_spanish/asr1/run.sh
egs/iwslt18st/st1/run.sh
egs/jsalt18e2e/asr1/run.sh
egs/li10/asr1/run.sh
egs/librispeech/asr1/run.sh
egs/reverb/asr1/run.sh
egs/swbd/asr1/run.sh
egs/tedlium/asr1/run.sh
egs/voxforge/asr1/run.sh
egs/wsj/asr1/run.sh
egs/wsj_mix/asr1/run.sh
egs/yesno/asr1/run.sh

This is a bash technique: `wait` command always returns 0 without arguments, and if pid is given, then it can return the return code of the background process. 
```
set -e 
fail_command &
wait  # Always 0, so cannot stop here
fail_command &
wait $! # returns non-zero, so this code will exit here.
```
I modified an4/run.sh only for example.

Modify for parallel back ground jobs

---

.travis.yml

From April 16th, travis use python3 as default python.
This PR fixes the issue related to the above change.

Fix to use python2 as default in travis

---

README.md
tools/Makefile

I want to specify CUDA version when I install pytorch binary because its default is CUDA9 but I have a different version.

add CUDA_VERSION in Makefile

---

tools/Makefile

With 1f758b5445dc8963d0785a612fae8c886342cc10 , an additional condition was added to the makefile in order to ensure that the cpu version of pytorch would be used, unless nvidia-smi was available.
However, as of now, pytorch-cpu is downloaded if nvidia-smi is available. The normal pytorch library is downloaded if nvidia-smi isn't available.
Also fixed a syntax error.

fix choice between pytorch and pytorch-cpu

---

utils/data2json.sh
utils/merge_scp2json.py

#699
I added `--allow-one-column` to `data.sh` and `merge_scp2json.py`.
If `text` having no labels is expected, we need to add `--allow-one-column true` in such recipes. Maybe this is not good solution.
@sw005320 Can you modify swbd recipe? I can't get the data now.

Fix merge_json behavior when no labels #699

---

espnet/asr/chainer_backend/asr.py
espnet/asr/pytorch_backend/asr.py
espnet/asr/pytorch_backend/asr_mix.py
espnet/lm/chainer_backend/lm.py
espnet/lm/pytorch_backend/lm.py
espnet/tts/pytorch_backend/tts.py

Some json files are not human-readable (#723).
e.g. 
```
"utts": {
"A03M0106_0526591_0534158": {
"output": [
{
"name": "target1[1]",
"rec_text": "\u540c\u3058\u5236\u5fa1\u3067\u69cb\u6587\u89e3\u6790\u304c\u3067\u304d\u308b\u3068\u3067\u3053\u306e\u5834\u5408\u91cd\u8981\u306a\u306e\u306f\u3053\u306e\u30a2\u30eb\u30b4\u30ea\u30ba\u30e0\u304c\u30aa\u30fc\u30c8\u30de\u30c8\u306e\u5177\u4f53\u7cfb\u306b\u4f9d\u5b58\u3057\u306a\u3044\u3068\u3044\u3046\u70b9\u306b\u3054\u3056\u3044\u307e\u3059<eos>",
"rec_token": "\u540c \u3058 \u5236 \u5fa1 \u3067 \u69cb \u6587 \u89e3 \u6790 \u304c \u3067 \u304d \u308b \u3068 \u3067 \u3053 \u306e \u5834 \u5408 \u91cd \u8981 \u306a \u306e \u306f \u3053 \u306e \u30a2 \u30eb \u30b4 \u30ea \u30ba \u30e0 \u304c \u30aa \u30fc \u30c8 \u30de \u30c8 \u306e \u5177 …
```

Use ensure_ascii=False to make json human-readable

---

espnet/asr/chainer_backend/asr.py
espnet/asr/pytorch_backend/asr.py
espnet/asr/pytorch_backend/asr_mix.py
espnet/lm/chainer_backend/lm.py
espnet/lm/pytorch_backend/lm.py
espnet/tts/pytorch_backend/tts.py

The logging directory for [`SummaryWriter`](https://tensorboardx.readthedocs.io/en/latest/tensorboard.html) is called `logdir` and not `log_dir`. Without these changes, I end up with the following error when running the example in the README, `an4/asr1/run.sh`:
```
Traceback (most recent call last):
File "/home/doneata/src/espnet/espnet/bin/asr_train.py", line 274, in <module>
main(sys.argv[1:])
File "/home/doneata/src/espnet/espnet/bin/asr_train.py", line 262, in main
train(args)
File "/home/doneata/src/espnet/espnet/asr/pytorch_backend/asr.py", line 415, in train
writer = SummaryWriter(log_dir=args.tensorboard_dir)
File "/home/doneata/src/espnet/tools/venv/lib/python3.6/site-packages/tensorboardX/writer.py", line 254, in __init_
_
self._get_file_writer()
File …
```

FIX Argument name for SummaryWriter

---

espnet/asr/asr_utils.py
espnet/asr/pytorch_backend/asr.py
espnet/asr/pytorch_backend/asr_mix.py
espnet/lm/pytorch_backend/lm.py
espnet/tts/pytorch_backend/tts.py

The corrections for pytorch with chainer v6.0.0 are included in this PR, to solve #760. 
- Modified LMTest; this returned gpuid as a GPUId class, set self.device inside __init__
- Replaced extensions.snapshot_object for (custom) snapshot_object. V6.0.0 call first [serialize](https://github.com/chainer/chainer/blob/17796d7cf17f667eb4e7b7cd41778ad9ec56c749/chainer/training/extensions/_snapshot.py#L228) and the use the savefun method (not sure why it does this), so the training will raise error due to the lack of serialize routine.  While v5.0.0 is [straight](https://github.com/chainer/chainer/blob/e4a0b8fca2fdd893c491de79f0b66129d0d15824/chainer/training/extensions/_snapshot.py#L81). Just copied the required code into the 'asr_utils' and replace the line in 'pytorch/asr/train' and …

Fix pytorch for chainer v6.0.0

---

egs/jsut/tts1/conf/train_pytorch_tacotron2.yaml
egs/ljspeech/tts1/conf/tuning/train_pytorch_tacotron2.v1.yaml
egs/ljspeech/tts1/conf/tuning/train_pytorch_tacotron2.v2.yaml
egs/m_ailabs/tts1/conf/tuning/train_pytorch_tacotron2.v1.yaml
egs/m_ailabs/tts1/conf/tuning/train_pytorch_tacotron2.v2.yaml

In the case of TTS, loss value itself is not reliable.
Therefore, I update patience not to use early stopping.

Update patience in TTS recipes

---

egs/an4/tts1/run.sh
egs/jsut/tts1/run.sh
egs/libritts/tts1/run.sh
egs/ljspeech/tts1/run.sh
egs/ljspeech/tts2/run.sh
egs/m_ailabs/tts1/run.sh
egs/yesno/tts1/run.sh

This PR supports `n_average` option in TTS recipe.
In contrast to ASR, over-fit model does not always result in bad generated speech.
Therefore, I changed to use `n_average` option even if `n_average=1`.
In this case we just use the last model for decoding.

Support n_average option

---

setup.py
tools/Makefile

I moved python modules originated from github repos from Makefile to setup.py
This setup.py uses `module@URL` syntax https://github.com/pypa/pip/pull/4175, and it was enabled on `pip==19`, which was released on Jan 2019. 
I also added python version check.
If `warp-ctc` and `chainer-ctc` can be installed by such way, then we can freeze all python dependencies in setup.py. It may be useful for google colab environment.

Move the dependency links to github from Makefile to setup.py

---

egs/aishell/asr1/local/download_and_untar.sh

This might cause error if download is interrupted, because wget will rename the file if old one is not deleted.

Fix tgz typo

---

.travis.yml

because some scripts under `utils/*.sh`, require `tools/venv/bin/activate` in `. path.sh`
- error log (no conda) https://travis-ci.org/ShigekiKarita/espnet/jobs/548190174#L1402
- success log (conda) https://travis-ci.org/ShigekiKarita/espnet/jobs/548190173#L3008

use only conda to build doc

---

.travis.yml

By specifying commit message, we can avoid running CI on gh-pages
- https://github.com/Syntaf/travis-sphinx#specifying-a-custom-deploy-repository
- https://circleci.com/docs/2.0/skip-build/

skip ci when gh-pages is deployed

---

espnet/nets/pytorch_backend/transformer/subsampling.py

@Fhrozen This bug shoould be fixed in master.
```
convodim(x) := floor((x - 2 * pad - dilation * (kernel - 1) -1) / stride + 1)
= floor((x - 3) / 2 + 1)
= floor((x - 1) / 2)
odim = convodim(convodim(idim))
= floor((floor((idim - 1) / 2)) - 1) / 2)
```
The first equation is referred from https://pytorch.org/docs/stable/nn.html#convolution-layers

Fix: Output dimension of Conv2dSubsampling #822

---

ci/install.sh
egs/librispeech/asr1/run.sh

Librispeech requires `sentencepiece` tools to be installed. Script should exist if path sourcing fails, otherwise the master script won't succeed.

run.sh should exit if sourcing path.sh return error

---

espnet/transform/spectrogram.py

I needed control to change `pad_mode` (I was using `pad_mode="constant"`) when computing log mel-spectrogram.

transform: expose pad_mode for logmelspectrogram

---

espnet/lm/pytorch_backend/lm.py

I found LM GPU training cannot run without cupy because of the unnecessary device option added by the recent chainer 6.0.0 change.
I'm already tested this modification with my previous asru2019 branch https://github.com/ShigekiKarita/espnet/commits/asru2019/espnet/lm/pytorch_backend/lm.py

Fix pytorch LM GPU training without cupy

---

egs/librispeech/asr1/run.sh

A little bug when running decode in librispeech run.sh, lang_model need to use lm_n_average, not n_average.

 Fix lm_n_average in lang_model

---

egs/an4/asr1/cmd.sh
egs/an4/asr1/run.sh
espnet/bin/asr_train.py
espnet/bin/lm_train.py
espnet/bin/tts_train.py
utils/free-gpu.sh
utils/queue-freegpu.pl

This PR is a refactoring request of this part of *_train.py
https://github.com/espnet/espnet/blob/f6b55b38a8b5e12a7b88df887dd7d5aa5cd0f6e0/espnet/bin/asr_train.py#L313-L331,
This part works only at JHU and  such codes shouldn't be written in python level. 
I created queue-freegpu.pl, which is almost same as kaldi's `queue.pl` except that it invokes `free-gpu` command and set CUDA_VISIBLE_DEVICES as this part do.
Note that queue-freegpu.pl is a private tool for JHU. 
I also changed the behaviour of `--ngpu` of `*_train.py`:
1. If --npu is given, use as it is.
1. elif CUDA_VISIBLE_DEVICES=None, use the number of visible devices.
1. elif nvidia-smi can be invoked, use the number of all devices.
1. else ngpu==0
Recent job scheduler such as slurm, torque, can manage GPU resources and user …

Remove "free-gpu" from *_train and create queue-freegpu.pl

---

.travis.yml
ci/doc.sh
tools/Makefile

This PR updates Travis as follows:
- Reduce travis jobs 8 -> 3 by removing conda and chainer 5.0.0 cases. This is because Circle CI already tests conda environments and we already use chainer 6.0.0 as default (while pytorch 1.0.1 is default)
- Update `ci/doc.sh` for non conda environment
- Update `tools/Makefile` to retry wget (this is minor change)

Reduce travis jobs

---

espnet/nets/chainer_backend/e2e_asr.py

In response to #1038, the mtl loss calculation is being rolled back.

Fix Loss Calculation

---

README.md
egs/tedlium2/asr1/RESULTS.md
egs/tedlium2/asr1/conf/lm.yaml
egs/tedlium2/asr1/conf/specaug.yaml
egs/tedlium2/asr1/conf/tuning/decode_pytorch_transformer.yaml
egs/tedlium2/asr1/run.sh

- Model files (archived to large.tar.gz by `$ pack_model.sh`)
- model link: (put the model link manually. please contact Shinji Watanabe <shinjiw@ieee.org> if you want a web storage to put your files)
- training config file: `./conf/tuning/train_pytorch_transformer.v2_epochs100.yaml`
- decoding config file: `./conf/decode_lm-weight0.5_beam-size40.yaml`
- cmvn file: `./data/train_trim_sp/cmvn.ark`
- e2e file: `./exp/train_trim_sp_pytorch_nbpe500_ngpu2_train_pytorch_transformer.v2_epochs100_specaug/results/model.last10.avg.best.ep86_irielmep1_beam40`
- e2e JSON file: `./exp/train_trim_sp_pytorch_nbpe500_ngpu2_train_pytorch_transformer.v2_epochs100_specaug/results/model.json`
- lm file: `./exp/train_rnnlm_pytorch_lm_irie_batchsize128_unigram500/rnnlm.model.best`
- lm JSON file: …

update tedlium2 config

---

utils/data2json.sh
utils/dump.sh
utils/dump_pcm.sh
utils/eval_source_separation.sh
utils/feat_to_shape.sh
utils/make_fbank.sh
utils/make_stft.sh
utils/pack_model.sh
utils/reduce_data_dir.sh
utils/remove_longshortdata.sh
utils/score_sclite.sh
utils/synth_wav.sh

```bash
Usage: $ /home/t_hayashi/workspace5/work/espnet_repositories/espnet_v.0.5.0/utils/synth_wav.sh <text> Example: # make text file and then generate it echo "This is a demonstration of text to speech." > example.txt /home/t_hayashi/workspace5/work/espnet_repositories/espnet_v.0.5.0/utils/synth_wav.sh example.txt # you can specify the pretrained models /home/t_hayashi/workspace5/work/espnet_repositories/espnet_v.0.5.0/utils/synth_wav.sh --models ljspeech.tacotron2.v3 example.txt Available models: - libritts.tacotron2.v1 - ljspeech.tacotron2.v1 - ljspeech.tacotron2.v2 - ljspeech.tacotron2.v3 - ljspeech.transformer.v1 - ljspeech.transformer.v2 - ljspeech.fastspeech.v1 - ljspeech.fastspeech.v2
Usage:
$ /home/t_hayashi/workspace5/work/espnet_repositories/espnet_v.0.5.0/utils/synth_wav.sh …
```

Fix help message to enable line break

---

egs/an4/tts1/run.sh
egs/jsut/tts1/run.sh
egs/libritts/tts1/run.sh
egs/ljspeech/tts1/run.sh
egs/ljspeech/tts2/run.sh
egs/m_ailabs/tts1/run.sh
egs/yesno/tts1/run.sh
setup.py
utils/convert_fbank_to_wav.py
utils/synth_wav.sh

From librosa 0.7.0, it supports fast Griffin-Lim (a.k.a. Griffin-Lim with momentum).
https://librosa.github.io/librosa/generated/librosa.core.griffinlim.html#librosa.core.griffinlim
This PR modifies the code to use librosa's Griffin-Lim.

Use librosa's fast Griffin-Lim

---

egs/mini_an4/asr1/run.sh
utils/spm_decode

Python version of `utils/spm_decode` (I picked this from fairseq) had different interface to C++ one. Therefore `utils/score_sclite.sh` raise errors when we use it with spm.

Fix spm decode

---

egs/mini_an4/asr1/run.sh
egs/tedlium3/asr1/run.sh
espnet/asr/asr_utils.py
espnet/bin/lm_train.py
espnet/lm/lm_utils.py
espnet/lm/pytorch_backend/lm.py

This PR aims to fix #1075 . I tested this by AN4 and TEDLIUM3. 
I found @kan-bayashi's comment was correct. The memory leak appeared when single GPU performs the frame reduction of loss values from multi GPUs. So I added the `ReduceFramewiseLoss` module to do it in multi GPUs.
In addition, I added HDF5 dump support for LM dataset because some large corpora, e.g., TEDLIUM3, results in 3GB of text dataset and it took 3 mins for preprocessing. After HDF5 dump performed, it only took 30 secs to load that. It really helps me testing this problem, and running rapid try-and-errors in the large LM experiment. (PS. I also tested pickle but it seems to perform very slow and save large bin.)

Fix multi gpu LM issues and add hdf5 LM dataset dump

---

espnet/nets/chainer_backend/e2e_asr_transformer.py

This fix cover the decoding for chainer.transformer. 
Given than the encoder output has now 3 dimensions, need to set correctly the length of the output (to the axis 1)

Fix decoding for chainer transformer

---

espnet/nets/pytorch_backend/transformer/embedding.py
test/test_positional_encoding.py

This is a rework of #1060 (by @takenori-y) not only for inference but also for inference. I found my PR including TransformerLM requires a much longer cache for PE. So I made this both for training and inference.

 Allow to extend the length of positional encoding at training and inference

---

ci/test_flake8.sh
espnet/nets/asr_interface.py

This is a minor fix to the CI error caused by the order of merging these two #1092 #1065.
The #1092 introduces flake8-docstrings that raises an error when newly added python modules does not follow its rules. And it is now discribed in [doc/README.md](doc/README.md). However #1065 could not know that because the PR was proposed first.
This PR just added the RNN transducer related modules into the blacklist.

Fix flake8 blacklist

---

espnet/nets/pytorch_backend/transformer/embedding.py
test/test_positional_encoding.py

As reported in #1121, we have small breaking change in PE in my previous PR #1105. This PR registers pre-hook function to ignore the state `self.pe` that we previously saved (while we do not save it now).

Fix backward compatibility problem in PositionalEncoding by adding pre-hook to ignore `self.pe`

---

ci/test_integration.sh
espnet/asr/asr_utils.py
espnet/asr/pytorch_backend/asr.py
espnet/bin/asr_recog.py
espnet/bin/asr_train.py
espnet/bin/lm_train.py
espnet/lm/pytorch_backend/lm.py
espnet/nets/asr_interface.py
espnet/nets/pytorch_backend/ctc.py
espnet/nets/pytorch_backend/e2e_asr.py
espnet/nets/pytorch_backend/transformer/plot.py
espnet/utils/fill_missing_args.py
test/test_asr_interface.py
test/test_beam_search.py
test/test_train_dtype.py

This is similar to `--dtype floatXX` option in `asr_recog.py --api v2`. Because `--dtype` is already used for RNN ASR model, I named this option as `--train-dtype`.

Add --train-dtype option for float16/float32/float64 precision training in pytorch ASR and LM

---

ci/test_flake8.sh
egs/voxforge/asr1/conf/tuning/train_transducer.yaml
espnet/asr/pytorch_backend/asr.py
espnet/nets/asr_interface.py
espnet/nets/pytorch_backend/e2e_asr_transducer.py
espnet/nets/pytorch_backend/rnn/decoders_transducer.py
test/test_e2e_asr_transducer.py

Hi,
I’m making this PR to fix some things for transducer :
- add missing argument `score_norm_transducer` for when report_cer=True or report_wer=True
- add argument relative to fix in `tests/test_e2e_asr_transducer.py`.
- raise error for temporary unavailable batch decoding for transducer (@ShigekiKarita  : I did as you mentioned in previous PR and put the assertion in `asr/asr.py`, is that okay like this?)
- modify voxforge example (initial config was used with pre-trained CTC encoder) to have performances closer to other E2E models. It's probably not the best config though.
Example of results for dt_it:
```
Trans (CER)	| 1082   79133 | 86.9    5.7    7.4    2.9   16.1   97.9 |
Trans (WER)	| 1082  13235 | 57.7   34.8    7.5    5.1   47.4   97.9 | …
```

Transducer v1.1

---

ci/doc.sh
doc/conf.py
doc/module2rst.py
espnet/lm/lm_utils.py
espnet/utils/spec_augment.py

Fix #1154 
I stop using pkgutil because it does not import dir without `__init__.py`
So I will use glob instead because it literally retrieves any files under the dir.

Fix doc/module2rst.py to use glob and remove --nowarn from travis-sphinx

---

utils/download_from_google_drive.sh

This was failing because OSX's grep doesn't support -P option. Use perl directly instead of using -P option (Perl regular expressions).
Ref: https://stackoverflow.com/questions/16658333/grep-p-no-longer-works-how-can-i-rewrite-my-searches

Fix download_from gdrive.sh on osx

---

tools/Makefile

Hi,
`warprnnt_pytorch` will fails if `make -j X` is used. Switching from command name to variable MAKE resolve the issue.

fix recursive make

---

tools/Makefile

I'm working to reorganize branch structure of warp-ctc repository (see https://github.com/espnet/warp-ctc/issues/8 ) and update tools/Makefile to install warpctc-pytorch from pytorch-0.4 branch when PyTorch version is 0.4.X

Install warpctc-pytorch from pytorch-0.4 branch when PyTorch version is 0.4.X

---

utils/generate_wav_from_fbank.py

Fixes:
```
2019-08-31 06:52:12,670 (generate_wav_from_fbank:167) INFO: generation speed = 0.27367370203519414 (sec / sample)
Traceback (most recent call last):
File "/home/ryuichi/espnet_upstream/egs/ljspeech/tts1/../../../utils/generate_wav_from_fbank.py", line 180, in <module>
main()
File "/home/ryuichi/espnet_upstream/egs/ljspeech/tts1/../../../utils/generate_wav_from_fbank.py", line 171, in main
y = mlsa_filter(y)
File "/home/ryuichi/espnet_upstream/egs/ljspeech/tts1/../../../utils/generate_wav_from_fbank.py", line 70, in __call__
coef = np.tile(self.coef, [num_frames, 1])
AttributeError: 'TimeInvariantMLSAFilter' object has no attribute 'coef'
```

Fix error on waveform generation by WaveNet

---

README.md
utils/feats2npy.py
utils/synth_wav.sh

New vocoder model: `ljspeech.wavenet.mol.v1` (MoL: mixture of logistics; see http://proceedings.mlr.press/v80/oord18a.html for details)
WIP since https://github.com/r9y9/wavenet_vocoder/pull/164 is not merged yet. If you want to try this out, run the following command at the `egs/ljspeech/tts1` directory:
```
../../../utils/synth_wav.sh --stage 0 --stop-stage 5 --models ljspeech.transformer.v1 --vocoder-models ljspeech.wavenet.mol.v1 example.txt
```
The MoL WaveNet was trained for 1800k steps. Hyper parameters can be found at https://github.com/r9y9/wavenet_vocoder/blob/33da3ac619e1663f3664d23e637c47ee9aa5bc6f/egs/mol/conf/mol_wavenet.json.

Add support for MoL WaveNet to synth_wav.sh

---

utils/synth_wav.sh

Two fixes were done for https://github.com/r9y9/wavenet_vocoder:
1. fixed weird error message at evaluation time
```
/aaa/bbb/nnmnkwii/nnmnkwii/datasets/__init__.py:125:
UserWarning: No files are collected. You might have specified wrong data
source.
warn("No files are collected. You might have specified wrong data
source.")
```
2. changed wav file format to int16, not float32 (ref: https://github.com/espnet/espnet-tts-sample/pull/1)

TTS: MoL WaveNet minor update

---

tools/Makefile
tools/check_install.py

This pull request enables installing warp-ctc from PyPI when PyTorch version is 1.0.
Currently following wheels are served at pypi.org in both Python 3.6 and 3.7.
- [warpctc-pytorch10-cuda101](https://pypi.org/project/warpctc-pytorch10-cuda101/)
- [warpctc-pytorch10-cuda100](https://pypi.org/project/warpctc-pytorch10-cuda100/)
- [warpctc-pytorch10-cuda92](https://pypi.org/project/warpctc-pytorch10-cuda92/)
- [warpctc-pytorch10-cuda91](https://pypi.org/project/warpctc-pytorch10-cuda91/)
- [warpctc-pytorch10-cuda90](https://pypi.org/project/warpctc-pytorch10-cuda90/)
- [warpctc-pytorch10-cuda80](https://pypi.org/project/warpctc-pytorch10-cuda80/)
- [warpctc-pytorch10-cpu](https://pypi.org/project/warpctc-pytorch10-cpu/)
First, save this script as `ctc_example.py`.
```py
import torch
from …
```

Install warp-ctc from PyPI

---

espnet/asr/asr_utils.py
espnet/asr/pytorch_backend/asr.py
espnet/bin/asr_train.py

the epoch num may not  be very large on large dataset training because of time limit. And average_checkpoints is very important to achieve lower CER. So I suspect that it's necessary to support save snapshot when iterations(10000,20000 etc.).
Any idea will be appreciate, thanks

support save snapshot by iteration

---

espnet/nets/pytorch_backend/rnn/attentions.py

`att_to_numpy()` function for AttCov and AttCovLoc takes only the last attention, which gives wrong visualization.
```Python
elif isinstance(att, (AttCov, AttCovLoc)):
att_ws = torch.stack([aw[-1] for aw in att_ws], dim=1).cpu().numpy()
```
This PR fixes it by taking the attention weight only at that time step.
```Python
elif isinstance(att, (AttCov, AttCovLoc)):
att_ws = torch.stack([aw[idx] for idx,aw in enumerate(att_ws)], dim=1).cpu().numpy()
```
Before this fix:
After this fix:

fixed att_to_numpy() function for AttCov, AttCovLoc

---

espnet/bin/asr_train.py
espnet/bin/lm_train.py
espnet/bin/mt_train.py
espnet/bin/tts_train.py

This PR might fix #404.
Default multiprocessing has a problem with not fork-safe libraries (e.g. MKL) and as a result the worker process is dead locked without any error massages.
Use 'spwan' for multiprocessing might be able to avoid this issue. 
See also https://github.com/pytorch/pytorch/issues/3619.

Use spawn in multiprocessing to fix #404

---

README.md
utils/synth_wav.sh

- Transformer
- Tacotron 2
- MoL WaveNet
Example usage:
```
cd egs/jsut/tts1
python -c "import pyopenjtalk;print(pyopenjtalk.g2p('こんにちは。私はグーグルアシスタントです。'))" > test.txt
../../../utils/synth_wav.sh --stage 0 --stop-stage 4 --models jsut.transformer.v1 --vocoder-models jsut.wavenet.mol.v1 --trans_type phn --fs 24000 --fmin 80 --fmax 7600 test.txt
```
- Universal MoL WaveNet
Example usage:
```
cd egs/libritts/tts1
echo "This is the demonstration of text-to-speech." > test.txt
../../../utils/synth_wav.sh --stage 0 --stop-stage 4 --models libritts.transformer.v1 --vocoder-models libritts.wavenet.mol.v1 --fs 24000 --input_wav /path/to/libritts/clean_test/237_134493_000003_000004.wav test.txt
```
Demo samples: https://drive.google.com/open?id=1QOo16aFGa5jN3Sxy1rREU9LS5QFm8jMV

Add pretrained models: JSUT and LibriTTS

---

espnet/asr/chainer_backend/asr.py
espnet/nets/asr_interface.py
espnet/nets/chainer_backend/asr_interface.py
espnet/nets/chainer_backend/e2e_asr.py
espnet/nets/chainer_backend/e2e_asr_transformer.py
espnet/nets/chainer_backend/transformer/training.py

I was wondering about the limitation of the training methods (Converter, updater...), because asr.py call it directly, so it is now rewritten in order to be call through the model. This is also helpful in case of a new e2e_foo.py because it only required to be declared in the model script and does not modify the asr.py script directly.

Indirect call  for training method [chainer]

---

espnet/bin/asr_train.py
espnet/bin/lm_train.py
espnet/bin/mt_train.py
espnet/bin/tts_train.py

This PR fixed #1266.
Setting 'spawn' multiple times in the process causes RuntimeError. To
avoid this issue we can use force=True but according to following issue,
it causes leaking of semephores. Therefore I decided to use try-except
to avoid this RuntimeError.
See also: https://github.com/pytorch/pytorch/issues/3492

Fix RuntimeError in setting spawn multiple times

---

ci/install.sh
tools/Makefile

This PR fixes https://circleci.com/gh/espnet/espnet/8163
Reference: https://superuser.com/questions/1402260/error-when-updating-conda-packages-removeerror-setuptools-is-a-dependency-of

Fix RemoveError: 'setuptools' is a dependency of conda

---

egs/vais1000/tts1/conf/tuning/train_fastspeech.v1.yaml
egs/vais1000/tts1/conf/tuning/train_fastspeech.v2.yaml
egs/vais1000/tts1/conf/tuning/train_pytorch_transformer.v1.yaml
espnet/bin/tts_train.py
espnet/tts/pytorch_backend/tts.py

In the case of a tiny dataset, the number of iterations in an epoch is small and then the evaluation interval is too short.
Too frequent evaluation is not necessary and it requires too much time.
This PR adds `eval-interval-epochs` to decide how frequent evaluation will be performed.
This enables us to avoid this issue by setting eval-interval-epochs to large number e.g. 10 or 100.

Add eval-interval-epochs for the tiny dataset

---

espnet/nets/pytorch_backend/e2e_tts_fastspeech.py
test/test_e2e_tts_fastspeech.py

This would be helpful when reduction_factor=1 is hard for training (e.g., LibriTTS). Also, this will allow quick iterations of experiments.

TTS: support reduction factor > 1 for FastSpeech

---

egs/libri_trans/asr1/RESULTS
egs/libri_trans/asr1/RESULTS.md
egs/libri_trans/asr1/conf/decode.yaml
egs/libri_trans/asr1/conf/specaug.yaml
egs/libri_trans/asr1/conf/train.yaml
egs/libri_trans/asr1/conf/tuning/decode_pytorch_transformer_bpe.yaml
egs/libri_trans/asr1/conf/tuning/decode_pytorch_transformer_char.yaml
egs/libri_trans/asr1/conf/tuning/decode_rnn_bpe.yaml
egs/libri_trans/asr1/conf/tuning/train_pytorch_transformer_bpe.yaml
egs/libri_trans/asr1/conf/tuning/train_pytorch_transformer_bpe_long.yaml
egs/libri_trans/asr1/conf/tuning/train_pytorch_transformer_char.yaml
egs/libri_trans/asr1/conf/tuning/train_rnn_bpe.yaml
egs/libri_trans/asr1/run.sh
utils/pack_model.sh

- Change RNN to Transformer
- Change character unit to BPE1k unit

Update libri_trans asr recipe

---

espnet/bin/asr_train.py
espnet/bin/lm_train.py
espnet/bin/mt_train.py
espnet/bin/tts_train.py

This PR fixes #1290 by removing `mp.set_start_method("spawn")`.

Remove set start method to fix #1290

---

egs/ljspeech/tts1/local/ob_eval/data_prep_for_asr.sh
egs/ljspeech/tts1/local/ob_eval/evaluate_cer.sh
egs/ljspeech/tts1/run.sh

This PR fixes a bug in the ASR eval for TTS in the case of `trans_type=phn`.
The ASR evaluation script assumed that the `text` is the character sequence but recently we support `trans_type=phn`. This causes the wrong evaluation results.
This PR fixes the issue by re-creating the `text`.

Fix ASR eval for TTS in the case of trans_type=phn

---

espnet/asr/pytorch_backend/asr.py

In the current codebase, evaluation with the validation set happens only when the epoch is even.
In other words, the checkpoints in the odd epoch are skipped.
This PR forces the model to turn the gradient accumulation off when the last minibatch in the current epoch is given.

Fix gradient accumlation

---

espnet/asr/pytorch_backend/asr.py

this should be `torch_load()` instead of `torch.load()`

fix rnnlm load bug

---

espnet/nets/pytorch_backend/e2e_tts_tacotron2.py

This PR fixed missing key error in Tacotron2.
In #1397, `Tacotron2Loss.bce_criterion.pos_weight` is registered as a parameter but old models did not include such a parameter. As a result, when loading an old model, it causes missing key errors. This PR fixes the above issue by using a pre-hook function.

Fix missing key error in Tacotron2

---

docker/build.sh
docker/prebuilt/devel/Dockerfile
docker/prebuilt/runtime/Dockerfile

Finish to build, test and uploading the containers with fixes for new installation.
@sw005320 , BTW I am wondering if there is gonna be a soon support for pytorch 1.1, 
CUDA 10.1 cannot be used with pytorch 1.0.1 so I cannot add this container yet.

Docker Updates

---

espnet/nets/pytorch_backend/e2e_tts_fastspeech.py
espnet/nets/pytorch_backend/e2e_tts_tacotron2.py
espnet/nets/pytorch_backend/fastspeech/duration_calculator.py
test/test_e2e_tts_fastspeech.py

This PR enables us to use Tacotron2 as a teacher of FastSpeech.
Our recent results show that Transformer has more errors compared to Tacotron2.
https://github.com/espnet/espnet/blob/7e30093deee53dc76ea99d01f8679d703f58d195/egs/ljspeech/tts1/RESULTS.md
Also, it is more straightforward to calculate the duration from the attention in the case of Tacotron2.
I think this makes it easy to apply filtering process for FastSpeech training.

Support Tacotron 2 as a teacher of FastSpeech

---

espnet2/tasks/abs_task.py

Now loss and statistics are divided by the number of gpus.

[ESPnet2] bug fix of multi gpu

---

egs/ami/asr1/run.sh

changed the condition of running local/ami_text_prep.sh from ` [ ! -d data/local/downloads ] ` to ` [ ! -d data/local/downloads/annotations ] ` since data/local/downloads has already been created in stage -1

fixed a small problem in run.sh

---

espnet/nets/pytorch_backend/e2e_asr_transformer.py
espnet/nets/pytorch_backend/e2e_tts_fastspeech.py
espnet/nets/pytorch_backend/e2e_tts_transformer.py
test/test_e2e_tts_transformer.py

This PR addresses the issue #1449.
TTS Transformer mask is changed as follows:
```python
ilens = [5, 3]
olens = []
tensor([[[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1]],
[[1, 1, 1, 0, 0],
[1, 1, 1, 0, 0],
[1, 1, 1, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0]]], dtype=torch.uint8)
tensor([[[1, 1, 1, 1, 1],
[1, 1, 1, 0, 0]]], dtype=torch.uint8)
```
```python
ilens = [4, 2]
olens = [5, 3]
tensor([[[1, 1, 1, 1],
[1, 1, 1, 1],
[1, 1, 1, 1],
[1, 1, 1, 1],
[1, 1, 1, 1]],
[[1, 1, 0, 0],
[1, 1, 0, 0],
[1, 1, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]]], dtype=torch.uint8)
tensor([[[1, 1, 1, 1],
[[1, 1, 0, 0]]], dtype=torch.uint8)
```
```python
olens = [5, 3]
tensor([[[1, 0, 0, 0, 0],
[1, 1, 0, 0, 0],
[1, 1, 1, 0, 0],
[1, 1, 1, 1, 0],
[1, 1, 1, 1, 1]],
[[1, 0, 0, 0, 0], …
```

Unify TTS Transformer mask with ASR Transformer

---

test/test_multi_spkrs.py

Modified the test_multi_spkr file for recognition. Previous fixed ground truth text comparison may cause assertions due to various reasons, which was highly dependent on initialization, network inner computation and so on. Now only check whether the recognition function works without interrupt and ensure the output is a sequence of characters.

Fix test_multi_spkr

---

espnet2/bin/pack.py
espnet2/utils/pack_funcs.py
test/espnet2/utils/test_pack_funcs.py

I implemented utilities for packing a model file with the other related files.
These tools are used for uploading model files to cloud storage and 
also provides the interface for inputting pre-trained model to decoding tool.
```bash
python -m espnet2.bin.pack asr \
--asr_train_config.yaml exp/asr_train/config.yaml \
--lm_train_config.yaml exp/lm_train/config.yaml\
--asr_model_file.pth exp/asr_train/model.pth \
--lm_file.pth exp/lm_train/model.pth \
--option data/local/bpemodel --option data/cmvn.npz \
--outpath out.tgz
```
```
packed/meta.yaml
packed/asr_train_config.yaml
packed/lm_train_config.yaml
packed/asr_model_file.pth
packed/lm_file.pth
packed/option/bpemodel
packed/option/cmvn.npz
```
This tool is aware of the yaml file and if the yamls has a value pointing to the input file, …

[ESPnet2] Pack and Unpack model

---

egs2/TEMPLATE/asr1/asr.sh
egs2/TEMPLATE/tts1/tts.sh

The number of jobs for collect_stats mode should be selected from the minimum number among --nj, the number of lines of train.scp, and the number of lines of dev.scp.

[ESPnet2] Bug fix of splitting files for collect_stats mode

---

egs2/TEMPLATE/asr1/asr.sh
egs2/TEMPLATE/tts1/tts.sh

(#1504)
CSJ, CHIME5, and many tasks distributes "unsegmented" wav files in raw corpus, so we need to split them some where.
Espnet2 generates segmented wav files using "segments" if feats_type=raw,  while espnet1 and kaldi creates it as fbank.

[ESPnet2] Support "segments" file in asr.sh and tts.sh

---

egs/librispeech/asr1/RESULTS.md

By looking at the cotent in the snippets, I think the original intention is to use the Markdown table.

Use Markdown table instead for WER results

---

espnet2/asr/encoder/rnn_encoder.py
espnet2/asr/encoder/vgg_rnn_encoder.py

(Cherry pick from #1522)
GRU is always used if bidirectional mode.

[ESPnet2] fix rnn_type when bidirectional is used

---

egs2/TEMPLATE/asr1/pyscripts/audio/format_wav_scp.py

load_scp_sequential() is faster than load_scp for segmentation.
@YosukeHiguchi @ftshijt  I think  the stage of formart_wav_scp.py took much times. Sorry for wasting your resource.

[ESPnet2] Use load_scp_sequential in formart_wav_scp.py

---

egs2/csj/asr1/run.sh

@YosukeHiguchi   "$@" is different from "$*".

[ESPNet2] Minor fix for CSJ recipe

---

egs2/TEMPLATE/asr1/scripts/audio/format_wav_scp.sh

The maximum number of split equals to the number of lines of segments file.

[ESPnet2] Fix nj of scripts/audio/format_wav_scp.sh

---

espnet2/layers/stft.py

FIx for the case of nfft != win_length
https://github.com/espnet/espnet/pull/1529#issuecomment-585397145

[ESPnet2] Bug fix of stft.py

---

espnet/asr/asr_utils.py

1. have word `snapshot` in experiment path (e.g. ~/somepath/snapshot/exp/tag)
2. run experiment by resuming a snapshot from other place
Espnet throws ```KeyError: 'model'``` at ```espnet/asr/asr_utils:510```
```model_state_dict = torch.load(path, map_location=lambda storage, loc: storage)['model']```
I figured out it was because at ```espnet/asr/asr_utils:509```, espnet test whether  a path is model or snapshot by checking the entire path, but I have word 'snapshot' in experiment directory though the basename of path is actually ```model.acc.best```.
It can be fixed by change the test condition to testing the basename of model/snapshot path

fix snapshot/model test condition

---

README.md

Recently I support MelGAN in https://github.com/kan-bayashi/ParallelWaveGAN.
This PR adds the link to the pretrained MelGAN and support it in demo notebook.

Add MelGAN pretrained model and support in demo notebook

---

espnet2/bin/launch.py

Now environment variables are not inherited from parents process: e.g. NCCL_SOCKET_IFNAME

[ESPnet2] Fix launch.py for slurm

---

egs/ru_open_stt/asr1/run.sh

if "tag" is setted, since there is no variable "expname" before line 147.
so I copy the setting from librispeech

ru_open_stt recipe bug fix

---

espnet2/iterators/abs_iter_factory.py
espnet2/iterators/chunk_iter_factory.py
espnet2/iterators/sequence_iter_factory.py
espnet2/tasks/abs_task.py
espnet2/tasks/asr.py
espnet2/tasks/lm.py
espnet2/tasks/tts.py
espnet2/train/trainer.py
test/espnet2/iterators/test_chunk_iter_factory.py
test/espnet2/iterators/test_sequence_iter_factory.py

This is preliminary PR for not seq2seq task for ESPnet2.
Now our data-iterator can  generate only a batch of sequences, so it can support only some task which inputs variable length sequence. I'd like to extend espnet for more general task, e.g. speech enhancement network often uses "fixed length to same length", and speaker recognition task typically uses a DNN of "fixed length to a vector" at training.
I implemented `ChunkIterFactory` in this PR. This iterator creates fixed length segments, which I refer it as chunk, cut from a sequence.
- Chunks are equal length for a sequence and they have half of length overlap by default like STFT. The length of chunk and shift length are parameters.
- Multiple chunk lengths can be also specified and randomly pickup a value from them for each …

[ESPnet2] Implement chunk iterator

---

README.md
egs/wsj/asr1/RESULTS.md

Previous results with builtin CTC and PyTorch 1.3 were mistakenly obtained from the `eval92_5k` set. Now I update the results on the standard dev and eval sets generated by the recipe.
This is related to https://github.com/espnet/espnet/pull/1421,  https://github.com/espnet/espnet/pull/1527, https://github.com/espnet/espnet/pull/1537 and https://github.com/espnet/espnet/issues/1643.

correct results with builtin CTC and PyTorch 1.3 in WSJ recipe

---

docker/build.sh
docker/prebuilt/local/Dockerfile

This is a fix for #1619.
The CUDA_VER variable was not passing to docker build so It generates the cupy installation error.

Docker local updates

---

egs/vcc20/README.md

The organizers decided to provide another _reference set_ for participants. This PR updates the link to the converted reference set in the README.

[VCC2020 baseline] Extra reference set

---

espnet2/iterators/chunk_iter_factory.py
espnet2/iterators/sequence_iter_factory.py
espnet2/main_funcs/collect_stats.py
espnet2/tasks/abs_task.py
espnet2/train/trainer.py

Following up #1608
- Fix bugs:
- If  `--chunk_length` has multiple values e.g. "--chunk_length 100,110,140", process was aborted.
- Fix for Multi GPU mode
- Avoiding to use `len(iterator)`  for chunk iterator,  
- `len(iterator)`  can be derived for chunk iterator because chunks are dynamically created and we can get the number of chunks before generating.
- ESPnet2 uses `len(iterator)` to determine the default value of `--log_interval`, so simply replace it to 100 if `__len__` is not implemented.
- Refactoring for distributed training for chunk iterators
- Previous behavior:  All processes loads same utterances and create chunks from them, then divide mini-batch into processes.
- The data loading can't be parallelized, therefore this implementation is bad for scalabality.
- New behavior: …

Fix chunk iterator and refactoring for distributed training

---

espnet2/bin/launch.py

Follow up #1713 
New line char is unnecessary

Fix error log for espnet2/bin/launch.py

---

espnet2/main_funcs/average_nbest_models.py

The averaged model shouldn't be created  if --keep_nbest_models=1. Instead of it, create a symbolic link to the the best epoch model.

Not to create the averaged model if --keep_nbest_models=1

---

espnet2/bin/launch.py

Kaldi's run.pl, and etc. overwrite the log file regardless of the options. This is hard coding, so we can't change it to append mode. This issue might be addressed in Kaldi, but I won't discuss about it.
In espnet2 we always submit training jobs via launch.py for distributed training, so I implemented log-rotation in launch.py.

Log  rotation for launch.py

---

espnet2/asr/ctc.py

The deterministic mode of CuDNN should be controlled by `--cudnn_deterministic` option.

Disable CUDNN deterministic for CTC:   espnet2/asr/ctc.py

---

espnet2/tasks/abs_task.py

We discussed in #1710 and decided to turn  cudnn deterministic mode on by default. (This is the default behavior of espnet1).
Note that the performance might be slower in some cases, but in my benchmark that is enough small.

Change cudnn deterministic mode to default

---

espnet2/tasks/abs_task.py
espnet2/utils/types.py
test/espnet2/utils/test_types.py

- Change `action="append"` -> `nargs="+"`
-  `action="append"`  appends the given arg to the default list
-  `nargs="+"` remove the default. This is expected behavior
- Fix problem when best_model_criterions is given by config file:
- The interval behavior of configargpase is that:
1. Parse the value from yaml to Python object: e.g. [a, b] -> ['a', 'b']
2. Change it to text: "['a', 'b']"
3. Give it to type function which is given for add_arguments():  
- e.g. ---add_arguments("--foo",type=int): --foo 3 -> return int("3")
4. The value derived from the above step is the exact attribute in the parsed objects.

Fix --best_model_criterions

---

espnet2/bin/tts_inference.py

GPU mode doesn't work now for tts_inference because the data is not transferred to gpu device. I forgot it.

Fix gpu mode for tts_inference.py

---

espnet2/asr/espnet_model.py
espnet2/asr/specaug/abs_specaug.py
espnet2/asr/specaug/specaug.py
espnet2/layers/global_mvn.py
espnet2/layers/mask_along_axis.py
espnet2/layers/time_warp.py
espnet2/layers/utterance_mvn.py
espnet2/tasks/asr.py
test/espnet2/asr/specaug/test_specaug.py
test/espnet2/layers/test_mask_along_axis.py
test/espnet2/layers/test_time_warp.py

- Implement Batch  Specaug in PyTorch
- Backwardable
- This feature can be enabled by adding `--specaug specaug` for `train_asr.py`
- Now our ASR model includes `STFT` -> (`WPE` -> `MVDR`)  -> `Mel-Fbank` -> `SpecAug` -> `Encoder` -> `Decoder`
- The part of `SpecAug` has also an abstracted class, so we can replace it to another for future development.
- The computation cost seems negligible in my environment even if using TimeWarp.
- We might need `TimeAug` ( -> `STFT` -> ...) module in the future?
- RIR-convolution and noise-injection are the main targets.
- I didn't evaluate this module in any recipes yet. 
- Specaug seems efficient for large corpus?, so I hesitated to test it. 
Now is good time to release ESPnet2 if all my current PRs are merged (except for DNN-HMM)!

Implement SpecAug for ESPnet2

---

espnet2/train/reporter.py
espnet2/train/trainer.py
test/espnet2/train/test_reporter.py

- Fix the calculation for stats in SubReporter: Now the number of samples is incorrect
- Implement SubReporter.measure_time() and SubReporter.measure_iter_time()
- Show iter_time, forward_time, optim_step_time, and backward_time
```
[kamo-desktop] 2020-03-29 18:04:38,450 (trainer:452) INFO: 10epoch:train:1-10batch: iter_time=0.007, forward_time=0.156, loss=41.992, loss_att=22.768, loss_ctc=61.217, acc=0.682, backward_time=0.088, optim_step_time=0.007, lr_0=1.000, train_time=0.471
```

Fix SubReporter

---

espnet/tts/pytorch_backend/tts.py

Fix issue #1753.
`data` is not sorted by the input length while the input batch is sorted during converting to the batch from data.
So the following part did not work correctly.
https://github.com/espnet/espnet/blob/95ecf5f15fe2577ec649363e9700cd5721885c02/espnet/asr/asr_utils.py#L190-L202
The cropping size bug when reduction_factor > 1 is also fixed.

Fix an attention plot bug in TTS

---

egs/ljspeech/tts2/run.sh

in local/data_prep.sh
if [ $# != 3 ]; then
echo "Usage: $0 <db> <data_dir> <trans_type>"
exit 1
fi
char or phn should be added in the command line (seems like bug)

missing argument for local/data_prep.sh added

---

egs/ljspeech/tts2/conf/train_pytorch_tacotron2+cbhg.yaml

`forward-ta` should be changed to `forward_ta`
group.add_argument('--atype', default="location", type=str,
choices=["forward_ta", "forward", "location"],

typo fixed for attention type

---

ci/install.sh
egs/ljspeech/tts1/conf/tuning/decode_fastspeech.yaml
espnet/bin/tts_decode.py
espnet/nets/pytorch_backend/e2e_tts_fastspeech.py
espnet/nets/pytorch_backend/fastspeech/length_regulator.py
test/test_e2e_tts_fastspeech.py

This PR supports the speed control in FastSpeech decoding.
Example:
alpha = 0.5
https://drive.google.com/open?id=1kFROXQxX0oGmJhx35-3uarLi_Dt2gvxL
alpha = 1.5
https://drive.google.com/open?id=1zAmqvE_LsTNvwtCI_B_hl6oxkYPU7FSy
Related: #1404 #1708

Support the speed control in FastSpeech decoding

---

.github/workflows/pythonpublish.yml
README.md
espnet/st/__init__.py
espnet/tts/__init__.py
setup.py

- I registered espnet to pypi server. Now we can do pip install espnet.
- Pypi uploading runs on tag from now.
- The dependencies to direct URL, e.g. git+https://github.com/espnet/espnet_tts_frontend, can't be used for pypi server, so I also registered the dependencies to pypi. 
- This is one of the reasons why I hesitated to use pypi server.

modified for registration to pypi

---

espnet/transform/cmvn.py

The reverse operation order needs to be divide -> subtract (rather than subtract -> divide) w.r.t normalization operation order add + multiply

fix reverse option for cmvn

---

setup.py

sentencepiece==0.1.90 breaks the backward compatibility.

avoid sentencepiece==0.1.90

---

.github/workflows/ci.yaml

I found `pip install` takes [5min in Actions](https://github.com/espnet/espnet/runs/656446296?check_suite_focus=true). So I suggest [actions/cache](https://github.com/actions/cache/blob/master/examples.md#python---pip) for skipping it.

Use cache in actions

---

espnet2/bin/asr_inference.py

I found a fatal bug.
The model is not changed to eval mode when inference. BeamSearch.eval() is invoked, so the decoder part is set on eval mode, but the encoder part is still train mode, i.e. dropout is used for the encoder part.

Fix bug of espnet2 asr_inference.py

---

doc/installation.md

- `warp-transducer` installation was failed in our environment
- Adding `CPATH` solved this issue.

Update installation manual

---

ci/doc.sh
doc/module2rst.py

Currently, documents in `espnet2` are not rendered because `ci/doc.sh` does not support it. So I added it. You can see how it will be in https://karita.xyz/espnet

Add espnet2 in ci/doc.sh

---

espnet/tts/pytorch_backend/tts.py

Hi, @kan-bayashi, @b-flo 
After we've wrapped model in `nn.DataParallel`, the name of the parameter is prepended with '`module.`'
Thanks,

Fix freezing modules (when using  multi-gpu)

---

.github/workflows/ci.yaml

Recently, the required time for CI is increasing.
We might want to skip CI sometimes.
This PR might help such a situation.
If we add `[ci skip]` in the commit message, CI will be skipped.
But unfortunately, this is only available for the event `push`.
Reference:
- https://qiita.com/peaceiris/items/28e302996ccf04551434
- https://srz-zumix.blogspot.com/2019/10/github-actions-ci-skip.html

Support CI skip in gihub action

---

espnet/nets/pytorch_backend/e2e_mt_transformer.py
espnet/nets/pytorch_backend/e2e_st_transformer.py

In the current implementation, BLEU scores are calculated at each forward pass.
This PR modifies it so that BLEU scores are calculated in the validation only for faster training.
Also, WER calculation is turned off in the training mode when auxiliary ASR task is incorpolated.

Turn off BLEU calculation during training

---

setup.py

librosa is incompatible with numba=0.50 now, so I pinned it to 0.49 as workaround.

Pin numba=0.49

---

egs2/TEMPLATE/asr1/asr.sh
egs2/TEMPLATE/tts1/tts.sh
espnet2/bin/asr_inference.py
espnet2/bin/lm_calc_perplexity.py
espnet2/bin/split_scps.py
espnet2/bin/tts_inference.py
espnet2/fileio/read_text.py
espnet2/iterators/abs_iter_factory.py
espnet2/iterators/multiple_iter_factory.py
espnet2/tasks/abs_task.py
espnet2/train/dataset.py
espnet2/train/iterable_dataset.py
test/espnet2/iterators/test_multiple_iter_factory.py
test/espnet2/train/test_iterable_dataset.py

It's hard to handle large coprus, such as over 10,000,000 samples now because the number of samples in scp files directly impacts the memory footprint.
I prepared two ways to handle this problem.
1. IterableDataset
This class is not used training, but used for calc_stats and inference mode.
Current `ESPnetDataset` is dict-type:
```python
data = dataset["uttid"]
```
I newly implemented iterable type dataset: `IterableESPnetDataset`
```python
for data in dataset:
...
```
Text files are read line-by-line, so we no longer consume memory.
Note that iterable dataset for pytorch DataLoader is supported from pytorch=1.2, so if pytorch<=1.1, it falls back to the conventional ESPnetDataset.
2. Multiple iterator
IterableDataset can't be used for training because it can't shuffle the samples order.
I …

Solve memory issue with super large corpus training

---

espnet2/tasks/lm.py

Non linguistic symbols text is not used for lm model now. This will affect the result slightly.

fix bug of lm.py

---

egs2/TEMPLATE/asr1/asr.sh
egs2/TEMPLATE/asr1/scripts/utils/remove_longshortdata.sh
egs2/TEMPLATE/tts1/tts.sh
egs2/voxforge/asr1/local/data.sh

I added an option for removing long wave data in espnet2 template recipe.
Note that
- Removing short data is already existing in the recipe.
- We can't use `remove_longshortdata.sh` in espnet2 because it assumes exracted feature, but espnet2 recommend on-the-fly feature extraction. 
- Removing long/short text is not applied in the template recipe yet. This is difficult, unlike wave data, because of on-the-fly text processing.
- Instead of it, just removing empty text here.

Remove long wave in template recipe

---

espnet2/bin/aggregate_stats_dirs.py
espnet2/train/iterable_dataset.py
test/espnet2/train/test_iterable_dataset.py

Now the data loader generates duplicated keys if num_workers>=1.
See about Iterable dataset: 
https://pytorch.org/docs/stable/data.html#torch.utils.data.IterableDataset

Fix bug of iterable dataset when num_workers>=1

---

tools/Makefile

@kamo-naoyuki I found `cupy.done` is not included in `make python`.
This causes an error in `make check_install`.
Is it OK to add or are there any reason?

Add cupy.done in make python

---

espnet2/asr/frontend/default.py
espnet2/layers/log_mel.py
espnet2/layers/stft.py
espnet2/tts/feats_extract/log_mel_fbank.py
espnet2/tts/feats_extract/log_spectrogram.py
test/espnet2/asr/frontend/test_frontend.py
test/espnet2/tts/feats_extract/test_log_mel_fbank.py
test/espnet2/tts/feats_extract/test_log_spectrogram.py

I fixed feature extractor of TTS for espnet2 for compatibility.
- Use hann window in stft layer: The default of torch.stft is all 1 window. I forgot it, sorry...  **This changing also affects ASR results**.
- Change to log_e -> log_10
Note that we use different definition for log-spec between TTS and ASR now.
- ESPnet2
- TTS: log_10(abs(torch.stft))
- ASR: log_e(power(torch.stft))
- ESPnet1
- TTS: log_10(abs(librosa.stft))
- ASR: From Kaldi: log_e(power(kaldi-stft))
I found that the default behaviour of torch.stft is almost compatible with librosa.stft, while scipy.signal.stft is different.
I also added a compatibility testing between espnet2 and espnet1 feature for TTS. Now I assure you that feats_type=raw and feats_type=fbank in TTS recipe uses **almost** same feature (numerical error …

Fix feature extractor of TTS for compatibility

---

egs2/TEMPLATE/asr1/asr.sh
egs2/TEMPLATE/tts1/tts.sh
espnet2/fileio/read_text.py
espnet2/train/collate_fn.py
test/espnet2/fileio/test_read_text.py

#2105
I changed the espnet2 recipe not to remove short/long utterances for eval_sets.
I also check that this recipe can work to the last stage with empty text.

Not removing short/long utterances for eval_sets

---

setup.py
utils/download_from_google_drive.sh
utils/gdown.pl

#2071 
Use https://github.com/circulosmeos/gdown.pl. It is distributed under GPL 3, so I guess it is okay to just copy to `utils/`?

Fix error when downloading large files using `download_from_google_drive.sh`

---

espnet2/fileio/read_text.py
espnet2/train/dataset.py

We found `read_2column_text()` and `load_num_sequence_text` is very slow now. They re used for reading `text` and `*_shape.txt`. @Cescfangs may also know this problem?
I deleted some bottlenecks, but it might be still slow.

Make read_text faster

---

espnet/nets/beam_search.py

- added more decoding information for beam search api v2, which provides more analysis for the recognized results.
- bugfix (partial score is not accumulated)
- fix typo
The output looks like as follows:
```
2020-07-01 00:58:40,620 (beam_search:353) INFO: decoder input length: 22
2020-07-01 00:58:40,621 (beam_search:354) INFO: max output length: 22
2020-07-01 00:58:40,621 (beam_search:355) INFO: min output length: 0
2020-07-01 00:58:43,450 (beam_search:367) INFO: end detected at 13
2020-07-01 00:58:43,450 (beam_search:391) INFO: -11.98 * 0.5 =  -5.99 for decoder
2020-07-01 00:58:43,450 (beam_search:391) INFO:  -6.49 * 1.0 =  -6.49 for lm
2020-07-01 00:58:43,450 (beam_search:391) INFO:  -9.37 * 0.5 =  -4.69 for ctc
2020-07-01 00:58:43,450 (beam_search:392) INFO: total log probability: …
```

added more beam search info

---

espnet2/bin/tts_inference.py
espnet2/tasks/tts.py
espnet2/tts/espnet_model.py
espnet2/tts/tacotron2.py
espnet2/tts/transformer.py
test/espnet2/tts/test_tacotron2.py
test/espnet2/tts/test_transformer.py

This PR supports TTS-Transformer in ESPnet2.
- Add `espnet2/tts/transformer.py`
- Remove deprecated options from `espnet2/tts/tacotron2.py`
- Add options available in transformer for tacotron2
- Add test code for epsnet2 tts models.

Support TTS-Transformer in ESPnet2

---

egs/wsj/asr1/local/filtering_samples.py

Fix the bug in current wsj recipe when using transformer configuration, **local/filtering_samples.py** raises an attribute error as below.
> AttributeError: 'Namespace' object has no attribute 'etype'

Fix a bug in espnet wsj recipe.

---

espnet2/bin/tokenize_text.py

I fixed the bug reported in #2155 and refactor for readability.
@Cescfangs Would you check this PR?

Fix bug of when espnet2/bin/tokenize_text.py --cutoff or --vocabulary_size is used

---

egs2/TEMPLATE/asr1/asr.sh
egs2/TEMPLATE/tts1/tts.sh
espnet2/bin/pack.py
espnet2/main_funcs/pack_funcs.py
test/espnet2/main_funcs/test_pack_funcs.py

I'm planning using zenodo to upload pretrained model instead google drive. As the first step for it, I changed packed file of espnet2 to zip format since zenodo doesn't support previewing for the other format now.
https://github.com/zenodo/zenodo/issues/557

Change packed file of espnet2 to zip format

---

espnet2/bin/asr_inference.py
espnet2/bin/lm_calc_perplexity.py
espnet2/bin/tts_inference.py
espnet2/tasks/abs_task.py
espnet2/utils/config_argparse.py
espnet2/utils/nested_dict_action.py
test/espnet2/utils/test_config_argparse.py

- Now the configuration from config file is overwritten by argument.
```bash
% python3 -m espnet2.bin.tts_train --print_config --config conf/tuning/train_gst_tacotron2.yaml --tts_conf bce_pos_weight=10.0
```
- The type checking of configargparse is likely to cause some bugs. I'm sick of it.
I decided discarding configargparse from espnet2 and I implemented more simple configargparse in espnet2.utils. New argparse is lack of  some features which original configargparse has.
- Config file is used to change **default** values for `ArgumentParser`.
```python
parser.set_defaults(**from_config_file)
```
- Not supporting multiple config files and automatically adding "--config" as an option.
```bash
python asr_train.py --config config.yaml
```
- Not supporting any formats other than yaml
- Not …

Implement configargparse in espnet2

---

test_utils/integration_test_ctc_align_wav.bats
utils/ctc_align_wav.sh

The size of the small model is 15MB. I still use the google drive to store the model. I'm not sure whether there is still a problem when too many download trials.

fix integration_test_ctc_align_wav.bats with a small model

---

ci/test_integration.sh
egs2/TEMPLATE/asr1/asr.sh
egs2/TEMPLATE/tts1/tts.sh
egs2/aishell/asr1/run.sh
egs2/ami/asr1/run.sh
egs2/an4/asr1/run.sh
egs2/an4/tts1/run.sh
egs2/babel/asr1/run.sh
egs2/chime4/asr1/run.sh
egs2/commonvoice/asr1/run.sh
egs2/csj/asr1/run.sh
egs2/csmsc/tts1/run.sh
egs2/dirha_wsj/asr1/run.sh
egs2/how2/asr1/run.sh
egs2/jsut/asr1/run.sh
egs2/jsut/tts1/run.sh
egs2/librispeech/asr1/run.sh
egs2/ljspeech/tts1/run.sh
egs2/mini_an4/asr1/run.sh
egs2/mini_an4/tts1/run.sh
egs2/vctk/tts1/run.sh
egs2/vivos/asr1/run.sh
egs2/voxforge/asr1/run.sh
egs2/wsj/asr1/run.sh
egs2/yesno/asr1/run.sh
espnet2/bin/pack.py
espnet2/bin/zenodo_upload.py
espnet2/main_funcs/pack_funcs.py

I implemented a script to upload pretrained model to zenodo. This is an example: https://sandbox.zenodo.org/record/646767#.Xwqq6577TOQ
I also added --asr_exp and --lm_exp option in asr.sh and --tts_exp in tts.sh. It specifies the path of expdir directly.
```bash
unzip ${packed_model}
exp=$(basename ${packed_model} .zip)
./run.sh --skip_data_prep false --skip_train true --asr_exp ${exp}/asr --decode_asr_model pretrain.pth --lm_exp ${exp}/lm --decode_lm pretrain.pth
```

Implement espnet2.bin.zenodo_upload

---

espnet2/bin/tts_inference.py

Fixed a bug in tts_inference when `feats_extract is None`.

Fix `tts_inference` when `feats_extract` is None

---

ci/test_integration.sh
egs/mini_an4/asr1/conf/train_conformer_pure_ctc.yaml
espnet/asr/asr_utils.py
espnet/asr/pytorch_backend/asr.py
espnet/nets/pytorch_backend/e2e_asr.py
espnet/nets/pytorch_backend/e2e_asr_mulenc.py
espnet/nets/pytorch_backend/e2e_asr_transducer.py
espnet/nets/pytorch_backend/e2e_asr_transformer.py
espnet/nets/pytorch_backend/e2e_mt.py
espnet/nets/pytorch_backend/e2e_mt_transformer.py
espnet/nets/pytorch_backend/e2e_st.py
espnet/nets/pytorch_backend/e2e_st_transformer.py
espnet/nets/pytorch_backend/e2e_tts_transformer.py
espnet/nets/pytorch_backend/transformer/plot.py

I fixed a bug in attention plotting for non RNN-T models (see #2082 ).
Also, I slightly modified token visualization in MHA.
This is due to sos and eos tokens.
I also considered subsampling in CNN layers for visualization (divided by a factor of 4).
Then, I happened to find that the current plotting is conducted in the training mode (fixed to the eval mode).
Furthermore, the sort order of inputs for attention calculation and data which is registered in `PlotAttentionReport` is not matched.
This was problematic when truncating the lengths of attention weights for the exact padding during visualization.

Fix bug in attention plotting

---

utils/dump_pcm.sh

Without a space there, an error could happen when the variable **opts** is appended with **--format wav** because there's no space in between **--write-num-frames=xxx** and **--format wav**.

Append a missing space in cmd-line args in utils/dump_pcm.sh

---

espnet/asr/asr_utils.py
espnet/asr/pytorch_backend/asr.py
espnet/bin/asr_train.py
espnet/bin/st_train.py
espnet/nets/asr_interface.py
espnet/nets/pytorch_backend/ctc.py
espnet/nets/pytorch_backend/e2e_asr.py
espnet/nets/pytorch_backend/e2e_asr_mulenc.py
espnet/nets/pytorch_backend/e2e_asr_transformer.py
espnet/nets/pytorch_backend/e2e_st.py
espnet/nets/pytorch_backend/e2e_st_transformer.py
espnet/st/pytorch_backend/st.py
espnet/utils/training/tensorboard_logger.py
test/test_e2e_asr.py
test/test_e2e_asr_conformer.py
test/test_e2e_asr_mulenc.py
test/test_e2e_asr_transformer.py
test/test_e2e_st.py
test/test_e2e_st_transformer.py

This PR adds CTC posterior visualization during training as in attention weight plotting.
CTC visualization in the auxiliary ASR task during ST model training is also supported.
An example is as follows:

CTC posterior visualization during training

---

tools/Makefile
tools/check_install.py

Fix #2229 
cupy==6.0.0 doesn't support cuda=10.2 or later version.
I also added --no-cupy option to check_install.py

Update Makefile to disable cupy for cuda=10.2 or later

---

egs2/TEMPLATE/asr1/asr.sh
egs2/TEMPLATE/enh1/enh.sh
egs2/TEMPLATE/tts1/tts.sh

Fix #2252 
SGE jobname can't include "/".  I can't understand why SGE has such stupid restriction.
Torque/PBS and slurm support it.

Workaround for SGE jobname issue

---

.circleci/config.yml
.travis.yml
ci/test_integration.sh
egs/mini_an4/asr1/run.sh
egs/mini_an4/asr_mix1/run.sh
egs/mini_an4/mt1/run.sh
egs/mini_an4/st1/run.sh
egs/mini_an4/tts1/run.sh
test_utils/integration_test_ctc_align_wav.bats
utils/ctc_align_wav.sh

I replaced `python xxx.py` with `coverage run --append -m espnet.bin.xxx` for including integration tests into coverage stats (see [coverage.py usage](https://coverage.readthedocs.io/en/coverage-5.2.1/cmd.html#cmd-run)). The reason why I used `-m xxx` instead of `xxx.py` is that coverage.py cannot find non-local files.
I also disabled some codecov lines in CI without integration tests because their reports are different from (i.e. fewer than) ones with integration tests.

Take integration tests into coverage

---

espnet2/iterators/sequence_iter_factory.py
test/espnet2/iterators/test_sequence_iter_factory.py

- Before: If num_iters_per_epoch than the number of batches in the corpus, num_iters_per_epoch is ignored.
```python
if num_iters_per_epoch> len(batches):
num_iters_per_epoch = len(batches)
```
- After: Support if

Support larger num_iters_per_epoch than the number of batches in small corpus

---

tools/Makefile

cupy-cuda*=6.0.0 for python>=3.8 is not provided.

Not to install cupy-cuda* for python>=3.8

---

doc/espnet2_training_option.md
espnet2/asr/espnet_model.py
espnet2/tasks/abs_task.py
espnet2/train/trainer.py
espnet2/tts/espnet_model.py

- Support torch.cuda.amp, which is implemented from torch=1.6.0
- We can use it with `--use_amp True`
- Remove apex.amp (=We can't use amp if torch<1.6)
- `--train_dtype O0, O1, O2, O3` are removed.
- Disable autocast of the feature extraction part in asr model and tts model.
- Probably, we should enable it if the feature extractor part has learnable part, but they don't have now.
- I keep enh model as it is because I don't know how we should.
Note that RNN model doesn't work with amp now ( pytorch/pytorch#36428 )
@ShigekiKarita or @kan-bayashi 
Could you cross check this implementation? https://pytorch.org/docs/stable/notes/amp_examples.html#amp-examples

Support torch native automatic mixed precision for espnet2

---

espnet2/main_funcs/average_nbest_models.py
test/espnet2/main_funcs/test_average_nbest_models.py

BatchNorm has integer type state and now average_nbest_models() tries to average it.
PyTorch<1.6 can divide integer type, but 1.6 deals it as an error, so we got the error.
I modified it to accumulated parameters, not averaging, if data is integer type. I also added a test code for average_nbest_models().

Fix average_nbest_models for pytorch=1.6

---

egs2/TEMPLATE/asr1/asr.sh
egs2/TEMPLATE/asr1/pyscripts/utils/print_args.py
egs2/TEMPLATE/asr1/scripts/utils/show_asr_result.sh
egs2/TEMPLATE/enh1/enh.sh
egs2/TEMPLATE/tts1/tts.sh

- Motivation:
Sometimes, run.sh stops at the middle of stage, especially at training stage. I don't always keep the command to execute run.sh, so it's hard to remember the command because we normally add very long arguments to run.sh. e.g. `run.sh --train_args "--model_conf ctc_weight=0.3" ...` 
- This PR:
I modified the template recipes to generate `run.sh` in each experiment directory, e.g. `asr_exp`/run.sh. It records the command as it is with the corresponding stage, so we can resume the process from each stage with running this script.
Note that this script also accepts more command line arguments. `"$@"`, e.g. 
`asr_exp/run.sh --stage 10`
I also changed the name of decoding directory for ASR.
`inference_${dset}_${inference_tag}` -> `${inference_tag}/${dset}` for this modification. …

Generate run.sh in the experiment dir for resuming

---

espnet2/tasks/abs_task.py

Now config.yaml is written by all processes when distributed training and if the writing operation happens as the same time, it causes wrong writing, so I disabled it if rank!=0.

Not to save config.yaml if rank!=0

---

tools/Makefile
tools/check_pytorch_cuda_compatibility.py

Workaround #2302
Many people use cuda10.2 now, but pytorch1.4, which is current our default, may not support it.

Add checking for pytorch-cuda compatibility in Makefile

---

egs2/TEMPLATE/asr1/asr.sh

- Before: --lm_exp can overwrite the name specified for lm_tag, mainly for only performing inference, but inference_tag refers lm_tag.
- After: Inference_tag refers lm_exp

use lm_exp instead of lm_tag for inference_tag

---

espnet2/main_funcs/average_nbest_models.py
espnet2/tasks/abs_task.py
test/espnet2/main_funcs/test_average_nbest_models.py

Now `--keep_nbest_models` accepts multiple arguments.
```sh
... --keep_nbest_models 3 10 15
```
If multiple arguments are specified, `phase.criterion.ave.pth` is a symlink to the maximum number in the specified numbers: e.g. 15 in this case.

Support multiple nbest models

---

egs2/TEMPLATE/asr1/asr.sh

--asr_exp option is an option to give the name of experiment directory ignoring --asr_tag, so it shouldn't be modified by the other parameters.

Not to add _sp to $asr_exp if --asr_exp option is specified

---

tools/check_install.py

ImportError doesn't always mean the module is not found, e.g. Some dependencies isn't found or the package itself is broken.
We must  always check why it can't be imported. Don't forget. this is very important.

Show raw error message when failed to import packages

---

egs/wsj/asr1/local/wsj_data_prep.sh

I addded prepare_lm flag in wsj_data_prep.sh to disable preparation for ngram because it requires lrstlm.

Disable preparation for lm in wsj recipe

---

doc/installation.md
tools/setup_anaconda.sh
tools/setup_python.sh
tools/setup_venv.sh

Now setup_python.sh is two part: setup venv or setup System python environment. I divided it into two scripts.
I also changed it to set `PYTHONUSERBASE` by default not to use `~/.local` for pip user installation mode.

Devide setup_python.sh into setup_venv.sh and setup_python.sh

---

egs2/TEMPLATE/asr1/scripts/utils/show_asr_result.sh

Bug fix of show_asr_result.sh.
-H options show the file name if only one argument is given.

Add grep -H option

---

ci/install.sh
egs/tedlium2/align1/path.sh
setup.py

Now ctc-segmentation is correctly installed via pip.
This PR adds ctc-segmentation in requirements.
Related: 
- https://github.com/espnet/espnet/issues/2365
- https://github.com/lumaku/ctc-segmentation/pull/2

Revert ctc seg installation

---

espnet/nets/pytorch_backend/e2e_asr_transformer.py

There is a bug on Transformer with ctc_weight == 1.0 that
the first character is removed during token-to-str conversion.
It occurs as asr_utils.parse_hypothesis() assumes the first token is sos
and removes it, but CTC out does not have sos.
This patch fixes it by prepending sos symbol.

asr: Fix recog issue on Transformer CTC model

---

espnet2/tasks/abs_task.py
espnet2/train/trainer.py

Add --grad_clip_type to change the norm type of gradient clipping.
L2-norm is likely to have infinite value because it has power of gradient, so I thought L1- or Inf-norm might be better.

Implement --grad_clip_type

---

test/espnet2/train/test_distributed_utils.py

Sometimes `test/espnet2/train/test_distributed_utils.py` seems to be hangup in CI.
I guessed it caused by failing to get a free port and `torch.distributed.init_process_group()` is hangup. I'm not sure.

Fix hangup of unittests

---

README.md
egs/csj/asr1/RESULTS.md

I uploaded the CSJ RNN pre-trained model [here](https://drive.google.com/file/d/1ALvD4nHan9VDJlYJwNurVr7H7OV0j2X9/view?usp=sharing).
It is useful for CTC Segmentation, though it is worse than the transformer model in terms of accuracy.

ADD CSJ RNN pretrained model 

---

espnet/nets/pytorch_backend/ctc.py
tools/check_install.py
tools/installers/install_warp-ctc.sh

https://pypi.org/project/warpctc-pytorch/
Now `warpctc-pytorch` is released, which works with PyTorch 1.1, 1.2 and 1.3.
warp-ctc installation is like this,
- `torch >= 1.4`, warpctc will not be installed.
- `1.1 <= torch <= 1.3` , `warpctc-pytorch` wheel will be installed.
- `torch == 1.0` , `warpctc-pytorch10-cudaXX` wheel will be installed.

Install warpctc-pytorch wheel when torch version is 1.1, 1.2 or 1.3

---

test/espnet2/tts/test_fastspeech.py
test/espnet2/tts/test_fastspeech2.py
test/espnet2/tts/test_tacotron2.py
test/espnet2/tts/test_transformer.py

Now `test/espnet2/tts` requires only 14 sec in my local.
Related #2459

Make espnet2 tts test faster

---

.github/workflows/ci.yaml
.github/workflows/debian9.yml

github workflows ci.yml and debian.yml should have codecov because they run both unittests and integration tests.
https://github.com/codecov/codecov-action

Add codecov actions.

---

ci/install.sh
setup.py

This PR fixed the installation error in CI.
Also removed hacking-related workaround installation.
Related:
- https://github.com/psf/black/issues/1707
- https://github.com/python/typing/issues/573

Fix the installation error in CI

---

espnet/nets/pytorch_backend/e2e_tts_fastspeech.py
espnet/nets/pytorch_backend/fastspeech/length_regulator.py
espnet2/tts/fastspeech.py
espnet2/tts/fastspeech2.py
test/test_e2e_tts_fastspeech.py

Now x40 faster than the current version.
```
[ins] In [11]: %timeit xs_expanded = length_regulator(xs, ds)
7.11 ms Â± 143 Âµs per loop (mean Â± std. dev. of 7 runs, 100 loops each)
[ins] In [12]: %timeit xs_expanded = length_regulator(xs, ds)
7.05 ms Â± 207 Âµs per loop (mean Â± std. dev. of 7 runs, 100 loops each)
[ins] In [13]: length_regulator.repeat_fn = length_regulator._legacy_repeat_one_sequence
[ins] In [14]: %timeit xs_expanded = length_regulator(xs, ds)
284 ms Â± 633 Âµs per loop (mean Â± std. dev. of 7 runs, 1 loop each)
[ins] In [15]: %timeit xs_expanded = length_regulator(xs, ds)
284 ms Â± 1.81 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)
```

Refactor length regulator to improve the speed

---

test/espnet2/enh/nets/test_beamformer_net.py

Related #2459 
216sec -> 12.76sec
- Decrease model sizes
- Remove duplicated and unused parameters

Make test_beamformer_net.py faster

---

espnet/lm/pytorch_backend/extlm.py
espnet/nets/pytorch_backend/ctc.py
espnet/nets/pytorch_backend/e2e_asr_mix.py
espnet/nets/pytorch_backend/lm/default.py
espnet/nets/pytorch_backend/nets_utils.py
espnet/nets/pytorch_backend/rnn/attentions.py
espnet/nets/pytorch_backend/rnn/decoders.py
espnet/nets/pytorch_backend/rnn/encoders.py

FIX #2169
From pytorch1.5, there are no ways to derive the device number from torch.nn.module in DataParallel.forward(), using public API.
I fixed all codes in espnet1 as possible, but `recognize` and `recognize_batch` doesn't receive any tensors, so it's impossible to detect the device. The followings are remaining.
```
espnet/nets/pytorch_backend/e2e_asr.py:545:        xs = [to_device(self, to_torch_tensor(xx).float()) for xx in xs]
espnet/nets/pytorch_backend/e2e_asr.py:597:        xs = [to_device(self, to_torch_tensor(xx).float()) for xx in xs]
espnet/nets/pytorch_backend/e2e_asr.py:667:        h = to_device(self, torch.from_numpy(np.array(x, dtype=np.float32)))
espnet/nets/pytorch_backend/e2e_asr_mix.py:503:        h = to_device(self, to_torch_tensor(x).float()) …
```

fix multigpu bug if pytorch>=1.5

---

test/test_e2e_asr_maskctc.py

Related #2459 
10.1s -> 5.07s in local
- Decrease model and data sizes
- Remove importlib
- Mock savefig in plot

Make test_e2e_asr_maskctc.py faster.

---

test/test_recog.py

Related to #2459 
- Remove chainer lines because nothing was tested
- Remove etype/dtype variants because there is no difference in batch/non-batch search impl
- Decrease model and data sizes
43.85s -> 5.18s in local

Make test_recog.py faster

---

test/test_e2e_asr.py

Related to #2459 
16.02s -> 9.79s in local
- Decrease model and data sizes
- Remove unused chainer blocks
- Remove importlib

Make test_e2e_asr.py faster

---

egs2/csmsc/tts1/conf/tuning/train_transformer.yaml
egs2/jsut/tts1/conf/tuning/train_transformer.yaml
egs2/ljspeech/tts1/conf/tuning/train_transformer.yaml
egs2/vctk/tts1/conf/tuning/train_gst_transformer.yaml

I found that `lamb` optimizer is more stable than adam + warmup.
For Transformer-TTS, `adam + warmup` causes broken attention sometimes (depending on the dataset).
Therefore, we use `lamb` as a default for Transformer-TTS.

Update Transformer-TTS config

---

doc/tutorial.md
espnet/nets/pytorch_backend/transducer/causal_conv1d.py
espnet/nets/pytorch_backend/transducer/loss.py
espnet/nets/pytorch_backend/transducer/rnn_att_decoder.py
espnet/nets/pytorch_backend/transducer/rnn_decoder.py
espnet/nets/pytorch_backend/transducer/tdnn.py
espnet/nets/pytorch_backend/transducer/transformer_decoder_layer.py
espnet/nets/pytorch_backend/transducer/transformer_encoder.py
espnet/nets/pytorch_backend/transducer/vgg2l.py
test/test_e2e_asr_sa_transducer.py
test/test_e2e_asr_transducer.py

This PR modifies a few parts discussed but also missed in #2444:

Small fixes for transducer

---

espnet2/train/reporter.py

I changed add_scalars to add_scalar  for tensorboard SummaryWriter in reporter.py in espnet2 because add_scalars creates separated log files for each values. We don't prefer this behaviour.

Change add_scalars to add_scalar  for tensorboard SummaryWriter

---

egs2/TEMPLATE/asr1/asr.sh

To calculate WER per speaker for sctk, the utterance ids are named like "spk-uttid". I modified the uttid to be like so. Note that this is done for espnet1, but espnet2 doesn't. #2518

Modify uttid to "${spkid}-${uttid}" for trn files

---

README.md
espnet/bin/asr_align.py
utils/asr_align_wav.sh

This pull request provides the discussed changes in #2526:
1. In `asr_align.py`: It checks for a mismatch of dictionary and model blank characters, which is the most probable cause of IndexError in `ctc_segmentation()`. The log output will now report this mismatch.
2. It informs users about the increased memory consumption of Transformer models on large audio files. In `asr_align.py`, a check is conducted for non-RNN encoders. The downloaded pretrained model in `asr_align_wav.sh` is also checked. Also, a note in `README.md`.
I did not change the small example in `README.md` that uses a transformer model.
`wsj.transformer_small.v1` is a small model (quick download) and gives good results (in terms of confidence score and interval) on the provided example file:
```
ctc_align_test …
```

 CTC segmentation - checks for blank chars and RNN models

---

setup.py

Old h5py doesn't run on python 3.8. New one seems [fully compatible](https://docs.h5py.org/en/latest/whatsnew/2.10.html). On my computer everything runs just fine, but I'm not a tester, so I can't be sure.

Update h5py version to avoid errors in Python3.8

---

setup.py

Modified requirements: "dataclasses; python_version < '3.7'",

---

egs/mini_an4/asr1/conf/decode_transducer.yaml
egs/vivos/asr1/conf/tuning/transducer/decode_alsd.yaml
egs/vivos/asr1/conf/tuning/transducer/decode_default.yaml
egs/vivos/asr1/conf/tuning/transducer/decode_nsc.yaml
egs/vivos/asr1/conf/tuning/transducer/decode_tsd.yaml
egs/voxforge/asr1/conf/tuning/transducer/decode_alsd.yaml
egs/voxforge/asr1/conf/tuning/transducer/decode_default.yaml
egs/voxforge/asr1/conf/tuning/transducer/decode_nsc.yaml
egs/voxforge/asr1/conf/tuning/transducer/decode_tsd.yaml
espnet/asr/pytorch_backend/asr.py
espnet/bin/asr_recog.py
espnet/nets/beam_search_transducer.py
espnet/nets/e2e_asr_common.py
espnet/nets/pytorch_backend/e2e_asr_transducer.py
espnet/nets/pytorch_backend/transducer/joint_network.py
espnet/nets/pytorch_backend/transducer/rnn_att_decoder.py
espnet/nets/pytorch_backend/transducer/rnn_decoder.py
espnet/nets/pytorch_backend/transducer/transformer_decoder.py
espnet/nets/transducer_decoder_interface.py
test/test_asr_init.py
test/test_e2e_asr_sa_transducer.py
test/test_e2e_asr_transducer.py

Extracted from #2533. In order to use the same `BeamSearchTransducer` and `ErrorCalculatorTrans` classes in espnet1 and espnet2 some refactoring needs to be done on espnet1 side. I also split joint network according to other PR.
Some notes though:
- @ShigekiKarita `asr.py` is modified, I hope it's not an issue for #2521 
- Uploaded models for VIVOS will be incompatible. To be honest I'm not motivated to run again all experiments... At least for now.
- ~The PR is complete but I need to at least run some test to check I didn't break or impact performances with that changes.~ Done, there was a bug in NSC.

Refactor BeamSearchTransducer and ErrorCalculatorTrans

---

espnet/nets/pytorch_backend/ctc.py
tools/check_install.py
tools/installers/install_warp-ctc.sh

warpctc-pytorch 0.2.1 is released and the wheel can be installed when PyTorch >= 1.1 and <= 1.6.

Install warpctc-pytorch wheel when torch version is 1.1 - 1.6

---

espnet/nets/pytorch_backend/rnn/decoders.py

In multi-enc cases, att_w_list changes in each cycle, append method will make all elements in att_ws change synchronously, which leads to an incorrect attention-weights image.  So, we need to append a copy of att_w_list.

fix bug about att_ws in multi-enc case

---

egs2/TEMPLATE/asr1/pyscripts/utils/evaluate_mcd.py

This PR adds MCD evalution.
```sh
$ pyscripts/utils/evaluate_mcd.py \
--wavdir exp/tts_train_conformer_fastspeech2_raw_phn_pypinyin_g2p_phone/decode_train.loss.ave/eval1/wav_pwg \
--gt_wavdir dump/raw/eval1/data \
--outdir exp/tts_train_conformer_fastspeech2_raw_phn_pypinyin_g2p_phone/decode_train.loss.ave/eval1/wav_pwg/mcd
2020-10-05 11:32:06,913 (evaluate_mcd:272) INFO: The number of utterances = 100
...
2020-10-05 11:34:02,824 (evaluate_mcd:174) INFO: 009994 6.3555
2020-10-05 11:34:04,054 (evaluate_mcd:174) INFO: 009921 6.3340
2020-10-05 11:34:04,074 (evaluate_mcd:295) INFO: Average: 6.2542 ± 0.4846
2020-10-05 11:34:04,081 (evaluate_mcd:307) INFO: Successfully finished MCD evaluation.
```

Add MCD evaluation script for ESPnet2-TTS

---

tools/setup_python.sh

Google colab has python3 in /usr/bin and pip3 in /usr/local/bin. So this check is non-sense.

Remove pip3 check in setup_python.sh

---

espnet/bin/asr_align.py
setup.py
utils/asr_align_wav.sh

The ctc_segmentation python package was updated to version 1.1.0. with a fix for the bug discussed in #2526. I recommend to update to the new version.
After this update, the character list is passed via the configuration object, and the function `prepare_text()` does not need the dictionary as parameter anymore, so it was removed.
One other change: The parameter L used for generation of the segmentation score can now be changed via `asr_align.py` arguments.

CTC segmentation - package update

---

espnet/asr/pytorch_backend/asr_init.py

The parameter that determines the library used for CTC loss is written in the model config `train_args`. Some models read this setting and load the CTC loss module on initialization, e.g. the Transformer model, _even when CTC loss is not needed for recognition_.
This issue is relevant for users of pre-trained networks. If the model was trained with `warp-ctc` but this library is not installed, this results in an import error:
```
File "/xxx/espnet/espnet/asr/pytorch_backend/asr_init.py", line 176, in load_trained_model
model = model_class(idim, odim, train_args)
File "/xxx/espnet/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 151, in __init__
self.ctc = CTC(
File "/xxx/espnet/espnet/nets/pytorch_backend/ctc.py", line 41, in __init__
import warpctc_pytorch as warp_ctc …
```

Set built-in CTC for asr_recog

---

egs/tedlium3/asr1/RESULTS.md
egs/tedlium3/asr1/conf/train.yaml
egs/tedlium3/asr1/conf/tuning/train_conformer.yaml

- Model files (archived to model.tar.gz by `$ pack_model.sh`)
- model link: https://drive.google.com/file/d/11CN3tPF4MXM6wKdTFo7GjX3TlhhZobk-
- training config file: `conf/tuning/train_conformer.yaml`
- decoding config file: `conf/decode.yaml`
- preprocess config file: `conf/specaug.yaml`
- cmvn file: `data/train_trim_sp/cmvn.ark`
- e2e file: `exp/train_trim_sp_pytorch_nbpe500_ngpu4_train_conformer_specaug/results/model.last10.avg.best`
- e2e JSON file: `exp/train_trim_sp_pytorch_nbpe500_ngpu4_train_conformer_specaug/results/model.json`
- lm file: `exp/train_rnnlm_pytorch_lm_irie_unit1024_unigram500/rnnlm.model.best`
- lm JSON file: `exp/train_rnnlm_pytorch_lm_irie_unit1024_unigram500/model.json`
- dict file: `data/lang_char/train_trim_sp_unigram500_units.txt`
- Results (paste them by …

Update TedLium3 conformer results

---

utils/average_checkpoints.py

Averaging int tensors in Pytorch 1.6 gives a run time error - 
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
This PR will look for integer tensors and average accordingly.

Conformer averaging model support for pytorch 1.6

---

tools/installers/install_chainer_ctc.sh
tools/installers/install_kenlm.sh
tools/installers/install_py3mmseg.sh
tools/installers/install_warp-ctc.sh
tools/installers/install_warp-rnnt.sh
tools/installers/install_warp-transducer.sh

#2615
`python setup.py install` requires the write permission to the Python.
pip>= 20.2, or 20.1?,  can switch to usermode if the write permission doesn't exist automatically, so it's better to use `pip install` always.
I also added `-e` option. This is not related to this issue, but maybe this is also useful in cases.

python setup.py install -> pip install -e

---

espnet2/layers/global_mvn.py

#2614 
In global_mvn.py, variance can get negative values due to numerical errors when the value is small.
I changed where the flooring is applied.

Fix flooring for global_mvn.py 

---

espnet/asr/pytorch_backend/asr.py

If `save_interval_iters>0`, the model snapshot is not saved at the end of the epoch.
This leads to an error when we try to average the n-best models after training as `model.ep.<epoch-num>` is not available, but the loss/accuracy entries for each epoch are available in `exp/<exp-name>/results/log`
This PR just removes the `else` condition for model snapshot so that along with `snapshot.iter.<iter-num>`, we also have `model.ep.<epoch-num>`.

Save model snapshot at every epoch even if save_interval_iters>0 - for model averaging

---

espnet2/utils/yaml_no_alias_safe_dump.py

If your tokens are not English they are shown incorrectly in the generated config. Here is a little fix to generate proper yaml.

Added unicode support for generated configs

---

doc/espnet2_training_option.md
espnet2/tasks/abs_task.py
espnet2/torch_utils/load_pretrained_model.py
test/espnet2/torch_utils/test_load_pretrained_model.py

I removed --pretrain_path and --pretrain_key options and implemented --init_param newly.
```bash
python -m espnet2.bin.asr_train --init_param model.pth
python -m espnet2.bin.asr_train --init_param model.pth:decoder
python -m espnet2.bin.asr_train --init_param model.pth:decoder:decoder
python -m espnet2.bin.asr_train --init_param decoder.pth::decoder
python -m espnet2.bin.asr_train --init_param model.pth:::decoder.embed
python -m espnet2.bin.asr_train --init_param model.pth:::encoder,decoder.embed
```

Add --init_param option

---

egs/librispeech/asr1/run.sh

The data2json.sh script supports multi-thread processing but is not used in current recipe.
Added `--nj ${nj}` to data2json.sh in stage 2.

Enable multi-thread processing of json files.

---

README.md
egs/swbd/asr1/RESULTS.md
egs/swbd/asr1/conf/lm.yaml
egs/swbd/asr1/conf/train.yaml
egs/swbd/asr1/conf/tuning/lm.yaml
egs/swbd/asr1/conf/tuning/lm_transformer.yaml
egs/swbd/asr1/conf/tuning/train_pytorch_conformer_lr5.yaml
egs/swbd/asr1/run.sh

(1) Update conformer results on swbd; 
(2) Add speed perturb in egs/swbd/run.sh
- date: `Wed Nov 18 23:24:06 CST 2020`
- python version: `3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42)  [GCC 7.2.0]`
- espnet version: `espnet 0.9.3`
- chainer version: `chainer 6.0.0`
- pytorch version: `pytorch 1.6.0`
```
exp_sp/train_nodup_sp_pytorch_train_pytorch_conformer_lr5_specaug_resume/decode_eval2000_model.last10.avg.best_decode_train_transformer_lm_pytorch_swbd+fisher_bpe2000/scoring/hyp.callhm.ctm.filt.sys
|       SPKR              |        # Snt              # Wrd        |        Corr                 Sub                  Del                 Ins                  Err               S.Err        |
|       Sum/Avg           |        2628               21594        |        87.9 …
```

Update Switchboard with conformer results

---

egs/csmsc/tts1/local/data_download.sh
egs/csmsc/tts1/local/data_prep.sh
egs2/csmsc/tts1/local/data.sh
egs2/csmsc/tts1/local/path.sh

We have applied `nkf` in the download stage, but some people miss this processing.
Therefore I use `nkf` in data prep to avoid format error.
Related: #2725 #1613

Use `nkf` in CSMSC data prep

---

ci/install.sh

From pip 20.3, the version in metadata must be the same as pypi version.
https://github.com/espnet/espnet/runs/1473939967
https://github.com/pypa/pip/issues/8745
To avoid this error, temporary fix pip version to the old one.

Temporary fix pip version to avoid PEP440 error

---

setup.py
tools/Makefile

Issue:
`pip install espnet` tries to install all dependencies including the requirements from recipes.
I created "recipe" command in setup.py and moved the dependencies.
- Minimal installation: `pip install espnet` 
- Inference only: `pip install espnet_model_zoo`
- Note that `espnet_model_zoo` depends on `espnet`.
- Train using our recipe (=full installation): `pip install "espnet[recipe]"`

Move the dependencies coming from recipes

---

ci/install.sh
doc/installation.md
tools/Makefile
tools/check_install.py

`warp-ctc` and `warp-transducer` are likely to cause installation error, but many people doesn't need these library, so they should be optional.

Change warp-ctc and warp-transducer to extra 

---

egs2/TEMPLATE/asr1/pyscripts/utils/plot_sinc_filters.py
egs2/voxforge/asr1/README_LightweightSincConvs.md
espnet2/asr/frontend/windowing.py
espnet2/asr/preencoder/sinc.py

@kamo-naoyuki Added more documentation. Also, I changed the mode of `plot_sinc_filters.py` to executable...
The `README_LightweightSincConvs.md` in the voxforge recipe folder is maybe not the best place to document how to use the sinc convolutions module and the plotting tool, so I put some of the information into the module docstrings.
The plotted filters of the RNN network trained on voxforge look like this:
Comparison of initialized to learned filters looks like this:
(dashed lines for initialization values, blue line for learned filters)
This PR is a follow-up to #2768.

Sinc Convolutions - add documentation for plot_sinc_filters.py

---

doc/espnet2_training_option.md
espnet2/tasks/abs_task.py

```sh
python -m espnet2.bin.asr_train --freeze_param encoder.enc.0.bt2 
```
Note that this option sets param.requires_grad = False, so it can be reset to True if you are setting it in model.forward()

--freeze_param option

---

espnet2/tasks/asr.py

`preencoder` is added but it does not exist in the old models.
This PR fixed the above issue.

Fix the compatibility of the pretrained ASR model

---

tools/installers/install_pyopenjtalk.sh

Recently, hts_engine_API uses `cmake` instead of `waf`.
This PR fixed the installation error due to the above change.

Fix HTS engine installation

---

tools/extra_path.sh

When I ran `egs/iwslt18/asr1/run.sh`, I got an error as shown below even after running `cd <my-espnet-path>/egs/iwslt18/asr1/../../../tools && make mwerSegmenter.done`.
```
Error: it seems that mwerSegmenter is not installed.
Error: please install mwerSegmenter as follows.
Error: cd <my-espnet-path>/espnet/egs/iwslt18/asr1/../../../tools && make mwerSegmenter.done
```
This was because `$PATH` variable was not set properly in `tools/extra_path.sh`.
I fixed it.

fix the incorrect $PATH setting in tools/extra_path.sh

---

tools/Makefile
tools/check_install.py
tools/extra_path.sh

- I removed exit signal from check_install.py because the required tools differ depending on each user's usage.  
- I removed --no-cuda and --no-cupy option.
- I removed the version check for pytorch.
- I added all external python modules to the checked modules list.
- I also added executable tools
```sh
python check_install.py
```
```
[x] python=3.7.7 (default, May  7 2020, 21:25:33)  [GCC 7.3.0]
Python modules:
[x] torch=1.4.0
[x] torch cuda=10.1
[x] torch cudnn=7603
[x] torch nccl
[x] chainer=6.0.0
[x] chainer cuda
[x] chainer cudnn
[x] cupy=6.0.0
[x] cupy nccl
[x] torchaudio=0.4.0
[x] torch_optimizer=0.1.0
[ ] warpctc_pytorch
[ ] warprnnt_pytorch
[ ] warp_rnnt
[x] chainer_ctc
[ ] pyopenjtalk
[x] kenlm
[ ] mmseg
[x] espnet=0.9.6
Executables:
[x] sclite
[x] sph2pipe
[ ] PESQ
[ ] …
```

modified:   check_install.py

---

egs/csj/asr1/run.sh

I made some minor changes in run.sh:
1. Set default `backend` to `pytorch`
2. Fixed a bug in model averaging (missing `average_opts` for averaging last N models)

Minor fixes in CSJ

---

espnet2/bin/enh_inference.py
espnet2/enh/espnet_model.py
espnet2/layers/stft.py
test/espnet2/bin/test_enh_inference.py

As @kamo-naoyuki  suggested in [#2649](https://github.com/espnet/espnet/pull/2649#issuecomment-760036269), I now implement the SeparateSpeech API for ENH. Here is an example:
```python
import soundfile
from espnet_model_zoo.downloader import ModelDownloader
from espnet2.bin.enh_inference import SeparateSpeech
d = ModelDownloader()
separate_speech = SeparateSpeech(
**d.download_and_unpack("model_name"),
segment_size=2.4,
hop_size=0.8,
normalize_segment_scale=False,
show_progressbar=True,
ref_channel=None,
normalize_output_wav=True,
)
speech, rate = soundfile.read("long_speech.wav")
waves = separate_speech(speech[None, ...], fs=rate)
```
This API allows processing both short audio samples and long audio samples. For long audio samples, you can set the value of arguments `segment_size`, …

Add SeparateSpeech API in espnet2/bin/enh_inference.py

---

espnet/nets/pytorch_backend/transducer/blocks.py

Fix #2914.
It doesn't impact reported experiments with TDNN/CausalConv1D as I used same input and output dim.
Given the tiny changes I'm adding auto-merge tag, I hope it's okay...

fix out_dim definition

---

egs/aishell/asr1/RESULTS.md

Update the Google Drive link of the pre-trained Aishell-1 Conformer model.
Refer to this issue: https://github.com/espnet/espnet/issues/2899.

Update the pre-trained Conformer model link of Aishell-1 corpus.

---

espnet/nets/beam_search_transducer.py

Fix a typo in time-synchronous decoding introduced in a recent refactor. Thanks to @hirofumi0810 for catching that!

Fix a condition in TSD

---

tools/Makefile
tools/installers/install_fairseq.sh

Chainer==6.0.0 depends on typing<=3.6.6, but this causes the following error when installing some modules. e.g. fairseq
```
AttributeError: type object 'Callable' has no attribute '_abc_registry
```
"typing" modules is not required for python>=3.6, so originally it should be written as ""typing; python_version < '3.6'"".
This error message is well known for me, but many users might be confused, so I decided to uninstall  typing.

Uninstall typing

---

README.md
doc/espnet2_distributed.md
espnet2/tasks/abs_task.py
espnet2/train/trainer.py
setup.py

I  added supporting sharded training provided by FairScale: https://github.com/facebookresearch/fairscale
- You can enable this feature just adding `--sharded_ddp true`
- I tested multiple gpus on single node 
- Multiple nodes training is failed. I don't know why. I'll investigate if I have time.
- I didn't compare the performance, but several good reports already exist: https://seannaren.medium.com/introducing-pytorch-lightning-sharded-train-sota-models-with-half-the-memory-7bcc8b4484f2
- I also refactor trainer class. Maybe, this is more readable.

Support sharded training of fairscale

---

egs2/librimix/enh1/local/data.sh

Fix an issue in librimix data preparation stage. The directory that not exists in the first run may cause failure.

quick fix for librimix (SE) data preparation

---

doc/espnet2_distributed.md
espnet2/tasks/abs_task.py
espnet2/train/trainer.py

- I fixed to invoke `consolidate_state_dict()` for multiple nodes case
- I reverted --ddp_shared to --sharded_ddp. I changed my mind
Multiple nodes training can't work now because fairscale has a bug.

Fix sharded training for multiple nodes

---

espnet/asr/pytorch_backend/asr.py
espnet/asr/pytorch_backend/asr_mix.py
espnet/lm/pytorch_backend/lm.py
espnet/mt/pytorch_backend/mt.py
espnet/st/pytorch_backend/st.py
espnet/tts/pytorch_backend/tts.py
espnet/vc/pytorch_backend/vc.py
espnet2/torch_utils/model_summary.py

Adding a small snippet of code that prints the number of model params and the trainable params along with the percentage trainable (borrowed from https://github.com/pytorch/fairseq/pull/469) in both espnet and espnet-2.
For espnet-2, I just added total params and the percentage to the model_summary.py as suggested by @simpleoier. 
I have tested it for ASR task in ESPnet and it works and thanks @simpleoier for testing it on ESPnet-2!

Print total params and trainable params.

---

espnet/bin/asr_train.py
espnet/bin/st_train.py
espnet/nets/pytorch_backend/ctc.py

I modified the existing CTC builtin code as the CuDNN CTC code (set with option "cudnnctc").
Added the pytorch CUDA CTC as the "builtin" option, which has the option of "zero_infinity". This takes care of "poorly aligned" utterances. The "builtin" option also accepts input larger than 256 frames. (pytorch/pytorch#21244).
Resubmit of https://github.com/espnet/espnet/pull/2988

builtin ctc modification

---

ci/install.sh
tools/installers/install_warp-ctc.sh

fixes https://github.com/espnet/warp-ctc/issues/35
Now that warp-ctc wheels are served in its [release page](https://github.com/espnet/warp-ctc/releases/tag/v0.2.2) instead of pypi.org, PEP440 restriction can be avoided.

Install warp-ctc using pip>=21.0

---

espnet2/train/trainer.py

Now when use_amp=True, fairscale is required. This is a bug.

Fix a bug when use_amp=True without fairscale

---

doc/installation.md

Also, support for ubuntu 16.04 seems to have been dropped, and justly so.

[docs] [minor] fix a broken link

---

espnet2/tasks/abs_task.py
espnet2/train/distributed_utils.py
test/espnet2/train/test_distributed_utils.py

Logging is not shown if using pytorch==1.8 with ngpu>=2
torch.distributed.init_process_group uses logging.info. If logging.info, logging.error, or etc. are used before calling logging.basicConfig, logging.basicConfig is ignored.
```python
logging.error()
logging.basicConfig(level="INFO")
logging.info()  # Not shown because basicConfig is ignored.
```
I modified the code not to invoke torch.distributed.init_process_group before logging.basicConfig.

Fix logging for pytorch>=1.8

---

tools/Makefile

Sorry, I forgot to activate python in the Makefile. Some users might meet an error when installation.

Fix a bug of  uninstalling typing

---

utils/speed_perturb.sh

Fixed a bug when used for ASR recipes.
The current implementation overwrites `text` in the `for` loop, which was pointed out by @pengchengguo.

Fix utils/speed_perturb.sh

---

espnet2/asr/encoder/conformer_encoder.py
test/espnet2/asr/encoder/test_conformer_encoder.py

This PR added support for LegacyRelPositionMultiHeadedAttention and LegacyRelPositionalEncoding in espnet2.
The PR #2816 , which fixed the bug of the conformer implementation, caused backward compatibility issue in espnet2. When loading a model trained before that PR, new RelPositionMultiHeadedAttention and RelPositionalEncoding definitions have been automatically used without warning, and there has been no way to select "Legacy" definitions. This caused degradation of ASR performance.
Following the discussion in https://github.com/espnet/espnet/pull/2816#issuecomment-781793673 , "Legacy" definitions will select by default and to enable new definitions you need to add `rel_pos_type=latest` option in a configuration.
We tested with the LaboroTVSpeech default recipe;
- Training time …

Fixed backward compatibility issue of new conformer definition

---

tools/installers/install_pyopenjtalk.sh

@r9y9 released a new version of pyopenjtalk, which reduce the burden of the installation of external tools.
https://github.com/r9y9/pyopenjtalk/releases/tag/v0.1.0
This PR changes the installation of pyopenjtalk to use the new version.

Use new pyopenjtalk version

---

egs/vcc20/README.md

Fixed small typo in `egs/vcc20/README.md`

typo fix in vcc20 README

---

setup.py

For the release, fix the ctc-segmentation version until #3087 merged.

Temporally fix the ctc-segmentation version

---

test/espnet2/train/test_distributed_utils.py

Sometimes, distributed utils' test with "gloo" causes errors randomly.
https://github.com/espnet/espnet/runs/2283829957?check_suite_focus=true#step:8:3763
This PR disabled related test.

Disable test using gloo to make CI stable

---

README.md
doc/tutorial.md

I added some descriptions for CTC decoding in doc/tutorial.md. I also made a minor change in README.md.

Add documentation for CTC decoding

---

egs/iwslt21/asr1/local/merge_short_segments.py
egs/iwslt21/st1/run.sh

Merge short segments until the total input length surpasses a threshold (e.g., 15 seconds).
However, merging is skipped if there is a pause longer than another threshold (e.g., 200ms).
This process is conducted in a greedy way from left to right and continues until all segments in a session satisfy the condition.

Merge short segments in IWSLT test sets

---

egs/swbd/asr1/run.sh

espnet1 swbd recipe has several minor bugs
For example, in data/train/text 
after this command `sed -i 's/\._/ /g; s/\.//g; s/them_1/them/g' data/${train_set}/text`
_sp0.9xxxx this is a t.e.xt --> sp09xxxx this is a text_ would change the utterance name and cause utternance name mismatch with other scp files.

fix receipe bug for swbd

---

espnet2/asr/espnet_model.py

This PR changes to set `self.decoder = None` in the CTC mode since `self.decoder` parameters were never used and PyTorch complained and threw an Exception in the multi-GPU experiment.
Thanks Jeff Farris for pointing out the issue!

fix a bug in the CTC mode

---

espnet/nets/pytorch_backend/ctc.py
espnet/nets/pytorch_backend/gtn_ctc.py
test/test_loss.py
tools/check_install.py
tools/installers/install_gtn.sh

This PR is WIP - I am testing the new implementation of CTC loss on Voxforge IT.
In a previous PR (https://github.com/espnet/espnet/pull/2866) I added a 'gtnctc' option for computing CTC loss using GTN differentiable WFSTs. This PR is a follow-up containing: 1) a bug fix 2) unit tests, and 3) installer.
1) Bug fix for improper handling of padding in log prob tensor.
The differentiable WFST based CTC loss function processes samples in the batch in parallel, meaning we index a tensor of size (T, C) from the batched tensor of size (B, T, C) representing log probs. Problem is that this includes padding in T that is not ignored. The fix for this is to slice the (T, C) tensor according to the unpadded input lengths: https://github.com/brianyan918/espnet-ml/blob/8c5b2414cb5351aa3584d8178e66034a8b …

[WIP] GTN CTC bug fix, unit test, and installer

---

espnet2/train/preprocessor.py

Hi all,
When adding noise to the training data, I found the probability of adding noise is determined by `self.rir_apply_prob`, instead of `self.noise_apply_prob`. Maybe this is a mistake.

Fix a bug of adding noise to the training data.

---

espnet2/train/dataset.py

Extended ark format case condition was the same as the sound scp case

fix typo for AdapterForSoundScpReader

---

egs/jsut/tts1/local/download.sh

Hi, I'm muramasa from Japan.
When I try to use jsut recipe, I found out the misspelling in ./egs/jsut/tts1/local/download.sh.
```
if [ ! -e ${download_dir}/jsut_lab ]; then
echo "Downloading full-context labels for jsut v1.1..."
cd ${download_dir}
git clone https://github.com/r9y9/jsut-lab
```
On the first line there is `${download_dir}/jsut_lab`,   
but the correct name of cloned dir is `jsut-lab` as follows `git clone https://github.com/r9y9/jsut-lab`.
So I fixed it, please check and merge it!

Fix misspelling in ./egs/jsut/tts1/local/download.sh

---

espnet2/text/char_tokenizer.py

It seems that for some pretrained models, the text cleaner tries to load `non_linguistic_symbols` from a file that doesn't exist. I did  short description in #3232  and tried to solve this by catching the file open error.
@kamo-naoyuki 
You understand the tokenizer better. Could you look into it if this solution is OK?

Fix missing nlsyms.txt for pretrained models

---

egs/aishell/asr1/RESULTS.md
egs/aishell/asr1/conf/tuning/transducer/decode_default.yaml
egs/aishell/asr1/conf/tuning/transducer/train_conformer-rnn_transducer.yaml
egs/aishell/asr1/conf/tuning/transducer/train_conformer-rnn_transducer_aux_ngpu4.yaml
egs/aishell/asr1/conf/tuning/transducer/train_transducer.yaml
egs/aishell/asr1/conf/tuning/transducer/train_transducer_aux.yaml
egs/aishell/asr1/run.sh

This PR adds config files & results of transducer models for AISHELL-1.
Specifically, three configurations (and their results) are provided in this PR:
- RNN-Transducer
- Conformer-Transducer
- Conformer-Transducer with auxiliary task
Note that `run.sh` was modified to disable `--api v2` if the model is transducer, because it seems transducer doesn't support the API version2; therefore ngram model (if given) is ignored in Stage 5 (decoding).

Transducer configs & results for AISHELL-1

---

egs/mgb2/asr1/local/xml2stm.py

if I run xml2stm.py to generate STM and CTM files from XML file I get this error :
```
Traceback (most recent call last):
File "xml2stm.py", line 133, in <module>
main(args)
File "xml2stm.py", line 98, in main
stm(data)
File "xml2stm.py", line 72, in stm
"{} 1 UNKNOWN {:.02f} {:.02f} ".format(data["id"], e.startTime, e.endTime)
File "/home/jupyter-achraf.mahdhi/.conda/envs/espnet/lib/python3.7/codecs.py", line 378, in write
self.stream.write(data)
TypeError: write() argument must be str, not bytes
```
so I fixed this error on the following script and it works for me now!

Fix some bugs in xml2stm.py

---

espnet2/bin/tokenize_text.py

Fix #3263
Old PR content:
> This allows the user to keep the columns in the input (such as `utt`) in the output file
> 
> Using the librispeech transcript as an example:
> 
> ```
> python -m espnet2.bin.tokenize_text --token_type "phn" \
>                                                  --input "tmp.txt" --output "tmp.phn" --field 2-4 \
>                                                                                               --cleaner none --g2p "g2p_en" --write_vocabulary false \
>                                                                                                                                                --keep_all_fields true
> ```
> The input is:
> ```
> 103-1240-0015 IF HE'D RUN OUT OF TURNIP SEED HE WOULDN'T DRESS UP AND TAKE THE BUGGY TO GO FOR MORE
> ```
> …

Fix bug when "--field -5" is passed to espnet2.bin.tokenize_text

---

egs2/TEMPLATE/asr1/asr.sh

In stage 12 of [asr.sh](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L1178):
```bash
if [ "${token_type}" = pnh ]; then
log "Error: Not implemented for token_type=phn"
exit 1
fi
```
it should be `phn`

Fix typo in asr.sh (espnet2) that might cause bug

---

espnet2/train/trainer.py

Now optimizer.zero_grad() is not invoked when the gradient is nan and accum_grad>1.
This is a fatal bug of #3014 and probably causes different result from previous version... Maybe #3170 also comes from here.

Bug fix of accum_grad when grad-nan

---

.github/workflows/ci.yaml
ci/test_integration.sh
espnet/asr/pytorch_backend/asr.py
espnet/asr/pytorch_backend/recog.py
espnet/bin/asr_recog.py
test/test_asr_quantize.py

This PR adds dynamic quantization for decoding.

Dynamic quantization for decoding

---

espnet2/asr/ctc.py

Fix errors when warpctc was used (related to #2699)
https://github.com/espnet/espnet/runs/2855468543#step:8:259

Warn ignore_nan_grad with warpctc instead of error.

---

.github/workflows/centos7.yml
.github/workflows/ci.yaml
.github/workflows/debian9.yml
.github/workflows/doc.yml
README.md
tools/Makefile

Add pytorch 1.9.0 support and remove 1.0.1, 1.1.0, and 1.2.0

---

.mergify.yml
espnet2/train/iterable_dataset.py
setup.py

Now pytorch1.9.0 isn't tested in the current ci because torchaudio changes the pytorch version.
I also fixed an issue (#3309, #3304) when using pytorch1.9.0.

Follow up for #3299, about pytorch1.9.0 in ci

---

espnet2/bin/tts_inference.py

It adds a possibility to synthesize speech with various speed values without reloading a model.
Resolves #3256.

Allow override default 'speed_control_alpha' parameter

---

espnet2/schedulers/abs_scheduler.py

OneCycleLR and CyclicLR schedulers should be per iteration, not per epoch.
Thanks, Jeff Farris for pointing out the issue!

fix a bug in OneCycleLR and CyclicLR

---

egs/swbd/asr1/local/eval2000_data_prep.sh
egs/swbd/asr1/local/fisher_data_prep.sh
egs/swbd/asr1/local/rt03_data_prep.sh
egs/swbd/asr1/local/swbd1_data_prep.sh
egs2/swbd/asr1/local/data.sh

Fix a type error of SWBD data preparation and also change the command `find` to `find -L` in case the corpus directory is a soft link.

Fix a type error of swbd data preparation.

---

espnet2/bin/tokenize_text.py
espnet2/tasks/asr.py
espnet2/tasks/enh_asr.py
espnet2/tasks/lm.py
espnet2/tasks/tts.py
espnet2/text/phoneme_tokenizer.py
test/espnet2/text/test_phoneme_tokenizer.py

This PR support german g2p.
```
[nav] In [1]: from espnet2.text.phoneme_tokenizer import PhonemeTokenizer
[nav] In [2]: pt = PhonemeTokenizer("espeak_ng_german")
[nav] In [3]: pt.text2tokens("Das hört sich gut an.")
Out[3]:
['d',
'a',
's',
'h',
'ˈœ',
'ɾ',
't',
'z',
'ɪ',
'ç',
'ɡ',
'ˈuː',
't',
'ˈa',
'n',
'.']
```

Support German G2P

---

espnet2/bin/tokenize_text.py
espnet2/tasks/asr.py
espnet2/tasks/enh_asr.py
espnet2/tasks/lm.py
espnet2/tasks/tts.py
espnet2/text/phoneme_tokenizer.py
test/espnet2/text/test_phoneme_tokenizer.py

This PR supports French G2P.
```python
[ins] In [1]: from espnet2.text.phoneme_tokenizer import PhonemeTokenizer
[ins] In [2]: pt = PhonemeTokenizer("espeak_ng_french")
[ins] In [3]: pt.text2tokens("Bonjour le monde.")
Out[3]: ['b', 'ɔ̃', 'ʒ', 'ˈu', 'ʁ', 'l', 'ə-', 'm', 'ˈɔ̃', 'd', '.']
```

Support french G2P

---

espnet2/bin/tokenize_text.py
espnet2/tasks/asr.py
espnet2/tasks/enh_asr.py
espnet2/tasks/lm.py
espnet2/tasks/tts.py
espnet2/text/phoneme_tokenizer.py
test/espnet2/text/test_phoneme_tokenizer.py

This PR supports Spanish G2P.
```python
[ins] In [1]: from espnet2.text.phoneme_tokenizer import PhonemeTokenizer
[ins] In [2]: pt = PhonemeTokenizer("espeak_ng_spanish")
[ins] In [3]: pt.text2tokens("Hola Mundo.")
Out[3]: ['ˈo', 'l', 'a', 'm', 'ˈu', 'n', 'd', 'o', '.']
```

Support Spanish G2P

---

egs2/TEMPLATE/tts1/README.md
espnet2/bin/tokenize_text.py
espnet2/tasks/asr.py
espnet2/tasks/enh_asr.py
espnet2/tasks/lm.py
espnet2/tasks/tts.py
espnet2/text/phoneme_tokenizer.py
test/espnet2/text/test_phoneme_tokenizer.py

This PR supports Russian G2P.
```python
[ins] In [1]: from espnet2.text.phoneme_tokenizer import PhonemeTokenizer
[ins] In [2]: pt = PhonemeTokenizer("espeak_ng_russian")
[ins] In [3]: pt.text2tokens("Привет мир.")
Out[3]: ['p', 'rʲ', 'i', 'vʲ', 'ˈe', 't', 'mʲ', 'ˈi', 'r', '.']
```

Support Russian G2P

---

egs2/TEMPLATE/asr1/scripts/audio/trim_silence.sh
utils/trim_silence.py
utils/trim_silence.sh

This PR adds `trim_silence.sh` for espnet2, which generates `segments` file to remove the silence at the beginning and the end of audio.

Add trim_silence for ESPnet2-TTS

---

egs2/TEMPLATE/tts1/README.md
espnet2/bin/tokenize_text.py
espnet2/tasks/asr.py
espnet2/tasks/enh_asr.py
espnet2/tasks/lm.py
espnet2/tasks/tts.py
espnet2/text/phoneme_tokenizer.py
test/espnet2/text/test_phoneme_tokenizer.py

This PR adds the support of Korean G2P.
```
[nav] In [1]: from espnet2.text.phoneme_tokenizer import PhonemeTokenizer
[nav] In [2]: pt = PhonemeTokenizer("g2pk")
[nav] In [3]: pt.text2tokens("안녕하세요!")
Out[3]: ['ᄋ', 'ᅡ', 'ᆫ', 'ᄂ', 'ᅧ', 'ᆼ', 'ᄒ', 'ᅡ', 'ᄉ', 'ᅦ', 'ᄋ', 'ᅭ', '!']
```

Support Korean G2P

---

.github/workflows/ci.yaml
setup.py
test_utils/test_spm.bats

This pull request fixes the test for sentencepiece and remove Sentencepiece version limitation.
Because [Sentencepiece supports Python 3.9 since v0.19.5](https://github.com/google/sentencepiece/issues/591#issuecomment-757425951), it enables python 3.9 support.
The reason for the test failures by increasing the version of Sentencepiece was the improper specification of options in the test.
(Insertion of an invalid duplicated option ``--user_defined_symbols``)

Update Sentencepiece and add python 3.9 to CI

---

doc/conf.py
doc/docker.md
doc/espnet2_task.md
doc/espnet2_training_option.md
doc/installation.md
doc/tutorial.md

Detected typos by using [typos](https://github.com/crate-ci/typos) and fixed them with manual check

Fix typos in "doc"

---

egs2/TEMPLATE/tts1/tts.sh
espnet2/bin/tts_inference.py
espnet2/tts/abs_tts.py
espnet2/tts/espnet_model.py
espnet2/tts/fastspeech.py
espnet2/tts/fastspeech2.py
espnet2/tts/tacotron2.py
espnet2/tts/transformer.py

Subset of #3423 
Sometimes, we want to analyze the outputs in inference.
Current Text2Speech interface assumes that fixed number of outputs, which makes it difficult to add new outputs in the inference.
This PR changes the output format to dict, which enables us to add a new outputs.

Change Text2Speech class output format

---

espnet2/bin/asr_inference.py

Ngram function will need `kenlm` for modeling, which will add additional requirements to the code-base. This may result in CI failure (e.g., https://github.com/espnet/espnet_model_zoo/pull/43)

Dynamic import for the ngram function

---

egs2/TEMPLATE/asr1/pyscripts/audio/trim_silence.py

Add missing symlink to trim_silence.py for ESPnet2

---

espnet2/bin/tts_inference.py

Bugfix of #3437.
I forgot to add them in output_dict.

Add duration and focus_rate in output dict

---

egs/wsj/asr1/conf/tuning/train_pytorch_transformer_interctc.yaml
espnet/nets/pytorch_backend/conformer/encoder.py
espnet/nets/pytorch_backend/conformer/encoder_layer.py
espnet/nets/pytorch_backend/e2e_asr_conformer.py
espnet/nets/pytorch_backend/e2e_asr_maskctc.py
espnet/nets/pytorch_backend/e2e_asr_transformer.py
espnet/nets/pytorch_backend/transformer/argument.py
espnet/nets/pytorch_backend/transformer/encoder.py
espnet/nets/pytorch_backend/transformer/encoder_layer.py
test/test_e2e_asr_conformer.py
test/test_e2e_asr_maskctc.py
test/test_e2e_asr_transformer.py

This implements [intermediate CTC](https://arxiv.org/abs/2102.03216) with [stochastic depth](https://arxiv.org/abs/1603.09382) for Transformer and Conformer encoders.
`stochastic_depth_rate` indicates the drop probability, similar to the dropout parameter. This might be confusing as the many papers use the notation of keep probability (`= 1 - drop_rate`). But I think it would be better to follow dropout notation.
The return type of Encoder needs to be changed due to intermediate CTC. To minimize the issue, the return type is changed only if `Encoder(intermediate_layers=...)` is given.
I would add some recipes soon.

Intermediate CTC + Stochastic depth

---

espnet2/gan_tts/vits/monotonic_align/__init__.py
espnet2/gan_tts/vits/monotonic_align/core.pyx
espnet2/gan_tts/vits/monotonic_align/setup.py

This PR adds cython code of maximum path calculation.
I'm wondering which is better:
- keep the cython setup as an optional (current style)
- integrate with root `setup.py` as a default 
For setup.py, I referred this one:
https://github.com/lumaku/ctc-segmentation/blob/master/setup.py

Add cython code for VITS

---

espnet2/bin/tts_inference.py
espnet2/tts/abs_tts.py
espnet2/tts/espnet_model.py
espnet2/tts/fastspeech/fastspeech.py
espnet2/tts/fastspeech2/fastspeech2.py
espnet2/tts/fastspeech2/loss.py
espnet2/tts/fastspeech2/variance_predictor.py
espnet2/tts/tacotron2/tacotron2.py
espnet2/tts/transformer/transformer.py
espnet2/tts/utils/duration_calculator.py
test/espnet2/tts/test_fastspeech.py
test/espnet2/tts/test_fastspeech2.py
test/espnet2/tts/test_tacotron2.py
test/espnet2/tts/test_transformer.py

Since we will add end-to-end text-to-wav model, the argument name for `AbsTTS` will be confusing.
This PR changes the argument name from `speech` to `feats`.
Note that this PR should not affect the compatibility with the old pretrained models.
Also split some modules for better modularization.

Refactor TTS modules in ESPnet2

---

README.md
utils/asr_align_wav.sh

[According to the instruction of CTC Segmentation in README](https://github.com/espnet/espnet/blame/2e4df0ad9c0ad7ebf0854962120708b5a9e03d0b/README.md#L553-L557), 
``utils/asr_align_wav.sh`` takes a file path (``${align_dir}/utt_text``) as the second argument.
```bash
cat << EOF > ${align_dir}/utt_text
${base} THE SALE OF THE HOTELS
${base} IS PART OF HOLIDAY'S STRATEGY
${base} TO SELL OFF ASSETS
${base} AND CONCENTRATE
${base} ON PROPERTY MANAGEMENT
EOF
```
```bash
../../../utils/asr_align_wav.sh \
--models ${model} \
--align_dir ${align_dir} \
--align_config ${align_dir}/align.yaml \
${wav} ${align_dir}/utt_text
```
However, the current implementation regards the second argument as *text* not *path to the text file*.
This PR fixes it by accepting either  *text* or *path to the text …

Fix CTC Segmentation

---

test/espnet2/gan_tts/melgan/test_melgan.py

I forgot to add condition to skip in #3516.
https://github.com/espnet/espnet/runs/3421708211?check_suite_focus=true
I don't know why CI is passed in PR stage.

Fix test condition

---

egs2/TEMPLATE/tts1/tts.sh
espnet2/bin/tts_inference.py
espnet2/tasks/abs_task.py
espnet2/tasks/tts.py

This PR is modification of #3526
```python
[ins] In [1]: from espnet2.bin.tts_inference import Text2Speech
[ins] In [2]: tts = Text2Speech.from_pretrained(model_tag=None, vocoder_tag="parallel_wavegan/ljspeech_parallel_wavegan
...: .v1", model_file="../../egs2/ljspeech/tts1/exp/tts_train_conformer_fastspeech2_raw_phn_tacotron_g2p_en_no
...: _space/train.loss.ave_5best.pth")
[ins] In [3]: tts = Text2Speech.from_pretrained("kan-bayashi/ljspeech_tacotron2")
[ins] In [4]: tts = Text2Speech.from_pretrained("kan-bayashi/ljspeech_tacotron2", "parallel_wavegan/ljspeech_parallel_w
...: avegan.v1")
```

Support `from_pretrained` function

---

espnet2/bin/asr_inference.py
espnet2/bin/enh_inference.py
espnet2/bin/k2_asr_inference.py
espnet2/bin/tts_inference.py

This PR supports `from_pretrained` function for ASR and ENH.
```python
[ins] In [1]: from espnet2.bin.asr_inference import Speech2Text
[ins] In [2]: asr = Speech2Text.from_pretrained("Shinji Watanabe/laborotv_asr_train_asr_conformer2_latest33_raw_char_sp_valid.acc.ave")
[ins] In [3]: from espnet2.bin.enh_inference import SeparateSpeech
[ins] In [4]: ss = SeparateSpeech.from_pretrained("Chenda Li/wsj0_2mix_enh_train_enh_rnn_tf_raw_valid.si_snr.ave")
```

Support `from_pretrained` for ASR and ENH

---

egs2/TEMPLATE/asr1/asr.sh

It's a bug from PR #3214 
Default model should be fix into `inference_asr_model=valid.acc.ave.pth`

Fix for default inference model

---

espnet2/asr/encoder/wav2vec2_encoder.py

Related to issue: #3543 . wav2vec2_encoder bug fix: the enc_outputs length becomes None when all the input utterances have the same length.

wav2vec2_encoder bug fix

---

espnet/nets/pytorch_backend/ctc.py

since .eval() will not work for F.dropout

ctc loss using dropout layer since .eval() will not work for F.dropout

---

egs/fisher_callhome_spanish/st1/local/score_bleu.sh
utils/json2trn_mt.py
utils/score_bleu.sh

In current evaluation, we detokenize "tokenized reference" for evaluation. Here, OOV tokens in references are ignored.
This PR recovers such OOV tokens in the references. But, in my experience, this does not change results so much (within 0.05 BLEU).
The same issue still exists in the ASR task.

Avoid tokenization for reference during evaluation

---

espnet2/bin/tts_inference.py
espnet2/gan_tts/joint/joint_text2wav.py
espnet2/gan_tts/vits/generator.py
espnet2/gan_tts/vits/vits.py
espnet2/tts/fastspeech/fastspeech.py
espnet2/tts/fastspeech2/fastspeech2.py
espnet2/tts/tacotron2/tacotron2.py
espnet2/tts/transformer/transformer.py

This PR unify the `spks` / `langs` / `spk_embed_dim` argument type among models.
Now both `None` and `int` can be acceptable.
This change does not affect to the existing config or pretrained models.

Unify spks / lids / spk_embed_dim type

---

espnet2/text/phoneme_tokenizer.py

`pyopenjtalk_g2p_accent` and `pyopenjtalk_g2p_accent_with_pause` output incorrect accent type if the accent type is larger than 9.
For example, according to [pyopenjtalk](https://github.com/r9y9/pyopenjtalk), the accent type of `よろしくお願いします` should be 10 (notice the part `F:11_10` in the output):
```
>>> import pyopenjtalk
>>> pyopenjtalk.extract_fullcontext('よろしくお願いします')[1]
'xx^sil-y+o=r/A:-9+1+11/B:xx-xx_xx/C:09_xx+xx/D:xx+xx_xx/E:xx_xx!xx_xx-xx/F:11_10#0_xx@1_1|1_11/G:xx_xx%xx_xx_xx/H:xx_xx/I:1-11@1+1&1-1|1+11/J:xx_xx/K:1+1-11'
```
However, `pyopenjtalk_g2p_accent` and `pyopenjtalk_g2p_accent_with_pause` return the phoneme and accent list as
```
y 1 -9 o 1 -9 r 1 -8 o 1 -8 sh 1 -7 I 1 -7 k 1 -6 u 1 -6 o 1 -5 n 1 -4 e 1 -4 g 1 -3 a 1 -3 i 1 -2 sh 1 -1 i 1 -1 m 1 0 a 1 0 s 1 1 U 1 1
``` …

Fix pyopenjtalk_g2p_accent(_with_pause)

---

ci/install.sh
ci/test_python.sh
espnet2/asr/frontend/s3prl.py
test/espnet2/asr/frontend/test_s3prl.py
tools/installers/install_s3prl.sh

The official S3PRL repo has made some changes. This PR updates the code.
Due to this [import](https://github.com/s3prl/s3prl/blob/2d9b78c50f9530ce37fb210739f3f28b28503aa6/s3prl/upstream/interfaces.py#L10), the installation becomes necessary.
When installing, I ignored all dependencies, thus previous "kaldi_io" package error no longer exists.

add s3prl test

---

egs2/TEMPLATE/ssl1/hubert.sh
egs2/librispeech/ssl1/README.md
egs2/librispeech/ssl1/local/data_prep.sh
egs2/librispeech/ssl1/run.sh
espnet2/torch_utils/initialize.py

This PR includes following content:
1.  Remove `--use_lm` and other language model related parameters in egs2/TEMPLATE/hubert.sh
2.  Remove `_org` subfolder in stage 3 of egs2/TEMPLATE/hubert.sh to fix the "failed to find data folder" issue.
3.  Add symbolic of Librispeech data preparation in egs2/librispeech/ssl1/local/
4.  Reset bias initialization of `torch.nn.GroupNorm` in `espnet2/torch_utils/initialize.pyL83`
5.  Add README.md to librispeech/ssl1

Fix some issues of  #3512 and add README.md to librispeech/ssl1 recipe.

---

.coveragerc

Most uncovered lines are from tools/fariseq.
https://app.codecov.io/gh/espnet/espnet

Omit tools/ from code coverage.

---

.github/workflows/ci.yaml
.github/workflows/debian9.yml
ci/test_integration_espnet1.sh
ci/test_integration_espnet2.sh
ci/test_utils.sh

I'd like to split test_integration.sh into three components
1. espnet/ and egs/
2. espnet2/ and egs2/
3. utils/
This is because the large one script is annoying especially when new changes are limited to each area. And we can easily know which components are broken or time consuming in CI.

Split test_integration.sh

---

doc/tutorial.md
espnet/nets/beam_search_transducer.py
espnet/nets/pytorch_backend/e2e_asr_transducer.py
espnet/nets/pytorch_backend/transducer/arguments.py
espnet/nets/pytorch_backend/transducer/custom_decoder.py
espnet/nets/pytorch_backend/transducer/error_calculator.py
espnet/nets/pytorch_backend/transducer/initializer.py
espnet/nets/pytorch_backend/transducer/rnn_decoder.py
espnet/nets/pytorch_backend/transducer/rnn_encoder.py
espnet/nets/pytorch_backend/transducer/tdnn.py
espnet/nets/pytorch_backend/transducer/transducer_tasks.py
espnet/nets/pytorch_backend/transducer/transformer_decoder_layer.py
espnet/nets/pytorch_backend/transducer/utils.py
espnet/nets/transducer_decoder_interface.py

- Fix some text and display in `doc/tutorial.md`.
- Add missing doc for some methods' arguments.
- Fix/format some docstrings.
- `transducer` -> `Transducer`

Fix/improve doc(string)s related to Transducer model

---

egs2/swbd/asr1/local/data.sh

I found that stage 7 (LM training) fails in the current recipe due to some duplicates in the Fisher training data. This added line should fix that problem.

Fix SWBD Data Prep Bug

---

espnet2/asr/frontend/s3prl.py

Given that some upstream models in s3prl have 20ms shift, CTC cannot be working for some specific languages because they have a relatively long transcription to the audio. In case of that, we could tile up the upstream features so as to match the fbank precision with 10ms.

Add option to tile up s3prl features

---

ci/install.sh

Matplotlib creates cache when the first import, and maybe it takes time, so I think this change can fix the ci error.

Create matplotlib cache in ci/install.sh to fix CI error

---

ci/install.sh
espnet2/asr/ctc.py
test/espnet2/asr/test_ctc.py
tools/Makefile

This PR is for adding `ctc_type=gtnctc` to ESPnet2. Implementation follows the same as in ESPnet1.
Confirmed the results on an4 and added unit tests.

GTN CTC for ESPnet2

---

egs2/TEMPLATE/enh1/enh.sh

In `enh.sh`, only `sound` as input speech type was used. Following `asr.sh`, the `kaldi_ark` type can be used as well now.

modified data type in enh.sh

---

espnet2/asr/frontend/s3prl.py

Update: Setting `layerdrop` before `Featurizer initialization`.
The error is from this [part](https://github.com/s3prl/s3prl/blob/3854f33867f3136ab97f5389578f4355ef6c660e/s3prl/upstream/interfaces.py#L214).

update s3prl frontend w.r.t. recent modification in s3prl interface

---

espnet/nets/pytorch_backend/transducer/utils.py

Just come across this function and think it is probably supposed to sort in descending order of logprob.
Correct me if it is wrong

fix the sort order in select_k_expansions()

---

espnet2/enh/layers/dnn_beamformer.py

Add an EPS in amplitude calculatation for complex tensor to improve numerical stability.
Otherwise, the gradient of zero square root may be NaN.

add eps in  beam-forming reference channel selection

---

egs2/TEMPLATE/tts1/tts.sh

lang2lid is not generated correctly.
utt2lid should be replaced with lang2lid.

bugfix lang2lid in tts.sh

---

espnet2/text/phoneme_tokenizer.py
tools/installers/install_phonemizer.sh

Current phonemizer-based G2P is unstable and too slow due to the bad usage of the phonemizer library.
This PR fixed this issue. 
- Old: Construct the instance at every g2p processing
- New: Construct the instance in `__init__` and call at every g2p processing
Now phonemizer-based on-the-fly G2P works reasonably.

Refactor Phonemizer-based G2P

---

egs2/seame/asr1/README.md
egs2/seame/asr1/local/score.sh
egs2/seame/asr1/local/split_lang_trn.py

I add a `local/score.sh` to separately scoring Mandarin CER and English WER in the `egs2/seame` recipe.
New results are also added in `README.md`.

Scoring Mandarin / English separately for the SEAME corpus

---

espnet/nets/pytorch_backend/conformer/contextual_block_encoder_layer.py
espnet/nets/pytorch_backend/transformer/contextual_block_encoder_layer.py
espnet2/asr/encoder/contextual_block_conformer_encoder.py
espnet2/asr/encoder/contextual_block_transformer_encoder.py

This PR is related to the discussion 
https://github.com/espnet/espnet/discussions/3971
After looking into the codes, I found that the arguments are wrongly passed among the layers.
The forward method of ContextualBlockEncoderLayer requires 8 parameters as 
https://github.com/espnet/espnet/blob/d4287afdd18e5a2dfec52119388b8d49f0be4ff8/espnet/nets/pytorch_backend/conformer/contextual_block_encoder_layer.py#L75
where it should be noted that layer_idx is the 7th parameter.
However, the forward_train method returns 6 values as 
https://github.com/espnet/espnet/blob/d4287afdd18e5a2dfec52119388b8d49f0be4ff8/espnet/nets/pytorch_backend/conformer/contextual_block_encoder_layer.py#L194
and the last value of layer_idx is inputted as a parameter of is_short_segment to the next layer, which means …

streaming conformer bugfix

---

egs2/iwslt22_dialect/asr1/local/data.sh
egs2/iwslt22_dialect/asr1/run.sh
egs2/iwslt22_dialect/st1/local/data.sh
egs2/iwslt22_dialect/st1/run.sh

@sw005320 I need to patch a bug in the data prep stage for this recipe. 
Thanks @siddalmia for the bug report!

[bug patch] egs2/iwslt22_dialect

---

espnet2/main_funcs/average_nbest_models.py
espnet2/train/trainer.py

Hi, this PR adds a suffix to the averaged model file name, if `nbest_averaging_interval` is used.
After every `nbest_averaging_interval` epochs, an averaged checkpoint will be saved with a suffix `till{xx}epoch.pth`. This is a unique name, so the previously saved model files will not be overwritten.
Note that the suffix is not added to the final averaged model after all epochs.

Add an optional suffix to the averaged model file name

---

doc/espnet2_tutorial.md

Hi, in ESPnet2, I think the argument name for asr training config should be `--asr_config` instead of `--asr_train_config`. I modified it in the documentation. I also saw a typo in the same file: `upstream` vs `upsteam`.

Fix argument name asr_config in ESPnet2 doc

---

egs2/librispeech_100/asr1/README.md
egs2/librispeech_100/asr1/conf/tuning/train_asr_transformer_win400_hop160_ctc0.3_lr2e-3_warmup15k_timemask5_amp_no-deterministic.yaml

Hi, here is the Transformer baseline for LibriSpeech 100h. The Transformer encoder has 18 layers. As expected, the performance of Transformer is worse than that of Conformer.

Add transformer results for LibriSpeech 100h

---

egs2/librispeech_100/asr1/conf/tuning/decode_ctc_bs1.yaml
egs2/librispeech_100/asr1/conf/tuning/train_conformer_ctc.yaml
egs2/librispeech_100/asr1/conf/tuning/train_conformer_interctc.yaml
egs2/librispeech_100/asr1/conf/tuning/train_conformer_scctc.yaml
espnet2/asr/ctc.py
espnet2/asr/encoder/conformer_encoder.py
espnet2/asr/encoder/transformer_encoder.py
espnet2/asr/espnet_model.py
espnet2/bin/asr_inference.py

This PR adds implementations for Intermediate/Self-conditioned CTC (Inter/SC-CTC) on espnet2, along with a strong baseline configuration for training a pure Conformer-CTC model. I'm still running some experiments to verify that the implementation is accurate and after that I will add the results.

[ESPnet2] Intermediate/Self-conditioned CTC

---

doc/installation.md

Hi, I updated the example PyTorch and CUDA version in the installation doc to avoid confusion. Originally, the PyTorch version was 1.3.1, but according to https://github.com/espnet/espnet/pull/4038, it is no longer supported.

Update the example PyTorch version in Installation doc

---

egs2/TEMPLATE/st1/st.sh

Hi, in `st.sh`, the source and target texts should be merged before tokenization, if `token_joint` is `True`.
This modification is based on the same stage in `mt.sh`. Please check if it's correct.

Fix joint tokenization in st.sh

---

egs2/TEMPLATE/mt1/mt.sh
egs2/TEMPLATE/st1/st.sh
espnet2/bin/mt_inference.py

This PR is meant to fix minor mistakes in the scoring -

scoring fixes MT and ST

---

egs2/librispeech/asr1/README.md
egs2/librispeech/asr1/conf/train_asr_confformer.yaml
egs2/librispeech/asr1/conf/train_asr_conformer.yaml
egs2/librispeech/asr1/conf/tuning/train_asr_conformer10_hop_length160.yaml
egs2/librispeech/asr1/run.sh

Hi, I am sharing a new Conformer config for LibriSpeech 960h. The `hop_length` in `frontend_conf` is reduced from 256 to 160. I will update the results once the decoding finishes. Currently, the WERs on dev/test-other sets are lower without an LM.

Add new conformer config with hop length 160 for LibriSpeech 960h

---

.gitmodules
ci/doc.sh
doc/.gitignore
doc/index.rst
doc/notebook2rst.sh

I just noticed our gh-page doc does NOT contain notebooks https://espnet.github.io/espnet/
This is because our gh action forget submodules. Moreover, the submodule was **not updated for two years**.
For simplicity, we should clone the latest snapshot and generate rst during build. See https://karita.xyz/espnet/ for the updated doc

Fix notebook in the official doc.

---

egs2/zh_openslr38/asr1/local/check_train_test_duplicate.py
tools/installers/install_longformer.sh

Longformer depends on pytorch-lightning, which requires torch>=1.8.*. [link](https://github.com/PyTorchLightning/pytorch-lightning/blob/3e808b8a7002f13970c9d6f449fb2bb1042b9b98/requirements.txt#L4)

fix issues about longformer package upgrades pytorch package

---

setup.py

Doc CI is failing now because of a Jinja2 version issue. 
- Our current sphinx version explicitly depends on environmentfilter from jinja2, which was depreciated recently. 
- Trying to import this module without pinning to an old jinja2 would cause the ImportError and fail the doc CI process. 
- More details can be seen in this issue: https://github.com/sphinx-doc/sphinx/issues/10291
The latest sphinx (>4.0.5) seems to already handle this issue, but because we are depending on an old version (2.1.2), we still have this issue. Maybe we should consider upgrading sphinx version in the future.
- As suggested in the previous issue, pinning jinja to an old version should solve this issue. 
- I have verified that this import error did not happen after pinning in my local environment.

fix doc ci by pinning jinja version

---

espnet2/bin/tts_inference.py

I added a parameter upon initialization of the Text2Speech object, which, when set to True will cause the vocoder model to receive normalized features rather than denormalized, when both are present in acoustic model output. The default value of this parameter is False so this should not cause any changes elsewhere.

Add option to use norm. feats over denorm.

---

.github/workflows/docker.yml

Minor fix for trigger git action for docker. It should be launched 6 days ago, but it was skipped.
I assume that the issues is because comparing true with 'true'

Github Action Trigger Docker Build

---

egs2/TEMPLATE/asr1/scripts/utils/show_translation_result.sh
egs2/TEMPLATE/mt1/mt.sh
egs2/iwslt14/mt1/run.sh

Hi, this PR fixes some issues and updates `show_translation_result.sh` to show all the decoding results in a specified exp directory. Previously, it could only show one test set in one decoding directory and there was a typo in `mt.sh`.

Update show_translation_result.sh to show all decoding results under the given exp directory

---

espnet2/enh/loss/wrappers/pit_solver.py

This PR fixes the bug that stats cannot be correctly counted when permutation invariant training (PIT) is applied.

Fix a bug in stats aggregation when PITSolver is used

---

espnet2/asr/maskctc_model.py

This PR adds `**kwargs` to the forward function of maskctc_model.py, which is required due to the [recent change](https://github.com/espnet/espnet/commit/dd408fc59a634eb8dac4bac87ad7288ce7493be4#diff-cb8db0cbd22ec7ef4211eda6fb02373b3d781248205b935ecf6cfce7e2030c8fR164) in espnet_model.py.

Minor fix for Mask-CTC forward function

---

espnet/nets/pytorch_backend/rnn/encoders.py
espnet2/bin/asr_inference.py
test/espnet2/bin/test_asr_inference.py

The dynamic quantization option is enabled in `asr_inference.py` for ESPnet2. I'm running an inference experiment on LibriSpeech 960h test other. I'll share the result soon.

Add quantization in ESPnet2 for asr inference

---

egs2/kss/tts1/conf/tuning/train_jets.yaml
egs2/ljspeech/tts1/conf/tuning/train_jets.yaml
espnet2/gan_tts/jets/__init__.py
espnet2/gan_tts/jets/alignments.py
espnet2/gan_tts/jets/generator.py
espnet2/gan_tts/jets/jets.py
espnet2/gan_tts/jets/length_regulator.py
espnet2/gan_tts/jets/loss.py
espnet2/tasks/gan_tts.py
espnet2/tasks/tts.py
test/espnet2/gan_tts/jets/test_jets.py

Hi, thanks for your great works; espnet
I experimented the e2e tts model (JETS) recently following 
paper: https://arxiv.org/abs/2203.16852
code: https://github.com/imdanboy/jets
and get some reasonable results on ljspeech, kss dataset.
Most part of the code is based on fastspeech2 and hifi-gan of espnet. It would be honor if it can be implemented in espnet.
I think an alignment module, related to an text-speech alignment learning, would be helpful at least to simplify the training of non-autoregressive tts model such as fastspeech.
Thanks.

add e2e tts model: JETS

---

tools/installers/install_s3prl.sh

This is a temporal solution by using a legacy version. The new features like data2vec is not supported. I will test the compatibility of new fairseq and s3prl versions.

fix s3prl install by using legacy version. Temporal solution.

---

espnet2/asr/ctc.py

When I implemented `ignore_nan_grad` for  ctc modules of espnet2, pytorch-ctc didn't have the zero_infinity option.
`ignore_nan_grad` is not so efficient and looks complicated impelemetation, so I changed it to use  the `zero_infinity` option. (ESPnet1 already used it.)
Note that this CTC class has both  `ignore_nan_grad` and `zero_infinity`  options and `ignore_nan_grad`  is an alias of `zero_infinity`. I left  `ignore_nan_grad` for backward compatiblity.

Zero_infinity option for ctc loss

---

egs2/TEMPLATE/asr1/pyscripts/utils/plot_sinc_filters.py
espnet/nets/chainer_backend/transformer/subsampling.py
espnet/nets/pytorch_backend/e2e_st.py
espnet/nets/pytorch_backend/frontends/mask_estimator.py
espnet/nets/pytorch_backend/nets_utils.py
espnet2/asr/encoder/rnn_encoder.py
espnet2/asr/encoder/vgg_rnn_encoder.py
espnet2/enh/layers/mask_estimator.py
setup.py
tools/Makefile

Maybe the issue of new NumPy has been fixed since our ci was not failed.

Remove the version restriction for numpy

---

test/espnet2/enh/test_espnet_model.py

This PR fixes the bug in `test/espnet2/enh/test_espnet_model.py`.

Fix a bug in enh unit test

---

doc/espnet2_distributed.md
doc/espnet2_tutorial.md
doc/tutorial.md

We have noticed that many users encountered this issue when using multiple GPUs on ESPnet2. Based on various investigations, ESPnet2 actually has good multi-GPU scalability, if the batch size is properly set.
Note that the behavior of batch size in ESPnet2 during multi-GPU training is different from that in ESPnet1. **In ESPnet2, the total batch size is not changed regardless of the number of GPUs.** Therefore, you need to manually increase the batch size if you increase the number of GPUs. Please refer to this [doc](https://espnet.github.io/espnet/espnet2_training_option.html#the-relation-between-mini-batch-size-and-number-of-gpus) for more information.

Add notes on batch size and num of GPUs in ESPnet2 documentation

---

egs2/dns_icassp21/enh1/local/data.sh
egs2/dns_ins21/enh1/local/data.sh

Based on [this issue](https://github.com/espnet/espnet/issues/4414), I updated comments in data.sh for the DNS challenges (dns_ins21 and dns_icassp21). This would help you to prepare data that is not downloaded by the script provided by the challenge organizer.

Update notes in the recipes for DNS challenges 

---

egs2/americasnlp22/asr1/README.md
egs2/americasnlp22/asr1/local/data.sh
egs2/americasnlp22/asr1/run.sh

This is to match the codes used last year, hopefully that's fine.

Update language codes in AmericasNLP 2022 baseline

---

setup.py
tools/Makefile

Numpy=1.22 has been released,  and it seems to have a problem with our matplotlib version.
I fixed numpy-version to <=1.21.4.

Temporary fixed numpy version

---

espnet/asr/pytorch_backend/asr.py
espnet/bin/asr_train.py
espnet/distributed/__init__.py
espnet/distributed/pytorch_backend/launch.py
espnet/utils/dataset.py
test/test_distributed_launch.py

This PR is related to #4377. As I described at a comment on the issue, this PR includes:
- adding a new script to launch multiple processes on each GPU like `pytorch's torch.distributed.launch`,
- adding a new option, `--use-ddp`, to `asr_train.py` to switch DDP and standard `data_parallel` when specifying multiple GPUs,
- changing evaluation schemes to distributed version,
- replacing a way to split dataset with pytorch's `DistributedSampler`,
- suppressing saving a checkpoint, intermediate info, plots, etc from non-main processes.
Please let me know if we need to discuss more about the changes.

Add DDP support for v1 ASR training.

---

egs2/TEMPLATE/asr1/scripts/utils/TEMPLATE_HF_Readme.md

Add a note to follow the installation instructions

---

egs2/aishell2/asr1/conf/tuning/train_asr_conformer.yaml
egs2/aishell2/asr1/conf/tuning/transducer/train_conformer-rnn_transducer.yaml

This PR is to add the GPU info in the training config files. 
For both hybrid CTC/Attention frameworks and transducer frameworks, I'm using 8 V100 GPUs and the training will take around 4 days

Aishell-2 GPU info

---

test/test_distributed_launch.py

Hi,
Some tests related to distributed launch seem to timeout a lot recently, more precisely [this one](https://github.com/espnet/espnet/blob/master/test/test_distributed_launch.py#L95=) and [this one](https://github.com/espnet/espnet/blob/master/test/test_distributed_launch.py#L124=).
On my side, the execution time is as follow:
```bash
3.02s call     test/test_distributed_launch.py::test_worker_exits_nonzero_code_ng[2-2]
3.02s call     test/test_distributed_launch.py::test_worker_raises_exception_ng[2]
3.02s call     test/test_distributed_launch.py::test_worker_exits_nonzero_code_ng[2-1]
2.01s call     test/test_distributed_launch.py::test_simple_function_ok_with_right_envvar[1]
2.01s call     test/test_distributed_launch.py::test_simple_function_ok_with_right_envvar[2]
2.01s call …
```

Fix distributed launch tests

---

espnet/nets/pytorch_backend/transformer/attention.py

We encountered an issue when data type is not float. In our case, we were using bfloat16.
```
File "/espnet/espnet/nets/pytorch_backend/transformer/attention.py", line 83, in forward_attention
scores = scores.masked_fill(mask, min_value)
RuntimeError: value cannot be converted to type at::BFloat16 without overflow
```
To fix it, we use `torch.finfo` and set the correct min value based on the `torch.dtype`.
From the output below, it shows that torch.float32 min is less than the min of torch.bfloat16, thus causing the overflow error. 
```
In [4]: torch.finfo(torch.float32).min
Out[4]: -3.4028234663852886e+38In 
[5]: torch.finfo(torch.bfloat16).min
Out[5]: -3.3895313892515355e+38 
```

use torch.finfo for dtype other than float

---

ci/test_python.sh
egs2/americasnlp22/asr1/conf/train_asr_transformer.yaml
egs2/catslu/asr1/conf/train_asr.yaml
egs2/mr_openslr64/asr1/conf/tuning/train_asr_conformer_xlsr.yaml
egs2/ms_indic_18/asr1/README.md
egs2/ms_indic_18/asr1/conf/tuning/train_asr_xlsr53_conformer.yaml
espnet2/asr/frontend/s3prl.py
espnet2/torch_utils/initialize.py
test/espnet2/asr/frontend/test_s3prl.py
tools/installers/install_s3prl.sh

This PR is to update the S3PRL frontend, because s3prl has some updates recently.
Reference: https://s3prl.github.io/s3prl/tutorial/upstream_collection.html
A duplicated PR: https://github.com/espnet/espnet/pull/4593
Completed items:
* s3prl frontend
* Installation script
* Test script
* When using fused frontend, [parameter initialization](https://github.com/espnet/espnet/blob/f51b3be88acc88509d140467b7593b9e1f48cd4d/espnet2/torch_utils/initialize.py#L104) of s3prl frontend acually was actually not called.
Items still working on

Update to fit the recent update in s3prl.

---

espnet2/tasks/abs_task.py

The current version of wandb requires a `dir` parameter of type `str` in `wandb.init()`.
```log
wandb: WARNING Invalid value for property root_dir: experiments/22k/tts_train_multi_spk_vits_raw_phn_none. This will raise an error in the future.
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
run = wi.init()
File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 553, in init
manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 161, in _inform_init
svc_iface._svc_inform_init(settings=settings, run_id=run_id)
File "/usr/local/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 36, …
```

Pass output_dir as str to wandb.init()

---

egs2/TEMPLATE/tts1/tts.sh

Stage 3 of `tts.sh` removes long/short data. At this time, authors use `utils/fix_data_dir.sh` to remove the entry of the removed utterance as follows:
https://github.com/espnet/espnet/blob/e5d133c21800116b2fc5844859333ef83163d293/egs2/TEMPLATE/tts1/tts.sh#L500-L509
However, if there exist both `utt2sid` and `utt2lid`, `_fix_opts` are overwritten as `"--utt_extra_files utt2lid "` because authors used the assignment operator. So I tried to fix the above code as follows:
```bash
_fix_opts=""
if [ -e "${data_feats}/org/${dset}/utt2sid" ]; then
_fix_opts+="--utt_extra_files utt2sid "
fi
if [ -e "${data_feats}/org/${dset}/utt2lid" ]; then
_fix_opts+="--utt_extra_files utt2lid "
fi
utils/fix_data_dir.sh ${_fix_opts} "${data_feats}/${dset}"
```
However, after I tested it, it seems that …

Fix both utt2sid and utt2lid when removing long/short data

---

egs2/covost2/st1/conf/tuning/train_transformer_st.yaml

batch_bins does not work for folded batching, need to set to batch_size to be working

recipe config update

---

doc/espnet2_tutorial.md
espnet2/asr_transducer/activation.py
espnet2/asr_transducer/beam_search_transducer.py
espnet2/asr_transducer/decoder/rnn_decoder.py
espnet2/asr_transducer/decoder/stateless_decoder.py
espnet2/asr_transducer/encoder/blocks/branchformer.py
espnet2/asr_transducer/encoder/blocks/conformer.py
espnet2/asr_transducer/encoder/blocks/conv1d.py
espnet2/asr_transducer/encoder/building.py
espnet2/asr_transducer/encoder/encoder.py
espnet2/asr_transducer/encoder/modules/convolution.py
espnet2/asr_transducer/encoder/modules/multi_blocks.py
espnet2/asr_transducer/encoder/modules/normalization.py
espnet2/asr_transducer/encoder/validation.py
espnet2/asr_transducer/error_calculator.py
espnet2/asr_transducer/espnet_transducer_model.py
espnet2/asr_transducer/joint_network.py
espnet2/asr_transducer/utils.py
espnet2/bin/asr_transducer_inference.py
espnet2/tasks/asr_transducer.py
test/espnet2/asr_transducer/test_activation.py
test/espnet2/asr_transducer/test_encoder.py
test/espnet2/asr_transducer/test_espnet_transducer_model.py
test/espnet2/bin/test_asr_transducer_inference.py

Hi,
This PR add Branchformer block with offline and streaming capabilities to the new Transducer version.
Btw, I need to redesign the units tests in the future, it'll become a mess if I pile up block tests. It's OK for now because the other block types aren't a priority.
Also, as follow up to #4479:
- Set the conv mod normalization module for Conformer to `BatchNorm1d`. Subsequently, the type was removed from `get_normalization(...)`.
- Fix some main and Conformer parameters in the ESPnet2 tutorial doc.
- Moved the dynamic chunk training parameters description from Encoder section to Streaming section.

Offline/Online Branchformer Transducer

---

egs2/TEMPLATE/svs1/pyscripts/feats
egs2/TEMPLATE/svs1/utils
espnet2/bin/svs_inference.py
espnet2/svs/espnet_model.py
espnet2/svs/feats_extract/score_feats_extract.py
espnet2/svs/naive_rnn/naive_rnn_dp.py
espnet2/tasks/svs.py
espnet2/train/preprocessor.py

Hi @ftshijt, here are new updates.
- Add model naive_rnn_dp. All stages have been tested. Result sounds great after 100 epochs. The rest is still running.
- Add new feature `beat`.
- Add SyllableScoreFeats.
- Reorganize two sets of features by segmenting from label or from xml.
- Unify feature names, mainly focusing on `label` and `midi`.

Muskit: rename & reorganize features

---

setup.py

Fix CI error due to the version up of importlib-metadata.
https://github.com/espnet/espnet/actions/runs/3174416926/jobs/5171182884#step:8:8419
https://importlib-metadata.readthedocs.io/en/latest/history.html#v5-0-0

Fix importlib-metadata version

---

espnet2/asr_transducer/encoder/blocks/conv_input.py
espnet2/asr_transducer/encoder/validation.py
test/espnet2/asr_transducer/test_encoder.py

This is a follow up for #4714. Basically:
- Support subsampling factor of 4 and 6 for VGG
- Create boolean mask according to output size only.
About the second point: basically, we don't need to ensure the "correct" items are removed according to the convolution/max pooling operations. Padding values will be removed anyway and subsequent mask for streaming is created from the output of ConvInput.

Update ConvInput for Transducer

---

doc/espnet2_tutorial.md

Missing commit for #4720. I'm manually merging as it only impact one line in doc.

Fix input block tutorial documentation for Transducer

---

egs2/chime4/enh1/conf/tuning/train_enh_convtasnet_small.yaml
egs2/lt_slurp_spatialized/enh1/conf/tuning/train_enh_conv_tasnet.yaml
egs2/wsj0_2mix/enh1/conf/tuning/train_enh_dptnet.yaml

Reminded by https://github.com/espnet/espnet/issues/4716, I checked through all existing enh config files in `egs2/*/enh1/conf/tuning/*.yaml` and found three outdated config files that cannot be used with the latest code.
This PR fixes these config files.

Update outdated enh config files

---

espnet2/asr_transducer/encoder/modules/attention.py

in [espnet2/asr_transducer/encoder/modules/attention.py](https://github.com/espnet/espnet/blob/master/espnet2/asr_transducer/encoder/modules/attention.py),
masked_fill fills elements of tensor with 0 where mask is True, so the value of the mask should be True if chunk_mask is true or (instead of and) source mask is true.

chunk_mask error

---

espnet2/asr/encoder/wav2vec2_encoder.py

As @kehanlu  suggested in #4768 , this PR is to fix the masking bug.

fix wav2vec2 encoder mask bug

---

espnet2/tasks/gan_tts.py
espnet2/tasks/tts.py
espnet2/text/token_id_converter.py

As reported in #4718,  whitespace```(' ')``` (word separator token in g2p_en, g2pk) is not parsed correctly. 
```token_list = [line.rstrip() for line in f]```
Currently when parsing each tokens from the line, ```str.rstrip``` removes not only ```'\n'``` but also whitespace token ```' '```
Therefore I suggest following method for parsing token_list
```token_list = [line[0] + line[1:].rstrip() for line in f]```

fix parsing token_list

---

egs2/sms_wsj/enh1/conf/tuning/train_enh_beamformer_no_wpe.yaml
egs2/sms_wsj/enh1/run.sh
egs2/wham/enh1/run.sh
egs2/whamr/enh1/README.md
egs2/whamr/enh1/conf/tuning/train_enh_beamformer_mvdr.yaml
egs2/whamr/enh1/conf/tuning/train_enh_beamformer_wmpdr.yaml
egs2/whamr/enh1/run.sh

I added `--audio_format wav` option to `run.sh` for WHAM!, WHAMR! and SMS-WSJ, based on discussion with @Emrys365. Since their data generation scripts use `32-bit Floating Point PCM`, the conversion to `16-bit Signed Integer PCM` in the stage 3 does not work well (in detail, [this part](https://github.com/espnet/espnet/blob/cb06bb1a9e5e5355a02d8c1871a8ecfafd54754d/egs2/TEMPLATE/asr1/pyscripts/audio/format_wav_scp.py#L186)). In addition, I updated outdated config files in the three recipes.
Note that I only ran the recipe for WHAMR!.

Fix an audio format issue in some enh recipes

---

doc/espnet2_tutorial.md

fix typo in espnet2_tutorial.md

---

espnet2/layers/stft.py
test/espnet2/layers/test_stft.py

This PR fixes the `librosa.stft` call in the default frontend.
The default parameter of the `pad_mode` for `torch.stft` and `librosa.stft` is different, so we need to use the same value to get the same output.

Fixed pad mode for librosa.stft

---

egs2/gigaspeech/asr1/local/data.sh

Hi, the original data prep script seems not working. Probably the interface of the `GigaSpeech` repo has changed. The new usage can be found here: https://github.com/SpeechColab/GigaSpeech/blob/main/toolkits/kaldi/gigaspeech_data_prep.sh#L67

Fix data prep in GigaSpeech

---

egs2/TEMPLATE/asr1/db.sh

The variable `VOXFORGE` is duplicated in `db.sh`: [line 81](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/db.sh#L81) and [line 157](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/db.sh#L157).

Remove duplicated VOXFORGE in db.sh (line81 and line157)

---

espnet/nets/batch_beam_search_online_sim.py
espnet/nets/beam_search.py

Add a warning statement when the hypo length equals the max out length.
The user should consider increasing the `maxlenratio` to avoid the decoding being stopped incorrectly by the max out length limitation.

Add a warning statement when the hypo length equals to the max out length.

---

egs2/librispeech/asr1/README.md

This PR is about updating README for E-Branchformer results on Librispeech.
I also add a description about an uploaded E-Branchformer model on Huggingface repo.

Add E-Branchformer results on Librispeech

---

README.md

Related to https://github.com/espnet/espnet/pull/4845#issuecomment-1379728417

Update README.md related to ASR architecture

---

egs2/librispeech/ssl1/local/path.sh

This is as suggested in #4747 
This is true. I suggest checking if torchaudio is 0.13.1 or nightly version, not only because of the AMP issue, but also there is new model initialization which is important to HuBERT pre-training.
_Originally posted by @nateanl in https://github.com/espnet/espnet/issues/4747#issuecomment-1380832647_

Add torchaudio version check for HuBERT pretraining

---

egs2/aphasiabank/asr1/README.md
egs2/aphasiabank/asr1/conf/tuning/train_asr_ebranchformer_small_wavlm_large1.yaml
egs2/aphasiabank/asr1/run.sh
espnet/nets/pytorch_backend/transformer/subsampling.py
espnet2/asr/encoder/branchformer_encoder.py
espnet2/asr/encoder/conformer_encoder.py
espnet2/asr/encoder/e_branchformer_encoder.py
espnet2/asr/encoder/longformer_encoder.py
espnet2/asr/encoder/transformer_encoder.py
espnet2/asr/encoder/transformer_encoder_multispkr.py
test/espnet2/asr/encoder/test_branchformer_encoder.py
test/espnet2/asr/encoder/test_conformer_encoder.py
test/espnet2/asr/encoder/test_e_branchformer_encoder.py
test/espnet2/asr/encoder/test_longformer_encoder.py

`Conv2dSubsampling1` module is similar to `Conv2dSubsampling` except the subsampling ratio is 1:1.
AphasiaBank English ASR experiments using E-Branchformer+WavLM showed a CER decrease from 17.7 to 17.0 by switching from `Conv2dSubsampling2` to `Conv2dSubsampling1`.
The user can specify `input_layer: conv2d1` in the encoder configuration to use this module.

Add Conv2dSubsampling1 module and test it in AphasiaBank ASR recipe

---

egs2/TEMPLATE/asr1/asr.sh
egs2/TEMPLATE/diar1/diar.sh
egs2/TEMPLATE/enh1/enh.sh
egs2/TEMPLATE/enh_asr1/enh_asr.sh
egs2/TEMPLATE/enh_st1/enh_st.sh
egs2/TEMPLATE/slu1/slu.sh
egs2/TEMPLATE/ssl1/hubert.sh
egs2/TEMPLATE/st1/st.sh
egs2/TEMPLATE/svs1/svs.sh
egs2/TEMPLATE/tts1/tts.sh
espnet2/asr/espnet_model.py
espnet2/main_funcs/collect_stats.py
espnet2/slu/espnet_model.py
espnet2/st/espnet_model.py
espnet2/tasks/abs_task.py

If utt_mvn is used and `extract_feats_in_collect_stats` is False in config, the scripts would skip building model and no dummy features are generated.
This can reduce the memory usage in Stage 10 when large SSL models are used, e.g. HuBERT.

Update collect stats stage so that less memory cost in Utt_mvn

---

egs/lrs/README.md

Fix typo in lrs/README.md

---

espnet2/layers/stft.py

See discussion in https://github.com/espnet/espnet/issues/4919

Use native CPU version of STFT on newer pytorch versions, fix librosa window size < ftt

---

egs2/TEMPLATE/enh1/enh.sh
egs2/librimix/enh1/local/data.sh
egs2/librimix/tse1/run.sh
espnet2/bin/enh_tse_inference.py
espnet2/enh/espnet_model_tse.py
espnet2/iterators/chunk_iter_factory.py
espnet2/train/preprocessor.py

This PR fixes existing bugs in the newly added TSE task. Some of them are critical that severely impede model training.
Bug fixes:
* `egs2/TEMPLATE/enh1/enh.sh`: enroll_spk?.scp files can be now correctly processed in Stage 3.
* `egs2/librimix/tse1/run.sh`: fixed a typo
* `espnet2/bin/enh_tse_inference.py`: `shared_encoder` can now take effect correctly in the inference stage.
* `espnet2/train/preprocessor.py`: Fixed a critical bug that prepares wrong TSE training data when provided `speech_ref` data does not sum up to `speech_mix`
Typo fixing:
* `espnet2/enh/espnet_model_tse.py`
To be discussed:
* `espnet2/iterators/chunk_iter_factory.py`: To support chunk-based iterator for the TSE task, I have to add some hacks to this file. If you think the hacks make the script too messy, I can …

Fix existing bugs in the TSE task

---

ci/test_integration_espnet2.sh
espnet2/asr/espnet_model.py
espnet2/tasks/asr.py
test/espnet2/bin/test_asr_align.py
test/espnet2/bin/test_asr_inference.py
test/espnet2/bin/test_asr_inference_k2.py
test/espnet2/bin/test_enh_inference.py

Tries to fix the issues in https://github.com/espnet/espnet/issues/4908

set default none decoder for ASR

---

espnet/nets/batch_beam_search.py
espnet2/layers/stft.py

When we do this with `torch >= 0.12.1`:
speech2text = Speech2Text(...)
PyTorch emits a couple of deprecation warnings:
UserWarning: __floordiv__ is deprecated, and its behavior will
change in a future version of pytorch. It currently rounds toward 0
(like the 'trunc' function NOT 'floor'). This results in incorrect
rounding for negative values. To keep the current behavior, use
torch.div(a, b, rounding_mode='trunc')
Fix the problematic code accordingly, so that users won't see confusing warnings.

Fix '__floordiv__ is deprecated' warnings 

---

espnet2/bin/enh_inference.py

Fix the issue reported in https://github.com/espnet/espnet/discussions/4970.

Fix a 'ref_channel'-related issue in espnet2/bin/enh_inference.py

---

egs2/msuperb/asr1/local/lid.py
egs2/msuperb/asr1/local/score.sh
egs2/msuperb/asr1/local/split_results.py

Fully decouple LID scoring and TER scoring, and parse LID directly from the text file. The previous version is bugged when dealing with [org_jpn].

LID score v2

---

setup.py

On 14th of March version `3.0.0` of `typeguard` has been released, it contains breaking changes so there are import failures importing certain `espnet` modules that also import `typeguard`.
This PR fixes the issue by pinning the version to latest non breaking one.
I decided to go this way since it's easist fix, updating all the imports would take much more time and I don't have enough knowledge about the codebase to do it correctly.

Fix typeguard version

---

egs2/iwslt22_low_resource/st1/RESULTS.md
egs2/iwslt22_low_resource/st1/conf/decode_st_full_transformer.yaml
egs2/iwslt22_low_resource/st1/conf/decode_st_transformer.yaml
egs2/iwslt22_low_resource/st1/conf/tuning/decode_pen3.yaml
egs2/iwslt22_low_resource/st1/conf/tuning/decode_pen4.yaml
egs2/iwslt22_low_resource/st1/run.sh

Tune decode penalty for better performance in terms of BLUE score.
clean_set: from 2.6 --> 2.7 (BLUE score) / 0.2 --> 0.4 (penalty)
full_set: from 3.6 --> 3.7 (BLUE score) /  0.2 --> 0.3 (penalty)
|dataset|score|verbose_score|
|---|---|---|
|decode_st_transformer_st_model_valid.acc.ave/test|2.7|22.1/4.6/1.9/0.8 (BP = 0.756 ratio = 0.782 hyp_len = 17593 ref_len = 22504)|
|dataset|score|verbose_score|
|---|---|---|
|decode_st_full_transformer_st_model_valid.acc.ave/test|3.7|24.4/5.2/2.0/0.9 (BP = 0.928 ratio = 0.931 hyp_len = 20945 ref_len = 22504)|

[Tuning] iwslt22 low-resource ST decode configuration tuning

---

ci/test_integration_espnet2.sh
egs2/TEMPLATE/asr1/asr.sh

This PR includes my self-answer to #4944.
- I changed `asr.sh` to raise an error if `--train_set` equal to `--valid_set`,  or `--train_set` is also included in `--test_sets`.
- If `--valid_set` is included in `--test_sets`, `--eval_valid_set` option is enabled. 
-  if `--eval_valid_set` is enabled, `dump/org/${valid_set}` is evaluated at the decoding stage instead of `dump/${valid_set}`
Someone might still think we should filter the long/short utterances in the training python process, but finally, I concluded it's a bad idea. Please let me go in this direction.
I also changed the behavior of the `--skip_train` option:
- Before this PR: The data preparation for `${train_set}` and `${valid_set}` still works. This is inconvinient if using a pre-trained model and evaluation is only required. …

Modify asr.sh

---

.gitignore

Two `tools/anaconda` exist in `.gitignore` (line 83 and 88), but `tools/miniconda` is missing. If we follow the [installation doc](https://espnet.github.io/espnet/installation.html), we will create a directory named `miniconda`, which should be excluded in git.

Add miniconda in gitignore

---

espnet/nets/beam_search.py

This PR fixes the condition of warning that best hypo length is equal to max length in beam search.

Fix the condition for maxlen warning in beam search

---

espnet2/tasks/abs_task.py

This is related to #4910 .
Thanks @boeddeker for the solution!

Bug Fix: pretrained s3prl-frontend based models loaded with parameters key mismatch error

---

espnet2/asr/encoder/e_branchformer_encoder.py
espnet2/bin/asr_inference.py
test/espnet2/asr/encoder/test_e_branchformer_encoder.py
test/espnet2/bin/test_asr_inference.py

This was originally written by @wanchichen.
The implementation is nearly the same as InterCTC in `TransformerEncoder` and `ConformerEncoder`.
The output is saved at `path/to/asr_decode_dir/test_set/logdir/output.*/1best_recog/encoder_interctc_layer<layer_idx>.txt`.
`<layer_idx>` corresponds to the indices set in model config file.
For example, if the config contains this line: `interctc_layer_idx: [6,12]`, then there will two files corresponding the output of the 6th and the 12th encoder layer: `encoder_interctc_layer6.txt` and `encoder_interctc_layer12.txt`.
The code in this PR was used in many of my Aphasia speech detection experiments and produced good results. I also added more tests to make sure ASR without InterCTC still works.
@sw005320 I mentioned there was a bug I encountered in …

Add InterCTC to E-Branchformer encoder, and the ability to save InterCTC inference output to files

---

tools/Makefile
tools/test_soundfile.py

This test program is designed to avoid a bug in which an invalid write or read operation is performed on FLAC audio files using soundfile under certain conditions when using a specific version of libsndfile. In this pull request, we will modify the installation process to perform this test because this issue is considered critical.
The bug occurs when audio data with the maximum and minimum values of PCM signed int16 type is written as flac using soundfile, and then read. We have confirmed that this issue occurs with libsndfile.so.1.0.25 at the very least. However, there is a possibility that the root cause lies with libFLAC or libogg which are linked to the libsndfile.

Add test of soundfile for Makefile

---

espnet/nets/beam_search.py
espnet2/bin/lm_inference.py
test/espnet2/bin/test_lm_inference.py

This PR adds `lm_inference`, which can be used for conditional text generation.
An example using the LM from `librispeech` is as follows.
Code:
```
import logging
import torch
from espnet2.bin.lm_inference import GenerateText
if __name__ == "__main__":
logging.basicConfig(
level=logging.DEBUG,
format="%(asctime)s (%(module)s:%(lineno)d) %(levelname)s: %(message)s",
)
generatetext = GenerateText(
lm_file="exp/asapp/e_branchformer_librispeech/lm/valid.loss.ave_10best.pth",
token_type="bpe",
bpemodel="path/to/bpemodel",
device="cuda" if torch.cuda.is_available() else "cpu",
maxlen=15,
minlen=1,
beam_size=5,
penalty=0,
)
res = generatetext(
"i have traveled to many ".upper()
)
print(res[0][0])
print(res[0][1])
```
Output:
```
I HAVE TRAVELED TO MANY PARTS OF THE WORLD
['▁I', '▁HAVE', …
```

Add lm_inference for conditional text generation

---

egs2/TEMPLATE/asr1/scripts/audio/format_score_scp.sh
egs2/opencpop/svs1/conf/tuning/train_xiaoice.yaml
espnet2/bin/asr_transducer_inference.py
espnet2/bin/svs_inference.py
espnet2/gan_svs/espnet_model.py
espnet2/gan_svs/joint/joint_score2wav.py
espnet2/gan_svs/vits/vits.py
espnet2/svs/espnet_model.py
espnet2/svs/naive_rnn/naive_rnn.py
espnet2/svs/naive_rnn/naive_rnn_dp.py
espnet2/svs/xiaoice/XiaoiceSing.py
espnet2/svs/xiaoice/loss.py
espnet2/train/preprocessor.py

Hi @ftshijt, here are updates on Muskits:
- Add slur in svs
- Add pitch_loss and vuv_loss for XiaoiceSing following XiaoiceSing2.

[SVS] Update XiaoiceSing

---

egs2/TEMPLATE/asr1/utils/filter_scps.pl
egs2/mini_librispeech/diar1/NOTE.md

In egs2/mini_librispeech/diar1 example, I found some problems:
- The Perl script in utils/data/get_utt2dur.sh is unable to process scp file of the dataset used in this example, e.g. data/train_clean_5/wav.scp. It results in the dependency of Kaldi despite it's a egs2 example.
- The Perl script used to filter scps is missing.
To address these problems, I make some changes as follows:
- Add a NOTE.md to warn user about the dependency of Kaldi. The warning wan't added to README.md considering that the file is generated by a script.
- Copy [filter_scps.pl](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/utils/filter_scps.pl) from Kaldi's repository.

Add missing filter_scps scripts and note about kaldi for diarization example of mini_librispeech

---

egs2/TEMPLATE/enh1/enh.sh
egs2/librimix/enh1/local/data.sh
espnet2/bin/asr_inference.py
espnet2/bin/enh_scoring.py
espnet2/enh/espnet_enh_s2t_model.py
espnet2/enh/espnet_model.py
espnet2/iterators/chunk_iter_factory.py

This is a followup PR of https://github.com/espnet/espnet/pull/5103.
* `egs2/TEMPLATE/enh1/enh.sh`: Fixed a bug when ark-formatted audios are used.
* `egs2/librimix/enh1/local/data.sh`: Added a stage for creating train-100 and train-360 subsets.
* `espnet2/bin/asr_inference.py`: Update the documentation of arguments related to joint Enh-ASR models and multi-speaker ASR models.
* `espnet2/bin/enh_scoring.py`: Fixed a bug when ark-formatted audios are used; Added sample info.
* `espnet2/enh/espnet_enh_s2t_model.py`: <del>Added an argument `enh_checkpointing` for applying checkpointing in the Enh model.</del>
* `espnet2/enh/espnet_model.py`: Fixed a bug when MultiLayerPITSolver is used.
* `espnet2/iterators/chunk_iter_factory.py`: Fixed a bug when excluded_key_prefixes is an empty list.

Bug fixing and improvement in SE functions

---

espnet2/bin/split_scps.py

Hi, this PR fixes two issues in the script `split_scps.py`. Please let me know if you spot any potential problems.
1. The original script opens and closes an output file everytime it writes a line. If the file has millions of lines, this process will take a huge amount of time. Now, I open all files before writing, which reduces the time from over 1 day to a few seconds in my case.
2. `prev_key` seems not updated and remains `None`, so I added line 55.

Fix issues in split scps

---

egs2/TEMPLATE/asr1/pyscripts/audio/format_wav_scp.py
espnet2/fileio/sound_scp.py

The processing for cache has a bug.

fix format_wav_scp.py

---

espnet2/train/trainer.py

This is related to https://github.com/espnet/espnet/issues/5134

Add more stats to the training log

---

setup.py

This PR is intended to fix the CI errors. Due to the [deprecation](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations) of numpy aliases, e.g. np.float, np.int, errors were raised in several packages (e.g. fairseq, librosa, etc).
Timeline:
1. Try to remove fairseq dependency, espeically in test.
2. Several other packages raise the same error. So the current solution is to constrain the numpy version (<1.24).

Limit the Numpy version (<1.24) to fix CI error temporarily.

---

README.md
egs2/wsj0_2mix/enh1/README.md
egs2/wsj0_2mix/enh1/conf/tuning/train_enh_skim_causal_small.yaml

Hi,
I upload a pre-trained causal model here: 
https://huggingface.co/lichenda/wsj0_2mix_skim_small_causal.
And also updated the colab streaming demo: 
https://colab.research.google.com/drive/17vd1V78eJpp3PHBnbFE5aVY5uMxQFL6o?usp=sharing
|dataset|STOI|SAR|SDR|SIR|SI_SNR|
|---|---|---|---|---|---|
|enhanced_cv_min_8k|93.41|15.54|14.92|24.87|14.51|
|enhanced_tt_min_8k|94.20|15.00|14.33|24.18|13.92|

Add pre-trained causal speech separation model and streaming demo

---

espnet2/asr/maskctc_model.py

This PR fixes a bug in Mask-CTC decoding using GPU (#5195).

Bug fix for #5195

---

egs2/chime7_task1/asr1/README.md
egs2/chime7_task1/asr1/local/da_wer_scoring.py
egs2/chime7_task1/asr1/local/data.sh
egs2/chime7_task1/asr1/run.sh
egs2/chime7_task1/diar_asr1/README.md
egs2/chime7_task1/diar_asr1/local/pyannote_diarize.py
egs2/chime7_task1/diar_asr1/run.sh

new PR from https://github.com/espnet/espnet/pull/5183 which had problems due to error of applying black. 
@simpleoier I made another PR and closed the other one.

 Closed CHiME-7 DASR adding evaluation inference + adding support to use diarization baseline "pre-computed" JSONs (new PR)

---

espnet2/gan_tts/hifigan/hifigan.py

Before https://github.com/espnet/espnet/commit/1b45bdc8c98b3b6bf149df241869aa63051acbd1, the norm for scale discriminator is not applied correctly. This causes mismatch of parameters with configuration. As a result, we cannot load the pretrained models.
~~To solve this issue, when parameter mismatch happens in loading, we remove the norm at first, load the parameters, and then apply the norm in post-hook functions.~~
It seems that applying weight norm and spectral norm for pretrained parameters causes unexpected behavior.
Therefore, I changed to just show the message about the training error when fine-tuning and the instruction to use pretrained parameters.
Just using pretrained model for the inference is fine.
Fix the following issues:
- #4595 
- #5237 
- #5239

fix norm compatibility in scale discriminator

---

egs2/TEMPLATE/asr1/utils/download_from_google_drive.sh
egs2/jvs/tts1/README.md
espnet2/gan_tts/hifigan/hifigan.py

- Fix the norm compatibility issue of the scale discriminator in fine-tuining
- Continue from #5240
When using `load_pretrained_model`, the state_dict of destination is updated with that of source.
https://github.com/espnet/espnet/blob/161e4bb5092b77361fcb22e28691d028ef7a7194/espnet2/torch_utils/load_pretrained_model.py#L114
Therefore, when there is key mismatch, the final state dict includes keys included in both destination and source dict.
As a result, the state_dict at [this point](https://github.com/kan-bayashi/espnet/blob/731cbfea3bc54f8e6625e01df5d9eebb144de1f0/espnet2/gan_tts/hifigan/hifigan.py#L626) includes `weight` from source dict and `weight_g` / `weight_v` from destination dict:
```python
(Pdb) state_dict.keys()
dict_keys(['discriminator.msd.discriminators.0.layers.0.0.bias', …
```

re-fix norm compatibility in scale discriminator 

---

egs2/librispeech/asr2/README.md
egs2/librispeech/asr2/conf/decode_ctc0.3.yaml
egs2/librispeech/asr2/conf/tuning/train_discrete_asr_e_branchformer1_1gpu.yaml
egs2/librispeech/asr2/conf/tuning/train_discrete_asr_e_branchformer1_conv1d3.yaml
espnet/nets/pytorch_backend/transformer/subsampling.py
espnet2/asr/encoder/e_branchformer_encoder.py
test/espnet2/asr/test_discrete_asr_espnet_model.py

* The speed is as following:
```
conv_subsample2: WER (2.1 / 4.6 / 2.4 / 4.6) 32 min / epoch, around 18.5 hours for 35 epochs
conv_subsample3: WER (2.4 / 4.8 / 2.5 / 4.8) 24 min / epoch, around 13.8 hours for 35 epochs
```
But the performance of conv_subsample3 is a bit worse due to deletion errors at the end. I increase the max_len_ratio to 1.2, however, it turns out that CTC scorer cannot handle the length.
* The speed is as following:
```
conv_subsample2: WER (2.2 / 4.5 / 2.4 / 4.6) 21 min / epoch, around 12.6 hours for 35 epochs
```

add conv1d subsampling 3 and egs2/librispeech/asr2 wavlm_large_21 kmeans (1000/2000) results

---

egs2/TEMPLATE/asr1/pyscripts/utils/convert_to_avg_xvectors.py
egs2/TEMPLATE/tts1/README.md

Using speaker averaged xvectors in TTS training may generalise better to inference tasks, where the utterance-specific xvector is unknown.
I added a small script to modify xvector.scp to refer to spk_xvector.ark entries instead of utterance-specific ones. It works well for my task so I figured it may be of use for others.

Add script to use speaker averaged xvectors in TTS training

---

espnet2/bin/asr_inference_streaming.py

For certain win_length/hop_length and sim_chunk_length settings (e.g., win_length:256, hop_length: 90 and sim_chunk_length: 512) poor WER was observed that was caused by incorrect filling of waveform_buffer object. 
See https://github.com/espnet/espnet/issues/4807

Fix filling of waveform_buffer with samples for streaming inference

---

doc/espnet2_tutorial.md
espnet2/asr_transducer/beam_search_transducer.py
espnet2/asr_transducer/decoder/mega_decoder.py
espnet2/asr_transducer/decoder/rnn_decoder.py
espnet2/asr_transducer/decoder/rwkv_decoder.py
espnet2/asr_transducer/decoder/stateless_decoder.py
espnet2/asr_transducer/error_calculator.py
espnet2/asr_transducer/espnet_transducer_model.py
espnet2/asr_transducer/joint_network.py
espnet2/tasks/asr_transducer.py
test/espnet2/asr_transducer/test_espnet_transducer_model.py

This PR add capabilities to train with k2 pruned transducer loss. It's working but a WIP.
It's was not a priority but I'm currently doing a major work/rework on the training pipeline (initialization, schedulers, criterions, normalization, loss and auxiliary losses, etc), I think it should be considered.
Also:
- Use `maes` instead of `default` in `ErrorCalculator` to avoid endless/long loop in some cases (e.g.: unrestricted decoding with constrained model training).
- Use `torch.tensor` instead of `torch.LongTensor` in all decoders' `batch_score`. The legacy constructor will raise device mismatch error with torch >1.10.
To add:

Add support for K2 pruned transducer loss

---

setup.py
tools/installers/install_pyopenjtalk.sh

- Fix Cython version
- Cython 3.0 may not work for several libraries
- pyworld
- pysptk
- pyopenjtalk
- https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder/issues/87
- https://github.com/r9y9/pysptk/releases/tag/v0.2.1
- https://github.com/r9y9/pyopenjtalk/releases/tag/v0.3.1

Fix Cython version to pass the installation of libraries with Cython

---

doc/espnet2_tutorial.md
egs2/TEMPLATE/asr1/pyscripts/utils/evaluate_whisper_inference.py
egs2/TEMPLATE/asr1/scripts/utils/evaluate_asr.sh

This PR adds `decode_options` and `hyp_cleaner` in `evaluate_whisper_inference`. The `decode_options` can be used to control the decoding hyperparameters in Whisper model's `transcribe` method.
Here is an example script to evaluate a test set using Whisper:
```bash
#!/usr/bin/env bash
set -e
set -u
set -o pipefail
whisper_tag=medium
cleaner=whisper_en
hyp_cleaner=whisper_en
nj=1
test_sets="test/WSJ/test_eval92"
decode_options="{language: en, task: transcribe, temperature: 0, beam_size: 10, fp16: False}"
for x in ${test_sets}; do
wavscp=dump/raw/${x}/wav.scp
outdir=whisper-${whisper_tag}_outputs/${x}
gt_text=dump/raw/${x}/text
scripts/utils/evaluate_asr.sh \
--whisper_tag ${whisper_tag} \
--nj ${nj} \
--gpu_inference true \
--stage 2 \
--stop_stage 3 \
--cleaner ${cleaner} \
--hyp_cleaner …
```

Add decode_options and hyp_cleaner in evaluate_whisper_inference

---

egs2/librimix/asr1/local/data.sh
egs2/librimix/sot_asr1/local/data.sh

In `egs2/librimix/asr1/local/data.sh`,  L116, if `mix_f` matches multiple files, the `grep` command (in some version) will output the specific matched file name (which is not the expected output) and lead to a wrong `utt_id` in data preparation.
So I updated the data preparation scripts to avoid this issue.

fix a data preparation issue for librimix recipe.

---

.github/workflows/doc.yml

Fix CI variable
CI were skipping doc verification due to mislabel.
#5320

Fix documentation skip CI

---

doc/espnet1_tutorial.md
doc/index.rst
doc/tutorial.md

Update the usage page
The [usage part](https://espnet.github.io/espnet/tutorial.html) is outdated. Also, it mixes the espent1 and espnet2 explanations.

Update the usage

---

.github/workflows/ci.yaml
tools/installers/install_ffmpeg.sh

- Install ffmpeg with apt for ubuntu in ci
- if ffmpeg is available, skip ffmpeg installation
- Sometimes ffmpeg installation is failed due to overaccess.
https://github.com/espnet/espnet/actions/runs/5633059176/job/15261578319

Reduce ffmpeg installation time in ci

---

egs2/TEMPLATE/asr2/asr2.sh

- Set the `lang` variable
- Enable LFS tracking for `*.mdl` files
- I think setting the language variable is needed (HF hub complains when language is set to `noinfo`).
- I'm not sure if setting the LFS tracking for `*.mdl` files is needed. Does it work without it for everyone else? I have not investigated what is the expected behaviour here, but in my environment HF hub complained that `*.mdl` is not under LFS.

Couple of tweaks for asr2.sh for the HF hub upload

---

egs2/TEMPLATE/asr1/scripts/utils/TEMPLATE_HF_Readme.md

Fix bash typo.
It pops up when I try to upload a model to the HF hub with `./run.sh --skip_upload_hf false --stage 18 --hf_repo espnet/xyz`.

Update TEMPLATE_HF_Readme.md (fix bash typo)

---

egs2/TEMPLATE/slu1/slu.sh

Made minor fix in slu.sh
There was bug in ngram training code in slu.sh that used only first token instead of all tokens in transcripts.
Refer https://github.com/espnet/espnet/issues/5312

Fix bug in ngram training in slu.sh

---

egs2/ljspeech/tts1/local/data.sh
espnet2/gan_tts/hifigan/loss.py

Correct wrong comments
According to the forward method of `LogMel` class, `spec` argument seems to inform wrong tensor shape.

minor fix: correct wrong comments

---

tools/installers/install_datasets.sh

Added quotation marks around `datasets>=2.0.0` in `tools/installers/install_datasets.sh`
So that bash does not consider the redirection in line `python3 -m pip install datasets>=2.0.0`

Add quotation marks to install_datasets.sh

---

egs2/dns_ins20/enh1/local/dns_create_mixture.sh
egs2/reverb/enh1/local/path.sh
egs2/wham/enh1/run.sh
egs2/whamr/enh1/run.sh
espnet2/bin/enh_tse_inference.py

This PR updates the bash scripts in several SE recipes to make them easier to use and fixes some potential bugs that might be difficult to detect.

Update of several SE recipes and some minor fixes

---

espnet/transform/spec_augment.py

This fixes occasional, unpredictable "ValueError: assignment destination is read-only" crashes for me. See #5415 .

In spec_augment.py, check whether an array is writeable before modifying it inplace

---

docker/build.sh
docker/prebuilt/devel.dockerfile

Update devel dockerfiles for fix local builds
Fix #5405

Docker updates for local builds

---

egs2/TEMPLATE/svs1/README.md

fix typo in TEMPLATE/svs1/README.md

fix typo in TEMPLATE/svs1/README.md

---

egs/commonvoice/asr1/local/data_prep.pl
egs/covost2/st1/local/data_prep_commonvoice.pl
egs2/fleurs/asr1/local/data_prep.pl
egs2/open_li52/asr1/local/data_prep.pl

Currently, only `[a-z]` ASCII characters are changed to uppercase in these scripts, not including other UTF-8 characters.
Here is an example:
```
ADEMáS, UTILIZó MOTIVOS MUSICALES REITERADAMENTE.
LA CANCIóN ALCANZó LA POSICIóN NúMERO UNO DEL "BILLBOARD".
ESTAS COMPAñíAS TENíAN COMO NOMBRE COMPAñíA A, B, C, Y D RESPECTIVAMENTE.
ÉL LO HACE PUES NUNCA HA DEJADO DE AMAR A YANG.
EN SU JUVENTUD RECIBIó FORMACIóN EN LOS CLAUSTROS DE LOS CARMELITAS EN ANGERS.
INGRESó A LA UNIVERSIDAD DE LOVAINA PARA HACER SUS ESTUDIOS EN DERECHO.
```
We want all the characters to be converted to uppercase.
This improves the preprocessing step on `data_prep.pl` scripts to take diacritics into account:
- [Enables UTF-8 encoding for standard streams](https://perldoc.perl.org/open).
- Switches to using …

Improve diacritic compatibility in data_prep.pl preprocessing scripts

---

test/espnet2/bin/test_asr_inference.py
test/espnet2/bin/test_slu_inference.py

Changed length of speech input to make the test time of test_slu_inference.py and test_asr_inference.py shorter
test_slu_inference.py takes too long and can sometimes fail.

Simple fix to reduce test_slu_inference time

---

espnet2/bin/whisper_export_vocabulary.py
espnet2/train/preprocessor.py

Fix bugs in the Whisper SOT implementation.
1. In `whisper_export_vocabulary.py`, the type of `--sot_asr` should be `str2bool`;
2. In `class CommonPreprocessor_multi`, add `whisper_language` and `whisper_task` to support more datasets.

Fix bugs of Whisper SOT.

---

egs2/commonvoice/asr1/README.md
egs2/commonvoice/asr1/conf/tuning/decode_transducer.yaml
egs2/commonvoice/asr1/conf/tuning/train_asr_transducer_conformer5.yaml

This PR introduces a new transducer conformer configuration for the CommonVoice recipe:
- Utilizes the Conformer architecture for the encoder (based on the `train_asr_conformer5.yaml` provided).
- Incorporates the LSTM-based transducer decoder.
We tested the model in an NVIDIA A100 GPU, but smaller GPUs can probably be used.
We have tested the model with the Basque language (`eu`) only.
Common Voice 14 test set:
| Model | Common Voice 14 CER | Common Voice 14 WER |
| --------- | ------ | ------ |
| `train_asr_conformer5.yaml` | 1.6 | 8.0 |
| `train_asr_transducer_conformer5.yaml` | 1.7 | 8.0 |
AhoMyTTS (a private difficult dataset):
| Model | AhoMyTTS CER | AhoMyTTS WER |
| --------- | ------ | ------ |
| `train_asr_conformer5.yaml` | 6.0 | 22.21 |
| `train_asr_transducer_conformer5.yaml` …

Add transducer conformer configuration to commonvoice recipe

---

egs2/TEMPLATE/s2st1/s2st.sh

Fix unbound variable error when uploading s2st models to HF.
`lang` variable needs to be set before generating README.md for the HF repository.

Fix s2st HF model uploading

---

test/espnet2/asr/frontend/test_s3prl.py

I removed the restriction of pytorch>=2.0 to test the s3prl frontend.
S3prl now supports pytorch>=2.0
https://github.com/s3prl/s3prl/pull/512

Remove the pytorch version restriction for s3prl

---

egs/must_c/st1/local/download_and_untar.sh

The mustc download links were changed. I'm updating the scripts accordingly.

replace old mustc links with new instructions

---

egs2/mixed_v2/s2t1/README.md

This PR adds the model link to E-Branchformer in OWSM v2.
Despite being trained for fewer updates, E-Branchformer shows clear improvement over Transformer at such a large scale.
We will train and release E-Branchformer based models at even larger scales.

Add E-Branchformer model checkpoint in OWSM v2

---

test/espnet2/asr/frontend/test_frontend.py
test/espnet2/enh/layers/test_complex_utils.py

This PR improves two unit tests to avoid occasional errors caused by numerical precision or randomness.
* [test/espnet2/asr/frontend/test_frontend.py](https://github.com/espnet/espnet/blob/master/test/espnet2/asr/frontend/test_frontend.py): use a predefined 2-ch signal instead of a randomly sampled signal for beamforming to avoid singular covariance matrix.
* [test/espnet2/enh/layers/test_complex_utils.py](https://github.com/espnet/espnet/blob/master/test/espnet2/enh/layers/test_complex_utils.py): fix the random seed to avoid occasional error when the numerical difference is slightly larger than 1e-06.
Sometimes we may observe errors as in https://github.com/espnet/espnet/actions/runs/6719461822/job/18261148245 which are essentially numerical issues. After the modifications in this PR, …

Improve error robustness of unit tests

---

espnet2/bin/uasr_inference_k2.py
espnet2/fileio/score_scp.py
espnet2/fst/lm_rescore.py
espnet2/uasr/espnet_model.py

Use a correct one-line except. 
```
from espnet2.tasks.tts import TTSTask
```
causes a segmentation fault in my environment (Python 3.9.0)
- https://docs.python.org/3/tutorial/errors.html#handling-exceptions
- https://stackoverflow.com/questions/6470428/catch-multiple-exceptions-in-one-line-except-block

Fix except

---

README.md

Update discord invitation link with new one that never expires.
Added link has expired.

Update Discord Invitation Link

---

espnet2/tts/espnet_model.py

- Fix #5588
- In text2wav model, `speech` is not used for the inference even if using `teacher_forcing` since the vocoder is non-causal.
- #5588

fix inference with teacher forcing using speech in text2wav model

---

egs2/owsm_v3/s2t1/local/kaldi_to_whisper.py

- Fix typo bug in [egs2/owsm_v3/s2t1/local/kaldi_to_whisper.py](https://github.com/espnet/espnet/blob/7c140c2ac9b4f642acb36131217dd984d4601681/egs2/owsm_v3/s2t1/local/kaldi_to_whisper.py#L4)
- Fixed typo: `f"<args.tgt>"` -> `f"<{args.tgt}>"`
- Checked all the use cases of `kaldi_to_whisper.py`, but no script uses `--tgt` parameter, so no problem in OWSM v3 training. Nevertheless, fixed the bug to remove potential future bugs.
- FYI, @jctian98 @pyf98

Fix minor OWSM data prep bug

---

espnet/nets/ctc_prefix_score.py

In my case, I have the EOS/SOS token at index 0 in my vocab. The CTC code here also has blank index hardcoded at index 0. In principle, it should not be a problem to reuse the EOS token as blank index for CTC, however, the code was behaving incorrect for this case and overwrote the EOS scores.

CTC prefix score, fix if blank == eos

---

egs/must_c/st1/local/download_and_untar.sh
egs2/must_c_v2/st1/local/data.sh

- remove check on existance of destination data directory.
- remove `-d` option in `tar` uncompression
for the first item, the directory should already exist because we put raw data archive in it. The original implementation skips when the directory already exists, which will result in slient failure.
- tested on slurm with the en-de

bug fixes for must_c v2 recipe

---

egs2/TEMPLATE/asr1/utils/data/internal/modify_speaker_info.py
egs2/TEMPLATE/asr1/utils/data/modify_speaker_info.sh

Two scripts where added (`egs2/TEMPLATE/asr1/utils/data/modify_speaker_info.sh` and `egs2/TEMPLATE/asr1/utils/data/internal/modify_speaker_info.py`) by copying them from Kaldi's github:
https://github.com/kaldi-asr/kaldi/tree/21ae411fd46282726d893e53c05fef5baea64fef/egs/wsj/s5/utils/data
The recipe failed when using espnet `run.sh` because `egs2/TEMPLATE/asr1/utils/data/modify_speaker_info.sh` was missing. This script is a Kaldi script and, by doing a quick search in the espnet repository appears to be used in the espnet recipes for tedlium3, ami, chime6 and tedlium2.
The other script, `egs2/TEMPLATE/asr1/utils/data/internal/modify_speaker_info.py`, was added since it was required by the first one.

Fixed bug by copying missing Kaldi scripts

---

egs2/TEMPLATE/asvspoof1/path.sh

Remove Kaldi dependency from ESPnet new task tutorial

Fix path dependency in ESPnet tutorial

---

espnet2/tasks/abs_task.py

This is a small fix for loading pre-trained models from the transformers library. 
The transformers library has added new variables to its pre-trained models like: https://github.com/huggingface/transformers/blob/07e3454f034b4889925621e8e3253547d2a04aa7/src/transformers/models/bert/modeling_bert.py#L195.  Therefore, when loading parameters from older pre-trained SLU models that include LMs, the argument strict=False is necessary to accommodate these changes.
This is related to the ESPnet-SLU tutorial.

Fix loading pre-trained model from transformers

---

egs2/TEMPLATE/slu1/slu.sh

I updated the "utt_extra_files" to be set as none (i.e., "") when not utilizing the transcript.
This caused some issues when performing speed perturbation without utilizing the transcript.
https://github.com/espnet/espnet/issues/5656

Fix speed perturbation when not using transcript in slu.sh

---

espnet/nets/pytorch_backend/transformer/decoder.py
espnet/nets/pytorch_backend/transformer/decoder_layer.py
espnet/nets/pytorch_backend/transformer/encoder.py
espnet/nets/pytorch_backend/transformer/encoder_mix.py
espnet2/asr/decoder/transformer_decoder.py
espnet2/asr/decoder/whisper_decoder.py
espnet2/s2st/synthesizer/discrete_synthesizer.py

I added the `memory_mask` arg to `BaseTransformerDecoder.forward_one_step`.
Alongside, I made the `cache` arg a keyword-only arg, such that the user can not rely on the specific order of positional args. I think that's cleaner.
I needed the `memory_mask` arg for `TransformerDecoder.forward_one_step` because I wanted to perform batched beam search (i.e. on multiple sequences at once, i.e. the batch dim in `memory` is >1).

TransformerDecoder forward_one_step with memory_mask

---

egs2/interspeech2024_dsu_challenge/asr2/README.md
egs2/ml_superb/asr1/README.md
egs2/ml_superb/asr1/local/data_prep.py

Another issue resulting from https://github.com/espnet/espnet/pull/5676#issuecomment-1963497902 , some extremely lengthy utterances are included in the benchmark though they are not considered in the `asr1` setup.
To keep `asr1` and `asr2` aligned, we need to remove the over-lengthy audio in ml_superb data from the local/data.sh to prevent it from happening.

Fix over-lengthy audio in ml_superb data prep

---

egs2/TEMPLATE/asr1/pyscripts/utils/calculate_bitrate.py
egs2/TEMPLATE/asr1/pyscripts/utils/convert_token2json.py

Two scripts for bitrate calculation.
The `calculate_bitrate.py` is for processing the submission package (i.e., all submission from participants shall be able to use this one to compute)
The `convert_token2json.py` is for converting espnet baseline results into a submission package.
Please consider merging it in advance so @simpleoier can push the ASR side scoring and I update the TTS and SVS scoring.

Update bitrate calculation scripts for the IS24 discrete speech challenge

---

egs2/TEMPLATE/asr1/pyscripts/utils/score_summarization.py

I obtained a reasonable score with `result['rouge2']*100` instead of `result['rouge2']**100`.

Fix typo in summarization scoring

---

egs2/TEMPLATE/tts1/tts.sh

After an extra stage was added to tts.sh in #5579 , following stage numbers were updated.
A few were missed in the update and this PR covers those that remained.

Fix stage references in generated run.sh in TTS recipes

---

espnet2/bin/s2t_inference.py

The last time-stamp prediction in the last chunk is slightly smaller than the whole speech length, making to an extra chunk that usually has < 1000 samples. The decoding behavior of this very short chunk leads to unpredictable behavior.
Remove one redundant line.

fix a small issue in OWSM decode_long

---

egs2/TEMPLATE/tts1/tts.sh

A bugfix to TTS model packing when new spk embedding is used.
Corresponding fixes to the https://github.com/espnet/espnet/issues/5713

Fix tts packing with new spk embedding

---

espnet2/layers/create_adapter_fn.py

This PR fixes discrepancy of parameters for the backbone model when applying LoRA and save all parameters.
Setting the model to eval mode at the fixing position can avoid the issue. Becase the weights would not be merged again when loading pre-trained checkpoints (in the eval mode) for inference. In addition, the weights would subtract the LoRA parameters in resuming training case, when calling `train()`. 
It should not affect the normal training, because `train()` (subtraction) is applied after `eval()` (addition). 
For example, in the LoRA Linear layers of [loralib](https://github.com/microsoft/LoRA/blob/main/loralib/layers.py#L62C1-L75C35), weights of the backbone model will be merged with LoRA parameters when switching between train and eval modes.
```
def train(self, mode: bool = …
```

Fix LoRA issues when saving all parameters.

---

egs2/chime8_task1/asr1/run.sh

There was an error for which txt normalization was not applied on validation set during ASR training on C8 recipe. 
This fixes that.

Apply normalization on validation set for CHiME-8 recipe

---

espnet2/tasks/abs_task.py

The change was initially conducted in a previous PR at https://github.com/espnet/espnet/pull/5741 but it breaks the compatibility of the loading policy. To keep it unchanged, we revert back to the original config.

Revert change to abs_task to keep the consistency behavior

---

.github/workflows/ci_on_macos.yml
ci/install_macos.sh
tools/Makefile
tools/installers/install_sctk.sh

Update ci_on_macos.yml (fix CI with latest mac at arm architecture)

---

egs2/TEMPLATE/asr1/pyscripts/feats/dump_codec.py

As in https://github.com/espnet/espnet/pull/5805, the updated codec tokenizer always allows back-prop. This is not necessary for the offline tokenization script.

followup codec tokenizer interface

---

espnet2/train/preprocessor.py

Add if block to avoid zero division when using speech_volume_normalize in preprocessor
When speech is all zero signal, zero division happens.

Avoid zero division for speech_volume_normalize

---

egs2/TEMPLATE/asr2/asr2.sh
egs2/librispeech_100/asr2/path.sh
egs2/librispeech_100/asr2/run.sh

- Typo-style bug fixes in asr2.sh template recipe
- The current version does not work for librispeech-100 recipe.
- After this fix, we reproduced similar librispeech-100 results. (Left: ours, Right: original README) Actually, the WER/CER is slightly better, so we might want to update the numbers + commit hashes.

Fix bug in asr2.sh

---

tools/Makefile

Add file download (averaged_perceptron_tagger_eng) required by package (espnet_tts_frontend > g2p_en) that is not downloaded automatically
Fix CI
https://www.nltk.org/_modules/nltk/tag/perceptron.html
https://github.com/nltk/nltk/issues/3177

[CI] Add required file for g2p_en

---

egs2/aishell3/tts2/local/data.sh
egs2/aishell3/tts2/local/download_and_untar.sh
egs2/aishell3/tts2/local/path.sh

Fix absolute paths under ``aishell3/tts2/local/``.
Recipe bug fixing.
Previous (PR)[https://github.com/espnet/espnet/pull/5849] .

Fix absolute paths in aishell3_tts2

---

.github/workflows/publish_paper_pdf.yml

Paper publish build is failing
Github actions' `actions/upload-artifact` was deprecated.
I bumped up from v1 to v4, because it doesn't seem to have difference in the interface.

Bugfix for the paper publish workflow

---

espnetez/trainer.py

* In this (small) PR, we remove ellipses from the ESPnet-EZ Trainer documentation and replace them with spaces
* While copying examples from ESPnet-EZ, ellipses are accidentally included:
```
trainer = Trainer(
...     task='asr',
...     train_config={'batch_size': 32, 'learning_rate': 0.001},
...     output_dir='./output',
...     stats_dir='./stats',
...     train_dump_dir='./train_dump',
...     valid_dump_dir='./valid_dump'
)
```

fix: replace ellipses (...) in ESPnet-EZ Trainer documentation

---

doc/espnet2_task.md

* minor spelling fix in documentation: collcate_fn -> collate_fn
* While looking for documentation on ESPnet's dataloading, I noticed that "collate_fn" was misspelled as "collate_fn", confusing me for a second.

fix: collcate_fn -> collate_fn

---

espnet/nets/pytorch_backend/transformer/attention.py
espnet2/train/trainer.py

Fixes #5921.
I also observed that a failed flash attention import will silence any `logging` with a level of `INFO` or below. 
Changing it to a print statement to avoid the issue for now, as I still cannot find the root cause.

Training code patches

---

egs2/libriheavy_small/asr1/README.md
egs2/libriheavy_small/asr1/asr.sh
egs2/libriheavy_small/asr1/cmd.sh
egs2/libriheavy_small/asr1/conf/decode_asr.yaml
egs2/libriheavy_small/asr1/conf/fbank.conf
egs2/libriheavy_small/asr1/conf/pbs.conf
egs2/libriheavy_small/asr1/conf/pitch.conf
egs2/libriheavy_small/asr1/conf/queue.conf
egs2/libriheavy_small/asr1/conf/slurm.conf
egs2/libriheavy_small/asr1/conf/train_asr.yaml
egs2/libriheavy_small/asr1/conf/tuning/train_asr_e_branchformer.yaml
egs2/libriheavy_small/asr1/db.sh
egs2/libriheavy_small/asr1/local/data.sh
egs2/libriheavy_small/asr1/path.sh
egs2/libriheavy_small/asr1/pyscripts
egs2/libriheavy_small/asr1/run.sh
egs2/libriheavy_small/asr1/scripts
egs2/libriheavy_small/asr1/steps
egs2/libriheavy_small/asr1/utils

Asr1 recipe using the TEMPLATE.
Run.sh file.
Data.sh file under local.
Train_asr.yaml and decode_asr.yaml under conf dir. 
README.md
In the data.sh under local dir I just replaced a word in line 63: "cases_and_punc" by "upper_no_punc" for the file that is under libriheavy_medium/asr2/local. The rest is the same, and so this file can be used for the other asr1 recipes (medium and large)
I also changed in line 65 for data.sh replacing "{print $1" spk";}" for "{print $1, $1;}" to be more kaldi friendly.

Add asr1 recipe for libriheavy_small

---

doc/espnet1_tutorial.md
doc/espnet2_tutorial.md

When clicking the link (table of contents) in https://espnet.github.io/espnet/espnet2_tutorial.html it breaks the page.
- This was due to existing markdown documents not using the code blocks for long text.
- I checked all the other tutorial docs, fixed two docs.
Bug reported by @pyf98 , thanks!

Fix bug in document that overflows the page

---

egs2/ml_superb/asr1/run_mono.sh

removed ```continue``` statement from the ```for``` loop in ```run_mono.sh```
Since both 10min and 1h loops are skipped, no training or ASR processing is done, and the script would prematurely reach the final echo and python commands without running any of the actual ASR tasks.

removed ''continue'' statement from the for loop in run_mono.sh

---

egs2/TEMPLATE/codec1/codec.sh

We have synced the scorer interface for versa, so we do not need a ESPnet-specified interface anymore.

Fix versa interface

---

egs2/TEMPLATE/diar1/diar.sh

Fix the order of arguments so that keyword arguments (`--collar` `--fs` `--frame_shift`) can be properly passed into `score_der.sh`.
I found that the above three arguments could not be passed into `score_der.sh` so it sometimes used the incorrect sampling rate to calculate the DER even when we set the correct one in run.sh.

[Bugfix] fix keyword argument error in stage 7 of diar.sh

---

espnet2/enh/loss/wrappers/pit_solver.py

When training a speech separation model with multiple losses, only the losses with independent_perm=True have gradients, while the gradients of all other losses with independent_perm=False are truncated. 
The root cause is the use of torch.tensor() to create a new tensor in pit_solver.py (when independent_perm=False). Here, torch.tensor() function detached from the computational graph when creating a new tensor, not preserving the gradient. 
A directly available solution is replacing torch.tensor() with torch.stack()​.
When checking the combined loss (L= alpha1 * loss1 + alpha2 *loss2 ), L has a gradient, where loss1 has a gradient and loss2 has no gradient. We compute the gradient norm during backpropagation to verify the contribution of each loss component in the combined loss, and we …

fix: gradient truncation bug in pit_solver.py

---

espnet/nets/pytorch_backend/transformer/attention.py

This PR adds the SDPA implementation from PyTorch. It supports several implementations of the attention mechanism (including flash attention), some of which are more efficient than the default implementation.
See https://pytorch.org/docs/2.5/generated/torch.nn.functional.scaled_dot_product_attention.html for more information.
Note: SDPA does not seem to support flash attention with variable-length inputs. So, we still need to use the previous flash attention implementation.

Add Scaled Dot Product Attention (SDPA) from PyTorch

---

doc/installation.md
egs2/owsm_ctc_v3.1/s2t1/README.md
espnet2/bin/s2t_ctc_align.py

This PR fixes a few issues in OWSM-CTC forced aligner. The new script should be more reliable and memory-efficient than the previous one. The script has been used in the segmentation of large-scale YODAS2.
The PR also fixes a typo in the installation documentation.

Fix issues in OWSM CTC segmentation

---

espnet2/train/preprocessor.py

During OWSM-CTC training, the language token is randomly masked so that the model will learn to predict it. However, this should not happen for validation.

Fix minor bug in OWSM-CTC preprocessor

---

egs2/ml_superb2/asr1/README.md
egs2/ml_superb2/asr1/local/score.py

Fixes a typo in score.py and RESULTS.md where the CER and LID are swapped.

Typo in ML-SUPERB Results

---

egs2/TEMPLATE/asr1/pyscripts/utils/average_checkpoints.py
egs2/owsm_ctc_v3.1/s2t1/README.md
espnet/nets/pytorch_backend/transformer/attention.py
espnet2/bin/s2t_inference_ctc.py
test/espnet2/bin/test_s2t_inference_ctc.py

- Implemented a unified batch decode interface for OWSM-CTC greedy search. The `decode_batch` method can decode a batch of audios which can be either short-form or long-form. Each audio can be provided as a path, a numpy 1-D array or a torch 1-D tensor. This makes the usage more flexible.
- Enabled flash attention for inference. With mixed precision and flash attention, we can decode ~200 samples at the same time on a GPU with 96GB memory.
- Added a stand-alone utility script to average model checkpoints.

Implement unified batch decode interface for OWSM-CTC

---

egs2/owsm_v3.1/s2t1/conf/train_s2t_ebf_conv2d_size1024_e18_d18_piecewise_lr2e-4_warmup60k_flashattn.yaml

* In https://github.com/espnet/espnet/issues/5973, a user reported that ESPnetS2TModel (for OWSM v3.1) could not be instantiated
* I ran into this issue too
* The solution is to remove the flash attention arguments regarding qk_norm from the model
* I added a small note that the current configuration is for the medium model in case anyone is confused
* flash attention arguments are not fields of the underlying ESPnetS2TModel
* these arguments were removed in HuggingFace (https://huggingface.co/espnet/owsm_v3.1_ebf_small/commit/e2f4e38bfb4b8319858ba910eb3af3eff272d3b9#d2h-406866) but not ESPnet

fix: OWSM v3.1 - remove flash attention args

---

tools/Makefile

Add `touch numpy.done` after numpy installation finishes normally.
After numpy installation, Makefile did not indicate that installation was finished.
Hence, rerunning Makefile kept numpy to be reinstalled even after installation.

Fix minor bug in Makefile

---

espnet2/train/trainer.py

Starting from torch2.6, the default value of torch.load has been flipped to True. However, our checkpoint setup is not in that option. It would be good to explicitly set the weights_only=False in the checkpoint loading.
Error msg when using torch2.6 with resuming.
```
FutureWarning: You are using torch.load with weights_only=False (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details).
In a future release, the default value for weights_only will be flipped to True. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be …
```

Add explicit weights_only=False for checkpoint loading

---

espnet2/enh/decoder/stft_decoder.py
espnet2/enh/layers/bsrnn.py
espnet2/enh/layers/tcn.py
espnet2/enh/layers/uses.py
espnet2/enh/separator/tfgridnetv3_separator.py

The old amp setup has been deprecated in later version of pytorch, throwing warning msg all the time.
Warning msg would be something like:
```
/usr/local/lib/python3.11/dist-packages/espnet2/enh/loss/criterions/time_domain.py:446: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
@torch.cuda.amp.autocast(enabled=False)
/usr/local/lib/python3.11/dist-packages/espnet2/enh/layers/tcn.py:458: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
@torch.cuda.amp.autocast(enabled=False)
/usr/local/lib/python3.11/dist-packages/espnet2/enh/layers/tcn.py:499: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use …
```

Fix the deprecated amp interface

---

espnet2/bin/st_inference.py

With the latest typeguard, it will spot the type issue in multi-decoder decoding (when both ASR and ST search are returned together).
Adding a simple fix to allow a tuple type for the multi-decoder return cases.
(Noted that this fix is necessary to make sure the demonstration notebook is working smoothly)

A quick fix for type error when dealing with multi-decoder (ST)

---

setup.py
tools/Makefile
tools/installers/install_transformers.sh

Limit max version of Transformers
The current version of transformer `4.50.0`, seems to be developed for newest pytorch versions (`>=2.3.0`)

Downgrade Transformers version

---

.gitignore
tools/installers/install_transformers.sh

Use lower pytorch version for checking transformer installation. `<2.1.0`
- The new release of transformers https://github.com/huggingface/transformers/releases, solves importing issues for versions `<2.3`
- Pytorch `<2.1.0` does not includes the compiler folder. So, versions `1.13` & `2.0` do not support the new transformer version.
@Vaibhavs10, @sw005320

Transformers version check

---

espnet2/gan_svs/vits/vits.py

- Fixed a bug in espnet2/gan_svs/vits/vits.py where score_dur_loss mistakenly used phoneme-level durations as targets, same as phoneme_dur_loss. Changed the target of score_dur_loss from gt_dur to score_dur.
- Currently, both channels in pred_dur are trained to predict phoneme durations, which are duplicated. This fix corrects the second channel to predict score-level durations and aligns with the original VISinger2 paper.
None

VISinger2 Duration Loss Quick Fix

---

.github/workflows/ci_on_ubuntu.yml

Limit Cython version on CI `test_import`
Fix CI
In the last days, Cython has released a new version that is generating the CI test_import to break (ver=3.1.0) due to the changes. (I cannot track exactly if due to the drop of numpy includes or any other). Versions lower than <3.1.0 do not have this issue.
Also, this seems to occur only on test_import. Other CI seems to not be using the Cython new version, so by the moment it will be installed at CI level. If it occurs on different CI, then it will be set at installation level.
Refs:
https://pypi.org/project/Cython/
https://github.com/cython/cython/pull/5842
https://github.com/cython/cython/issues/3573

FIX CI test_import

---

.github/workflows/ci_on_ubuntu.yml
ci/install.sh
ci/test_configuration_espnet2.sh
setup.py
test/espnet2/asr/decoder/test_hugging_face_transformers_decoder.py
test/espnet2/asr/postencoder/test_hugging_face_transformers_postencoder.py
test/espnet2/bin/test_asr_inference.py
test/espnet2/layers/test_create_adapter_fn.py

Changing order on CI installation.
Versa is using the latest whisper version. Whisper new version is not supported by ESPnet and does not have some hyperparameters (such as N_MEL). Changing the installation is an easy hack to fix CI checks.
Whisper.
ESPnet-3 commits

Changing order on CI for Whisper installation

---

egs2/TEMPLATE/asr1/steps/libs/nnet3/train/common.py
espnet/nets/chainer_backend/e2e_asr_transformer.py
espnet/nets/pytorch_backend/nets_utils.py

This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
The `logger.warn()` method is deperacted.

Resolve logger warnings

---

ci/doc.sh
doc/index.md
doc/vuepress/create_menu.py

- There was no link to espnet installation tutorial page, and this commit fixes it.
- Discussions at https://github.com/espnet/espnet/pull/6135
- The above branch is abandoned, I cherry-picked commits from it.

Update document to add tutorials + more easy connection to installation

---

espnet2/enh/loss/criterions/time_domain.py

I modified `espnet2/enh/loss/criterions/time_domain.py:446`:
```
-    @torch.cuda.amp.autocast(enabled=False)
+    @torch.amp.autocast('cuda', enabled=False)
```
---
There is a FutureWarning when I use espnet2:
.venv/lib/python3.10/site-packages/espnet2/enh/loss/criterions/time_domain.py:446: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
---
Yes
---
Please update the PyPI package to latest version! It is still 202412!

Fix FutureWarning `torch.cuda.amp.autocast(args...)` is deprecated

---

tools/installers/install_transformers.sh

This pull request includes a small change to the `tools/installers/install_transformers.sh` script. The change modifies the `pip install` command to include the `soxr` package alongside the `transformers` package.

Update transformers installation

---

.github/workflows/ci_on_ubuntu.yml
ci/install.sh
ci/test_integration_espnet1.sh
ci/test_python_espnet1.sh
espnet/asr/asr_mix_utils.py
espnet/asr/pytorch_backend/asr.py
espnet/asr/pytorch_backend/asr_mix.py
espnet/lm/lm_utils.py
espnet/nets/pytorch_backend/e2e_asr.py
espnet/optimizer/chainer.py
espnet/scheduler/chainer.py
espnet/utils/deterministic_utils.py
espnet/utils/dummy_chainer.py
espnet/utils/training/evaluator.py
espnet/utils/training/iterators.py
espnet/utils/training/tensorboard_logger.py
espnet/utils/training/train_utils.py
tools/Makefile

Move code related to disabling Chainer from the default installation. Ref: #6221
This pull request focuses on deprecating Chainer support in the codebase and making ESPnet robust to environments where Chainer is not installed. It introduces dummy classes to allow the code and CI to run without Chainer, adds warnings and instructions for users, and updates the installation and testing scripts accordingly. Chainer is now optional, and users are notified that it will be removed in the next release.
**Chainer deprecation and compatibility**
* Added try/except imports for Chainer throughout the codebase, logging a warning and falling back to dummy classes in `espnet.utils.dummy_chainer` when Chainer is not installed. This ensures the codebase can run (with limited functionality) without …

Disabling Chainer from default installation

---

egs2/TEMPLATE/tts1/tts.sh

---
Fix the bug that makes versa always use gpu even when gpu_inference is False
---
Previously, the code used --use_gpu False to tell Versa Scorer not to use a GPU. However, versa reads the existence of this option as True, leading to exception when the node doesn't have gpu.
---

Fix GPU flag handling in tts.sh script

---

.github/workflows/ci_on_ubuntu.yml
egs/tedlium2/align1/path.sh
espnet/bin/asr_align.py
espnet2/bin/asr_align.py
espnet2/bin/s2t_ctc_align.py
setup.py
tools/Makefile

After this PR is merged, I am planning to patch the release to fix the pip package build.
This pull request updates the way certain dependencies are installed for the project, specifically moving the installation of `g2p_en` and `ctc-segmentation` from `setup.py` to the `Makefile` due to package build issues. Additionally, it updates installation instructions for `ctc-segmentation` in the alignment script.
Dependency management improvements:
* Moved installation of `g2p_en` and `ctc-segmentation` from `setup.py` to `tools/Makefile` to address package build issues, ensuring these are installed via pip from their respective GitHub repositories during the build process. [[1]](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L27-L36) …

Package Build Patch

---

espnet3/trainer/callbacks.py
espnet3/trainer/trainer.py
test/espnet3/test_callback.py

* Added a new module: `espnet3/trainer/callbacks.py`, which includes:
* `AverageCheckpointsCallback`: a custom Lightning callback for averaging top-K model checkpoints.
* `get_default_callbacks()`: a utility to create a standard set of callbacks including checkpointing, progress bar, and LR monitoring.
* Integrated `get_default_callbacks` into the training loop in `espnet3/trainer/trainer.py`.
* Created a new test module `test/espnet3/test_callback.py`:
---
* To support checkpoint ensembling by averaging top-K models.
* To standardize callback configuration in the trainer, ensuring consistency and reusability.
* To ensure correctness and robustness of the new logic via a comprehensive test suite.
---
Yes. 3 files changed, ~500 additions.
---
* #6133
* #6139 
* #6167 
* #6171 
* #6172 
* …

[espnet3-7](2) Add Callbacks
